---
title: プライバシーポリシー
description: Ribose Open プライバシーポリシー
revision_date: 2023-11-15
revision_date_template: "最終改訂日：{{ revision_date | date: '%Y年%-m月%-d日' }}"
layout: page
hero_include: index-page-hero.html
---
:page-liquid:

CAUTION: このページは英文版の翻訳であり、参考用です。日本語版と英語版に不一致がある場合は、+++<a href="https://open.ribose.com/privacy/">英語版</a>+++が優先されます。

== はじめに

. お客様のプライバシーはRiboseにとって極めて重要です。当社は、お客様が共有される情報を保護することに専念しています。

. 本プライバシーポリシーは、当社がお客様から収集する、またはお客様が当社に提供する個人情報が当社によって処理される基礎を定めています。

. 本プライバシーポリシーはすべてのサービスに適用され、Riboseが事業を展開する管轄区域のプライバシー法に準拠していることを示すために作成されています。当社はデータ保護法規に従ってお客様の個人情報を取り扱います。

. また、Riboseによるお客様の個人情報の使用に関する選択肢、および個人情報にアクセスし、当社に修正または削除を依頼し、またはお客様の個人情報の取り扱いについて苦情を申し立てるためにとることができる措置についても説明しています。

. アカウントの登録、その使用、および本プライバシーポリシーの条項の受諾は、お客様が本プライバシーポリシーを確認し、それに拘束されることに同意したことを示します。

. アカウントを登録する前（またはサービスの使用を継続する前）に本プライバシーポリシーを受け入れることが必要であり、アカウントを使用するユーザーも、アカウントを通じてサービスに初めてアクセスする（またはアクセスを継続する）前に、本プライバシーポリシーを明示的に受け入れることが必要です。これらの条項に同意しない場合は、直ちに当社のウェブサイトを離れる必要があります。本プライバシーポリシーを受け入れることを選択した場合、当社はこの点に関するお客様の受諾の記録を保持します。

== 用語と定義

. 本書類における「Ribose」、「当社」、および「弊社」は、Ribose Inc.（米国）、Ribose Limited（英国）、およびRibose Asia Limited（香港）を含むRiboseグループの会社を総称しています。

. 「サービス」は、Riboseが提供するすべての製品およびサービスを指し、それぞれが「サービス」と呼ばれます。

. 「お客様のアカウント」は、お客様が作成したサービスの登録アカウントを指します。

. 「個人情報」は、データから、または当社が所有または入手する可能性がある他の情報と組み合わせてデータから識別される、または識別可能な生存個人に関連するデータを指し、データ保護法規に記載されている個人データを含みます。

. 「データ保護法規」は、香港個人資料（私隠）条例およびカリフォルニア州消費者プライバシー法、1988年および2003年のデータ保護法、指令95/46/ECなど、個人データの処理およびプライバシーに関連するその他の適用法または規制を指し、一般データ保護規則（EU）2016/679（以下「GDPR」）（およびGDPRを実施または補完する法律）の施行を含め、そのような法規は随時改正、改訂、または置換されます。

. 「ユーザーデータ」は、お客様または他者がお客様のアカウントを通じてアップロードしたデータ（個人情報を含む可能性がある）を指し、ユーザー資格情報、サービスに関連してユーザーまたは他者に共有されたデータ、および/またはサポートリクエスト中にお客様が提供した個人情報など、お客様または他者がサービスに関連して提供または使用する情報、データ、または資料である場合があります。Riboseはユーザーデータに関するデータ処理者（データ保護法規に定義）です。

. 「外部リソース」は、Riboseが運営していないリソースを指します。

== 当社がお客様から収集する情報

当社は、サービスとのやり取りに関連してお客様のプライバシー権を完全に尊重し、どのような情報を収集し、お客様の情報をどのように使用するかについて、お客様との取引において透明性を保つよう努めています。

=== お客様が提供する情報

. Riboseが保有する個人情報の大部分は、お客様（ユーザー）から提供されています。当社は、法的に権限がある場合にのみ、個人の情報を収集および使用します。

. アカウントおよびプロファイル情報。サービスのユーザー（以下「ユーザー」）になるには、個人情報を提供する必要があります。当社は、アカウントの登録、プロファイルの作成または変更、設定、サービスへのサインアップまたは購入を行う際にお客様に関する情報を収集します。登録プロセスでは、氏名、パスワード、メールアドレスの提供が求められます。また、プロフィール写真や、誕生日、電話番号などの詳細をプロファイル情報に追加して、サービスに表示することもできます。サービス内で入力された設定を追跡します。Riboseには実名および有効な連絡先情報の提供が求められますが、エイリアス（「スクリーン名」）を使用して、スペースや会話などのすべてのアクティビティに参加できます。

. サービスを使用して提供するコンテンツ。このコンテンツには、会話、カレンダー、連絡先、スペースメンバーシップなど、プラットフォームおよびそのアプリケーションに入力した情報が含まれます。また、自分の連絡先ソースから特定の連絡先をRiboseにアップロードすることもできますが、Riboseはユーザーのアドレス帳全体のコピーを作成および保存しません。アップロードした連絡先は、スペースに招待してユーザーになることを選択した場合、またはスペースコンテンツ（アップロードされたファイルや会話など）にそれらに関する情報を明示的に含めた場合を除き、お客様のみがアクセスできます。

. サポートチャネルを通じて提供する情報。これには、サービスのカスタマーサポート機能に提供された情報およびやり取りが含まれ、サポートチームに提供された情報が含まれます。報告された特定のサポートケースを解決するために、連絡先情報およびその他の必要な情報の提供が求められる場合があります。

. 支払情報：特定の有料サービスに登録する際、特定の支払いおよび請求情報を収集します。

=== サービスの使用から自動的に収集する情報

. 当社は、サービスの使用（ウェブサイトの閲覧やサービス内での特定のアクションの実行を含む）の際にお客様に関する情報を収集します。

. サービスの使用。当社は、お客様がサービスとやり取りする際、使用する機能やそのパラメータなどの特定の情報を追跡します。また、お客様がやり取りするスペースおよびユーザーに関する情報も収集します。

. Cookie。当社のCookieページでは、使用するCookieについて説明しています。ブラウザを設定してCookieを拒否できます。ただし、Cookieが無効になっている場合、一部のサービスが正しく機能しない場合があります。

. サーバーログ。お客様がサービスにアクセスすると、当社のサーバーは自動的に特定の情報を記録します。これには、IPアドレス、ブラウザタイプ、ブラウザ言語、ウェブリクエスト、サービスとのやり取り、リクエストの日時、サービスを使用する前にアクセスしたウェブページのアドレス、およびCookie情報（上記参照）が含まれる場合があります。

. クライアント情報。ブラウザまたはモバイルアプリケーション（以下「クライアントデバイス」）を通じてサービスにログインすると、当社のサービスはクライアントデバイスが当社のサービスに送信する情報を自動的に記録します。この情報には、クライアント設定およびプラグイン、言語設定、アプリケーション識別子、クラッシュデータが含まれます。

. 通信。お客様がサービスのユーザーであるかどうかにかかわらず、お客様とRibose間の通信を保持します。Riboseのニュースレター、ウェビナー、その他の通信にサインアップした場合、または一般的にお問い合わせになりたい場合は、リクエストを満たすために連絡先情報を収集します。カスタマーサポートを提供している間に、お客様から追加情報を収集する場合があります。

. 位置情報。特定のサービスは、IPアドレスから提供されるよりも詳細な位置認識を必要とする追加機能を提供する場合があります。詳細な位置情報は、明示的に通知された上で、これらのサービスを利用することを選択した場合にのみ収集されます。

=== 他のソースから受信する情報

. サービスとサードパーティの統合。特定のサービスは、連絡先のインポートなど、サードパーティサービスへのユーザー設定統合を許可します。これらの統合から受信する情報は、サードパーティサービスのパラメータに依存します。

. パートナー。当社は、リセラー、インテグレーター、またはインフラストラクチャプロバイダーなど、独自のサービスと補完的なサービスを提供するパートナーと協力しています。これらのパートナーは、サービスへの興味と使用、およびサービスの使用を維持するために必要なその他の情報と連絡先に関する情報を提供します。

. サービスへの外部アクセス。一部のサービスは、他のサードパーティウェブサイト上でまたはそれらを通じて提供されます。それらのサイトに提供された個人情報は、サービスをお客様に提供するためにRiboseに送信される場合があります。そのような情報は、Riboseが保持している間、本プライバシーポリシーによって保護されます。

. サードパーティ。マーケティングおよび広告会社は、サービスへの興味に関する情報を提供する場合があります。

== 収集した情報の使用方法

. Riboseは、保有する個人情報を使用して、サービスを提供および改善し、RiboseおよびRiboseユーザーの権利および財産を保護します。

. サービスの提供およびエクスペリエンスのパーソナライズ。当社は、認証、サポートの提供、必要なトランザクションの処理など、サービスをお客様に提供するために個人情報を使用します。サービスには、プロフィール写真をアップロードする機能など、パーソナライズ機能が含まれる場合があります。コラボレーション機能を含むサービスでは、個人名によってユーザーを識別する必要があります。

. お客様とのコミュニケーション。当社は、アクティビティ通知やカスタマーサポート、サービス自体の更新など、サービスの使用に関するメッセージをお客様に送信するために個人情報を使用します。ほとんどの場合、これらの通信は、アカウント内の設定エリアを通じてカスタマイズできます。

. Riboseが保有する個人情報は、ユーザーが行った選択に従ってのみ使用および開示されます。例えば、コラボレーションスペースに参加して会話に参加する場合など。各スペースのプライバシー設定は、その所有者/管理者によって設定されます。スペースに参加するユーザーはこれらの設定について知らされ、参加することによってそれらを受け入れます。

. サーバーログ。当社はこの情報を使用してサービスを管理し、訪問者がサービスをどのようにナビゲートするかを理解し、サービスを使用するエクスペリエンスを向上させます。

. 通信。Riboseは、お客様の問い合わせに対応し、サービスを改善するためにこの情報を使用します。

. Cookie。Riboseは、ログインおよび登録プロセスを促進し、エクスペリエンスをパーソナライズし、ユーザートレンドを分析および追跡し、広告およびプロモーションの効果を測定するために、Cookieを使用してサービスの品質を向上させます。

. IPアドレス。当社は、より良いサービスエクスペリエンスを提供するために、IPアドレスおよび/または国の設定を使用してお客様の位置を概算します。

. 位置情報。この情報を、IPアドレスから派生した情報（例：地域的位置）と組み合わせて、ユーザーエクスペリエンスを向上させる（例：特定の言語の使用や天気の表示）ために使用する場合があります。

=== お客様の情報の共有方法

. Riboseは、お客様の同意なしに、または法律で義務付けられている場合を除き（本プライバシーポリシーに規定されている場合を除く）、お客様のデータを共有しません。Riboseは、以下の状況でのみ第三者（非ユーザー）に個人情報を開示します。

. サービスのユーザーとコラボレーションを促進する。サービスの機能を使用してコンテンツを他のユーザーと共有でき、そのユーザーはコンテンツの発信元を識別するために特定の個人情報（お客様の名前など）を見ることができます。

. 組織アカウント管理者と管理。サービスへのアクセスが組織アカウントによって付与されている場合、お客様のアカウント情報および使用状況は、組織アカウント所有者および所有者によって許可された人によってアクセスできます。

. Riboseグループ内。第三者がRiboseグループの一部であり、その情報がサービスを提供するために必要な場合。個人情報へのアクセスは、Riboseのために処理する必要があるRiboseの従業員、請負業者、および代理人に制限され、機密保持要件に拘束されます。

. 契約当事者とプロビジョニングを促進する。Riboseと契約したサービスプロバイダーは、支払処理およびサービスをお客様に提供するために必要なその他のサービスの実行を支援し、そのために個人情報へのアクセスまたは使用が必要です。契約当事者は、本プライバシーポリシーに準拠してそのような情報を処理する必要があります。

. サードパーティと。特定の第三者とそのような情報を共有することを明示的に同意した場合にのみ、外部当事者と情報を共有します。

. サードパーティサービスとの統合。お客様のアカウントは特定のサードパーティサービスと統合するように設定されている場合があり、その結果、それらのサードパーティにお客様のアカウントおよびその中の情報へのアクセスを許可する場合があります。本プライバシーポリシーはサードパーティがお客様の情報をどのように使用するかをカバーしていないため、それらのサードパーティサービスのプライバシーポリシーを確認することをお勧めします。

. 明示的な同意。特定の場合、公開された成功事例にお名前を配置するなど、特定の個人情報を表示することを許可する明示的な同意を提供する場合があります。

. 安全を確保する。善意的に、開示がお客様または他者の健康または安全のために必要であると信じる場合。

. 法律を遵守する。召喚状（または類似の法的プロセス）または執行可能な政府の要求に準拠するなど、法律によりRiboseが情報を開示するよう求められている場合。Riboseは、法律で禁止されていない限り、個人情報の開示の法的拘束力のある要求を受領した際にお客様に通知します。

. 権利を保護する。善意的に、開示が当社の権利を保護し、本規約を執行し、詐欺、セキュリティ、または技術的な問題を検出、防止、またはその他の方法で対処するために必要であると信じる場合。そのような情報は、適用法および規制に従って開示されます。

. 事業譲渡。サービスが合併、買収、またはその資産の一部または全部の何らかの形態の売却に関与する場合、お客様のデータが異なるプライバシーポリシーの対象になる前に通知を提供します。

== 子供によるサービスの使用

. Riboseは組織および13歳以上の個人にのみサービスを提供し、年少の子供を対象としたサービスは提供しません。ユーザーとして参加する個人は、13歳以上であることを確認する必要があります。

. 13歳未満の子供が個人情報を提供したことを知った場合、当社はそのような情報を削除する措置を講じます。子供が個人情報を提供したことを知った場合は、当社に連絡してください。

== 情報の保存および保護方法

=== 情報の保護方法

. Riboseは個人情報の保護のセキュリティを真剣に受け止めています。個人情報への不正アクセス、または不正な変更、開示、または破壊から保護するために適切なセキュリティ対策を講じています。準拠しているセキュリティスキームおよび不正アクセスと開示から保護するための具体的なセキュリティ措置の詳細は、当社のウェブサイトで提供されています。

=== 情報の保持期間

. 個人情報。Riboseは、お客様のアカウントが使用しているサービスを提供するために必要な期間、および適切なバックアップおよびアーカイブ目的のために個人情報を保持します。ユーザーが削除された場合、ユーザーに関連する個人情報のみが直ちに削除されますが、サービスを再アクティブ化することを決定した場合に備えて、その後の合理的な期間、バックアップからは削除されません。

. 共有情報。この情報は、それを含むスペースの所有者、またはそのスペースを所有する組織アカウントの管理下に残ります。Riboseは、それらのスペースおよび/または組織アカウントにサービスを提供するために必要な期間、この情報を保持します。

. その他の義務。また、法的義務を遵守し、紛争を解決し、契約を執行し、ビジネス運営をサポートし、サービスの開発および改善を継続するために必要に応じて、お客様の情報の一部を保持します。サービスの改善および開発のために情報を保持する場合、そのような情報を匿名化する措置を講じ、お客様に関する個人的な特徴を具体的に分析するのではなく、サービスの使用に関する集合的な洞察を発見するためにのみこの情報を使用します。

. マーケティング情報。当社からのマーケティングメールを受け取ることを選択した場合、最後にサービスへの関心を示した日（最後に当社のメールを開いた日やサービスの使用を中止した日など）から合理的な期間、マーケティング設定に関する情報を保持します。Cookieおよびその他の追跡データから派生した情報は、そのような情報が作成された日から合理的な期間保持します。

== 個人情報の国際移転

. Riboseが保有する個人情報は、アメリカ合衆国に所在するサーバーで処理されます。

. サービスを使用したトランザクションおよび通信は、参加ユーザーが所在する管轄区域で少なくとも一時的に情報が保持されることを伴います。

. 一部のサービスでは、サービスのデータ処理およびストレージが行われる管轄区域（アメリカ合衆国および香港を含む）を明示的に選択できます。その場合、関連する必要な個人情報も、選択された管轄区域に所在するサーバーで処理されます。

. サービスのために処理される情報は暗号化された状態で保存および送信されるため、意図された参加者またはRiboseの許可された担当者以外、いかなる管轄区域でも、誰も個人情報を「クリア」で見ることはできません。

== お客様の権利

サービスの設定エリアから、一般的に基本個人情報にアクセス、確認、変更できます。Riboseに個人情報のコピーをリクエストできます。このサービスには少額の料金を請求する場合があります。アカウントを削除することにより、Riboseに個人情報の処理の撤回、制限、または異議申し立てをリクエストできます。Riboseが収集したデータを別の組織または直接お客様に転送することをリクエストできます。

個人情報に関連する問題については、サービスのフィードバックまたは{{ site.emails.privacy }}を通じてRiboseに手動リクエストを行う必要があります。アクセス、変更、または削除をリクエストする情報を特定し、身元を証明する必要があります。不相応な努力を必要とする、または他者の権利を侵害する可能性がある手動リクエストを拒否する場合があります。削除リクエストを受け入れた場合、法律で保持が義務付けられておらず、正当なビジネス目的に必要ない限り、通常1ヶ月で、サービスに保存されている個人情報の削除プロセスを開始します。サービスの構造上、個人情報が削除された後、残留コピーが当社のサービスおよびバックアップシステムから削除されるまでに150日を超えない場合があります。

== 外部リンクおよびアプリ

本プライバシーポリシーは、当社のサービスにのみ適用されます。当社のサービスは、Riboseが運営していないリソース（以下「外部リソース」）へのリンクを提供する場合があります。外部リソースに個人情報を提供することを選択した場合、個人情報はそのプライバシーポリシーの対象となります。訪問する外部リソースのプライバシーポリシーを注意深く読むことをお勧めします。

== 違反報告

. 重大なデータ違反が発生した場合、当社は遅延なく、可能な場合は72時間以内に、お客様のデータに関する重大なデータ違反をDPCに通知します。72時間後に通知が行われない場合、遅延の正当な理由を記録します。ただし、個人情報違反が自然人の権利および自由にリスクをもたらす可能性が低い場合、DPCに通知する必要はありません。この文脈における個人情報違反は、送信、保存、またはその他の方法で処理された個人情報の偶発的または違法な破壊、紛失、改ざん、不正開示、またはアクセスにつながるセキュリティ違反を指します。

. 当社は、その影響および講じられた是正措置を含むデータ違反の記録を保持し、データ保護法規に従って必要な場合、お客様の個人情報に影響を与えるデータ違反（お客様に高いリスクをもたらすもの）について通知します。以下の場合、データ違反について通知する必要はありません：

.. 暗号化など、許可されていない者がアクセスできないように個人情報を解読不能にする適切な技術的および組織的措置を実施している場合。または

.. データ主体への高いリスクが実現しないことを確保する後続の措置を講じている場合。または

.. 不相応な努力を伴う場合、その場合、公開コミュニケーションを行うことができます。

. ユーザーデータに関する重大なデータ違反が発生した場合、当社は合理的に実行可能な限り迅速に関連するデータ管理者に通知します。

== プライバシーポリシーの変更

. 当社は随時本プライバシーポリシーを変更する場合があります。最新の改訂日は本ページに表示されます。プライバシーポリシーに重要な変更が加えられた場合、ウェブサイトにより目立つ通知を掲載するか、これに関する通知を送信してお客様に通知します。

. 本プライバシーポリシーの変更に同意しない場合、サービスの使用を停止し、アカウントを無効化する必要があります。

== お問い合わせ

本プライバシーポリシーについてご質問がある場合、または個人情報の取り扱いについてお問い合わせになりたい場合は、{{ site.emails.privacy }}までメールをお送りいただくか、お問い合わせページに記載されている住所までご連絡ください。
