---
title: 利用規約
description: Ribose 利用規約
revision_date: 2023-11-16
revision_date_template: "最終改訂日：{{ revision_date | date: '%Y年%-m月%-d日' }}"
layout: page
hero_include: index-page-hero.html
---
:page-liquid:

CAUTION: このページは英文版の翻訳であり、参考用です。日本語版と英語版に不一致がある場合は、
https://www.ribose.com/tos/"[英語版]
が優先されます。

== 条款

. Riboseは、Ribose Inc.（英領バージン諸島法人）（以下「Ribose」、「当社」または「弊社」）のRibose製品、ソフトウェア、サービス、ウェブサイト（以下「サービス」）の唯一の所有者です。

. 以下に示すのは、サービスの利用に関する利用規約および条件（以下「一般条項」）です。

. 特定のサービスには、追加の法的通知および/または条項（以下「追加条項」）が適用される場合があります。

. 一般条項と追加条項は、お客様とRiboseとの間の法的拘束力のある契約（以下「本規約」）を構成します。追加条項が適用される特定のサービスについて、追加条項と一般条項の間に競合がある場合は、追加条項が優先されます。

== 承諾

. サービスのご利用は、お客様が本規約に拘束されることに同意したことを意味します。本規約に同意するためにクリックすることも、本規約の承諾を意味します。

. 本規約の更新については、定期的に確認することをお勧めします。継続してサービスをご利用になることは、変更された項目の承諾を意味します。一般条項は link:/tos/[利用規約]にあります。

== サービスの提供

. Riboseの子会社および関連法人（以下「子会社および関連会社」）は、Riboseを代表してサービスをお客様に提供する場合があります。子会社および関連会社がサービスをお客様に提供する権利を有することをお客様は承認し、同意します。

. Riboseは、ユーザーに最高のエクスペリエンスを提供することに専念しています。サービスの形式および性質は、事前の通知なく随時変更される場合があることをお客様は承認し、同意します。

. Riboseは、独自の裁量により、事前の通知なく、サービスの一部または全部をお客様に一時的または永続的に提供を停止する場合があります。Riboseに特に通知することなく、いつでもサービスの利用を停止できます。

. Riboseがお客様のアカウントへのアクセスを無効にした場合、サービス、お客様のアカウント詳細、またはお客様のアカウントに関連するコンテンツにアクセスできなくなる場合があることをお客様は承認し、同意します。

. Riboseは現在サービスの取引または容量に制限を設けていない場合がありますが、そのような制限はRiboseの独自の裁量により、事前の通知なくいつでも設定または変更される場合があることをお客様は承認し、同意します。

. お客様がRiboseに提供するデータは、タイプおよび発生源に従って分類される場合があります。お客様は、サービスに関連するデータに適用される法律または規制によって禁止されている目的でサービスを使用しないことを表明し、保証し、サービスおよびコンテンツのご利用はお客様自身のリスクで行われることに同意します。

== 知的財産

. サービスに対するすべての法的権利、権益、および利益をRiboseが所有していることをお客様は承認し、同意します。これには、サービスに存在する知的財産権が含まれます。そのような権利は、それらの権利の登録ステータスに関係なく、世界中でRiboseに帰属します。

. サービスには、Riboseが機密として指定した情報が含まれる場合があります。Riboseの事前の書面による同意なしに、そのような情報を開示しないことに同意します。

. サービスおよびそのすべてのコンテンツ（記事、テキスト、写真、画像、イラスト、グラフィック、ビデオ素材、オーディオ素材、ソフトウェア—総称して「知的財産」）は、特許、著作権、商標、および各国の法律および国際条約によって保護されています。知的財産はRiboseが所有または管理しています。サービスは特許および発明（以下「特許および発明」）によって保護されています。さらに、サービス自体は編集著作物および/または編集物として著作権によって保護されています。

. Riboseによって明示的に許可されていない限り、商業目的でサービスの一部を複製、複写、コピー、販売、またはその他の方法で利用することはできません。

. 本規約に明示的に規定されている場合を除き、知的財産またはサービス自体、またはその一部を複製、ダウンロード、表示、配布、公開、データベースに入力、実演、変更、派生物を作成、送信、投稿、逆コンパイル、リバースエンジニアリング、分解、またはその他の方法で利用することはできません。

. サービスに付属または含まれる可能性のある所有権に関する通知（著作権および商標通知を含む）を削除、隠蔽、または変更しないことに同意します。

. Riboseの名称およびRiboseブランドのシール、ロゴ、関連マークは、Riboseの登録商標/デザイン商標、またはRiboseの信用を運ぶその他の未登録商標です。全著作権所有。本規約のいかなる内容も、Riboseの商号、商標、サービスマーク、ロゴ、ドメイン名、その他の識別的なブランド特徴を使用する権利をお客様に与えるものではありません。

. Riboseとの別個の書面による契約によってこれらのブランド特徴を使用することが明示的に許可されている場合、そのような特徴の使用は、その契約、本規約、およびRiboseのブランド特徴ガイドラインに準拠することに同意します。Riboseのブランド特徴ガイドラインは、{{ site.emails.support }}にメールでリクエストできます。

.. 特許および発明または特許および発明から生じる特許または特許出願の有効性、執行可能性、または範囲を直接または間接に異議を唱えること、および前述の一般性を制限することなく、審査手続きに干渉しないこと、または特許および発明に関する反対手続きまたは司法無効訴訟（完全または部分）を開始または参加しないことに同意します。または

.. 特許および発明に基づく、または特許および発明から生じる特許出願を提出、または提出させること。これには、改良特許出願または特許、特許および発明に関連するまたは基づく特許、または特許および発明を回避する設計の特許出願または特許が含まれますが、これらに限定されません。特許および発明に基づく、または特許および発明から生じる発明は、Riboseが単独で所有し、そのような発明をRiboseに譲渡することに同意します。

== アカウント情報とセキュリティ

. 特定のサービスにアクセスするため、またはサービスの継続利用のために、お客様に関する情報（以下「個人情報」）の提供が必要になる場合があります。そのような情報は、サービスの登録プロセス中またはサービスの継続利用を通じて要求される場合があります。お客様がRiboseに提供する個人情報は、常に正確、正しい、最新であることに同意します。

. サービスへのアクセスのためのアカウントへのアクセス制御（サービスへのアクセスのためのアカウントアクセス資格情報の機密保持を含む）について、お客様が単独で責任を負うことを理解し、同意します。したがって、お客様のアカウント下で発生するすべてのアクティビティについて、Riboseに対してお客様が単独で責任を負うことに同意します。

. お客様のアカウントまたはアクセス資格情報の不正使用を知っている場合は、直ちに{{ site.emails.support }}でRiboseに通知することに同意します。

. Riboseのプライバシーポリシーに従ってお客様のデータが使用されることに同意します。Riboseのプライバシーポリシーは link:/privacy/[プライバシー通知]にあります。

== 適切な使用

. 本規約によって違法または禁止されている目的でサービスを使用すること、またはサービス上で損害を与えることはできません。サービス上またはサービスを通じたお客様のアクションは、適用される地方、州、国、または国際の法律、規制、一般的に受け入れられている慣行またはガイドラインに違反しないことを約束します。

. Riboseとの別個の契約で特に許可されていない限り、Riboseが提供するインターフェースを通じてのみサービスにアクセスすることに同意します。スクリプトやクローラーを含む自動化された手段を使用してサービスにアクセスまたはアクセスを試みないことに同意します。

. サービスまたはそのサポートの一部を妨害または破壊する活動、またはサービスを構成または促進する活動に従事または従事を試みないことに同意します。

. 本規約または適用法に違反するまたは違反するとされる方法でサービスを使用した結果として、またはその結果として主張される、実際または脅威されたクレーム、アクションまたは要求、責任および和解（合理的な法務および会計費用を含むがこれらに限定されない）から、Ribose、その役員、取締役、従業員、代理人、ライセンサー、ビジネスパートナー、およびサプライヤーを擁護、補償、および保護することに同意します。

== コンテンツ

. サービスの一部としてまたはサービスを通じてアクセス可能な情報は、Ribose以外の第三者（以下「コンテンツ」）から発信される場合があります。そのようなコンテンツは、そのコンテンツが発信された当事者の単独の責任です。Riboseは、そのようなコンテンツについていかなる表明、推奨、または保証も行わず、そのようなコンテンツの一部について責任または義務を負いません。

. サービス内またはサービスを通じて提示される特定のコンテンツ（広告およびスポンサーコンテンツを含む）が、そのようなコンテンツをRiboseに提供する第三者が所有する知的財産である可能性があることを理解しています。そのコンテンツの所有者から許可を得ていない限り、そのようなコンテンツの全部または一部を修正、賃貸、貸与、販売、配布、または派生物を作成しないことに同意します。

. Riboseは、サービスからコンテンツをスクリーニング、フィルタリング、レビュー、修正、拒否、または削除する権利を留保します。

== お客様のコンテンツ

. Riboseは、本規約に基づいて、お客様（またはお客様のライセンサー）から、お客様がサービス上またはサービスを通じて投稿、投稿、または表示するコンテンツに対して、以下に規定する限定されたライセンスを除き、権利、権名、または利益を取得しません。お客様の権利を保護し執行することはお客様の単独の責任であり、Riboseはお客様に代わってそうする義務がないことに同意します。

. サービスを通じてまたはサービス内で作成、送信、または表示するコンテンツについて、お客様が単独で責任を負うこと（およびRiboseがお客様または第三者に対して責任を負わないこと）、およびしたがって、そのようなアクションの結果（Riboseへの損害または損失を含む）について単独で責任を負うことに同意します。

. 会社または組織の商標、サービスマーク、商号、ロゴを、そのようなマーク、名前、またはロゴの所有者または許可ユーザーについて混乱を招く可能性がある、または意図する方法で使用しないことに同意します。

. サービス上またはサービスを通じて投稿、投稿、または表示するコンテンツ（以下「お客様のコンテンツ」）について、お客様はRiboseに、Riboseがサービスを表示、配布、提供、および促進することを可能にする唯一の目的のために、お客様のコンテンツを複製、適応、修正、翻訳、公開、公開実演、公開表示、および配布する永続的、取消不能、世界的、ロイヤリティフリー、および非独占的なライセンスを付与します（以下「コンテンツライセンス」）。

. Riboseは、他の当事者と共同でまたは共同してシンジケートサービスを提供する場合があります。お客様は、Riboseがシンジケートサービスの提供のためにRiboseが関係を持つ他の当事者にお客様のコンテンツを利用可能にし、コンテンツライセンスに基づいてそれらのサービスの提供に関連してそのようなコンテンツを使用することを許可します。

. お客様がコンテンツライセンスを付与するために必要なすべての権利、権限、および権限を持っていることをRiboseに確認し、保証します。さらに、Riboseが第三者のいかなる権利も侵害せず、お客様のお客様のコンテンツのRiboseへの投稿またはサービスの提供の結果としていかなる種類の責任または損害も負わないことを確認し、保証します。

== 広告コンテンツ

. Riboseがサービスに広告を配置する場合があることに同意します。一部の広告またはプロモーションは、サービスに保存されているまたはサービスに関連する特定の情報に対してターゲットされる場合があります。サービスにおけるRiboseによる広告の形式、性質、実装は、事前の通知なく変更される場合があります。

== 外部コンテンツ

. サービスは、Riboseが運営していないリソース（以下「外部リソース」）へのリンクを提供する場合があります。Riboseは外部リソースについて責任を負わないため、外部リソースへのアクセスまたは外部リソースへの依存の結果としてお客様が被る可能性のある損失または損害について責任を負わないことをお客様は承認し、同意します。

. Riboseは、事前の通知を与えることなく、およびその側に責任を負うことなく、外部リソースを削除またはリンク解除する権利を留保します。

. 外部リソースにおけるRiboseの担当者の引用またはコメントは、Riboseの意見を反映していないことをお客様は承認し、同意します。

== Riboseソフトウェア

. Riboseは、サービスの一部としてまたはサービスの提供を促進するためにRiboseから提供されるソフトウェア（以下「ソフトウェア」）を使用するための、個人的、世界的、ロイヤリティフリー、譲渡不可、非独占的なライセンスをお客様に付与します。このライセンスは、本規約に従ってサービスを使用することを可能にする唯一の目的のためです。

. 法律で義務付けられている場合またはRiboseから書面で明示的に許可されている場合を除き、ソフトウェアまたはその一部を複製、ダウンロード、表示、配布、公開、データベースに入力、実演、修正、派生物を作成、送信、投稿、逆コンパイル、リバースエンジニアリング、分解、ソースコードを抽出しようとする、またはその他の方法で利用することはできません。

. ソフトウェアは、Riboseから随時更新が必要な場合があります。サービスの提供をお客様に容易にするために、そのような更新を受け取り、Riboseがそれらをお客様に提供することを許可することに同意します。

== 取引

. サービスの特定の領域では、1つ以上のRiboseプログラムに参加申し込みができます。それらのプログラムの条項および申し込み登録と参加を管轄する条項は、そのプログラムのライセンス契約に規定されています。電子またはその他の形式の注文確認を受信したことは、お客様の申し込みの受諾を意味するものではなく、プログラムへの受諾を構成するものでもありません。Riboseは、お客様の注文を受領した後、お客様が申し込む特定のプログラムを管轄するライセンス契約に従って、お客様の申し込みを受け入れるか拒否する権利を留保します。

== 終了

. 本規約は、以下に規定されている通りに終了されるまで、適用され続けます。

. 以下により、Riboseとの法的契約を終了できます：

.. 本規約の冒頭に記載されているRiboseの住所に書面による通知を送付することにより、Riboseに通知する。および

.. このオプションが利用可能な場合、すべてのサービスのアカウントを閉鎖または削除する。

. 以下の場合、Riboseはお客様との法的契約を終了する場合があります：

.. 本規約の規定に違反した場合、またはRiboseがお客様が本規約に従うことができないと判断した場合。または

.. Riboseが法律によりそうするよう求められている場合。または

.. Riboseがサービスをお客様に提供できなくなった場合

. 本規約の終了時に、お客様とRiboseが利益を得た、制約された（または本規約が効力を持っていた間に蓄積された）、または無期限に継続すると明示されているすべての法的権利、義務、責任は、この終了の影響を受けず、「保証の否認、責任制限、および免除」および「その他」の条項の規定は、そのような権利、義務、責任に無期限に適用され続けます。

== 保証の否認、責任制限、および免除

. Riboseは、サービスで見つかった情報の正確性を保証しません。サービスで見つかった情報への依存は、お客様自身のリスクで行われます。

. サービスおよびそのすべてのコンテンツは、「現状のまま」提供されます。RIBOSEは、商業可能性、特定目的への適合性、権名、第三者の権利の非侵害、データの正確性、または静かな享受を含むがこれらに限定されない、明示または黙示の保証または表明を行いません。

. いかなる状況下でも、RIBOSEまたはサービスおよびそのコンテンツの作成に関与するその他の者は、サービスまたはそのコンテンツに関連する状況から生じる直接的、間接的、偶発的、特別、結果的、懲罰的、またはその他の損害または傷害について責任を負いません（エラー、省略、中断、欠陥、性能不全、誤った方向または再方向の送信、インターネット接続の失敗、サービスの不正使用、データの損失、操作または送信の遅延、セキュリティ侵害、回線障害、サービスのユーザーの誹謗、攻撃的または違法な行為、またはコンピュータウイルス、ワーム、トロイの木馬、またはその他の有害なコンポーネントによって引き起こされる損害または傷害を含むがこれらに限定されない）。RIBOSEにそのような損害の可能性を事前に通知した場合でも同様です。

. RIBOSEは、サービス上の資料の適時性、正確性、精度、信頼性、またはその他の点について、保証または表明を行いません。サービスに関するRiboseについての正確かつ適時の情報を提供するために合理的な努力を行っていますが、提供される情報が常に最新であると仮定したり、サービスに会社に関する利用可能な関連情報がすべて含まれていると仮定したりしないでください。そのような情報の正確性または最新性を確認または維持する義務を負いません。

. 適用法は、特定の保証の除外または偶発的または結果的損害の責任の制限または除外を許可しない場合があります。したがって、上記の制限または除外の一部はお客様に適用されない場合があります。ただし、いかなる場合でも、損害、損失、および訴訟原因に対するRiboseの総額は、サービスへのアクセスのために支払った金額（ある場合）または100ドルのいずれか低い方を超えないものとします。訴訟原因の発生から1年以内にすべてのアクションを提起することに同意し、この日付以降に提起されたアクションは時効にかかるものとします。

. Riboseとの紛争がある場合、Ribose（および当社の役員、取締役、代理人、および従業員）を、そのような紛争に関連するまたは関連する、既知および未知、疑わしいおよび疑わしくない、開示されたおよび未開示の、あらゆる種類および性質のクレーム、要求、および損害（実際および結果的）から免除します。

== その他

. Riboseは、本規約の違反に対して、法律および衡平法で利用可能なすべての救済措置を求める権利を留保します。これには、サービスへのアクセスの一時停止またはブロックが含まれます。

. 本規約のいかなる内容も、当事者間のパートナーシップを構成または構成するとみなされるものではなく、いかなる当事者も、いかなる方法でまたはいかなる目的のために、他の当事者を拘束する権限または権力を持ち、または他の当事者に対して責任を負わせることはありません。

. Riboseの事前の書面による通知を得ずに、本規約に基づくお客様の権利または義務の全部または一部を譲渡、転送、譲渡、ライセンス、下請け、委任、またはその他の方法で処分しないものとします。

. Riboseによる本規約のいずれかの条項の遅延または不履行は、本規約に基づく当社のいかなる権利の放棄も構成しません。Riboseによるいかなる資金の受領も、いかなる人物の当社のアクションへの依存も、本規約の一部の放棄を構成するものとみなされません。Riboseの授権代表者によって署名された特定の書面による放棄のみが法的効力を持ちます。

. 本規約に規定されている条項または規定が、現在または将来の法律に基づいて違法、無効、または執行不能であると判断された場合、その条項または規定は削除されたものとみなされ、残りのすべての条項または規定の執行可能性に影響を与えません。

== 準拠法および管轄権

. ユーザーは、本規約および本規約および/またはプライバシー通知またはサービスに基づいてまたは関連して生じるいかなる紛争も、法の衝突に関係なく、香港特別行政区の法律に準拠し、解釈されることに同意し、本契約に関連するいかなる紛争についても専属的な場所は香港特別行政区の裁判所とします。ただし、Riboseは常に、他の有管轄権の裁判所でユーザーに対していかなるアクションまたは手続きを提起することを許可され、Riboseは常に他の有管轄権の法を選択することを許可されます。

. この英語版の利用規約声明は、サービスのユーザーに対するRiboseの公式契約です。この英語版の利用規約声明と他の言語への翻訳の間に不一致がある場合、この英語版の文書が優先されます。

. 本契約に適用されないものとして明示的に除外されるのは、国際物品売買条約として知られる法律です。

== 条項の変更

. Riboseは、独自の裁量により、いつでも本規約を修正、変更、またはその他の方法で変更する権利を留保します。そのような変更の通知を一般条項ページで提供します。

. サービスの継続利用は、制限、資格、または変更なしに、これらの変更を受け入れ、同意することを構成します。いつでもこれらの変更を受け入れないと判断した場合は、「終了」セクションを参照して関係を終了してください。

== 詳細情報

. 利用規約についてご質問がある場合は、{{ site.emails.support }}にメールをお送りください。
