= Ribose Open Site

This site is using the Jekyll Open Hub theme.

See https://github.com/riboseinc/jekyll-theme-open-hub[theme documentation].

See https://github.com/riboseinc/open.ribose.com/wiki/Listing-of-open-projects[list of open projects] being added here.

== Introduction

This is the Ribose Open Site (Hub) located at https://open.ribose.com.

The site is implemented as a https://jekyllrb.com[Jekyll] site and configured
in _config.yml. Site data is located in this directory and build gets created
in _site.

== Development

=== Getting started

* Ensure you have reasonable Ruby version
* Run `bundle` from within site directory to install Ruby dependencies

=== Serving the site

* Run `jekyll serve` from within site directory

== Operations

The site is hosted on AWS using S3 behind CloudFront (CF).

=== Getting started

0. Make sure you have AWS CLI tools installed.

1. Obtain from your operations contact an inventory .rc file relevant
   to the environment you’re deploying.
   
   It would contain the variables such as S3_BUCKET, HOSTNAME, AWS_REGION,
   CF_DISTRIBUTION. Do not version that file in the repository!
   
   We’ll assume that file is named ro-site.rc.

2. Add AWS profile to your ~/.aws/credentials. We’ll assume it’s called `ribose-open`.

=== Deployment

Use the provided Rakefile to upload the site and reset CF cache if needed.

Run it like this:

[source,sh]
----
export AWS_PROFILE=ribose-open
source ro-site.rc
rake s3upload
----

== Contributing

. Create your feature branch (`git checkout -b my-new-feature`)
. Commit your changes (`git commit -am 'Add some feature'`)
. Push to the branch (`git push origin my-new-feature`)
. Create new Pull Request
