= Ribose Open Site

== Introduction

This is the Ribose Open Site (Hub) located at https://open.ribose.com.

The site is implemented as a https://jekyllrb.com[Jekyll] site and configured
in _config.yml. Site data is located in this directory and build gets created
in _site.

== Development

=== Getting started

* Ensure you have reasonable Ruby version
* Run `bundle` from within site directory to install Ruby dependencies

=== Serving the site

* Run `jekyll serve` from within site directory

== Operations

The site is hosted on AWS using S3 behind CloudFront (CF).

=== Getting started

Exact AWS service setup is outside of the scope of this README.

Obtain from your operations contact an inventory .rc file relevant
to the environment you’re deploying.

It would contain the variables such as S3_BUCKET, HOSTNAME, AWS_REGION,
CF_DISTRIBUTION. Do not version that file in the repository.

=== Deployment

The executable `./scripts/deploy` builds the site, uploads it to S3
and invalidates CF cache.

Run it like this:

[source,sh]
----
source ro-site.rc
./scripts/deploy
----

== Contributing

. Create your feature branch (`git checkout -b my-new-feature`)
. Commit your changes (`git commit -am 'Add some feature'`)
. Push to the branch (`git push origin my-new-feature`)
. Create new Pull Request
