---
layout: post
title: "在線協作：失去人情味和連結？"
date: 2013-11-18 16:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  在線協作：失去人情味和連結？
---
= 在線協作：失去人情味和連結？

想要評論今天在《全球商業樞紐》上發表的一篇文章 ---
Business Hub ---
*http://www.boston.com/business/blogs/global-business-hub/2013/11/tech_changes_ho.html*
-- 該文章討論了通過保持員工參與來保持他們在工作中的快樂的重要性。文章進一步解釋了像 Yammer、Huddle 和 Jive 這樣的社交網絡如何使員工更投入，最終更投入的員工是更高效的員工。作者還討論了我們在個人生活中用來連接和交流的技術也正在成為我們在工作中使用的技術。越來越多，我們在工作中的技術體驗正在模仿家庭中的體驗——使我們的工作生活和個人生活之間的界限更加模糊。

擎威 Ribose 理解這一概念，並且我們的目標是讓人們在工作中也能享受這種「Facebook」體驗。協作不僅應該是一個讓人們更高效的過程，它也應該是人們相互了解以及了解彼此作為同事和個體的方式。文章中的一個關鍵點是，我們在擎威 Ribose 團隊理解的是，千禧一代正在尋求創造一種無縫的工作/娛樂存在，而像我們這樣的嬰兒潮一代則喜歡我們的「不連接」時刻。正是千禧一代推動了在辦公室獲得類似 Facebook 體驗的需求。因此我們問，使用社交協作工具是否將成為我們在辦公室內外溝通的方式？看看我們今天如何使用手機進行短信和電子郵件。 在線協作工具無處不在，既用於個人也用於專業用途。我們相信每個人都在追求那種「Facebook」體驗。

我們的目標是連接所有人，無論他們是千禧一代還是嬰兒潮一代，旨在幫助他們更聰明地工作並在工作中享受樂趣。最重要的是，我們希望人們在協作時能更高效，從而能夠走出辦公室，做自己喜愛的事情，並與人面對面地建立聯繫。技術將使人們能夠以前所未有的方式連接和協作。 一些人認為這會削弱人情味。我們認為，虛擬協作平臺對於與他人合作至關重要。最重要的是，它們也可以有人情味，因為協作就是關於連接和建立關係。
