---
layout: post
title: "擎威 Ribose 獲得 ISO/IEC 27018 認證以保護雲端隱私"
date: 2015-12-17 16:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  擎威 Ribose 獲得 ISO/IEC 27018 認證以保護雲端隱私
---
= 擎威 Ribose 獲得 ISO/IEC 27018 認證以保護雲端隱私

*_獲獎的協作平台符合國際雲端隱私標準_*

[香港] -- 2015 年 12 月 18 日 -- 擎威 Ribose 獲得 ISO/IEC 27018 認證，該國際標準由國際標準化組織（ISO）最近發布，為公共雲中個人可識別信息（PII）處理者提供了保護指南。

作為 ISO/IEC 27001 信息安全管理系統標準的擴展，ISO/IEC 27018 描述了公認的控制目標、控制措施和指南，以確保 PII 數據在由雲 PII 處理者處理時得到充分保護，為在多國市場運營的 CSP 提供了共同的合規框架。基於 ISO/IEC 29100 中包含的十一項隱私原則，ISO/IEC 27018 規定了如何在 ISMS 框架內應用它們，以保護雲端隱私。

此項認證意味著由 Ribose 管理的數據絕不會被出售給第三方用於廣告，也不會分包給可能破壞用戶數據完整性的方。這也意味著用戶對存儲在 Ribose 上的數據保有完全控制權，並且公司對用戶數據的存放位置和處理方式保持透明。

Dale Johnstone, 國際標準化組織（ISO）/國際電工委員會（IEC）JTC1 SC 27 / WG 1 副召集人表示：
「ISO/IEC JTC 1 SC 27 委員會創建和管理 ISO/IEC 27001 家族的標準，其中包括 ISO/IEC 27018 -- 公共雲中個人可識別信息（PII）處理者保護實踐守則。2014 年，ISO/IEC 發布了 ISO/IEC 27018 的第一版，該標準提供了支持 ISO/IEC 27001 中規定的信息安全管理系統的控制指南。Ribose 在推進雲端隱私保護方面投入了大量努力，這一點在其成功完成 2015 年的正式審核過程中得到了認可，我們對他們的所有努力表示讚賞。」

Emmanuel Hervé, 英國標準協會（BSI）亞太區標準專業服務副總裁兼香港分公司總經理表示：
「我們讚揚 Ribose 致力以最高標準保護用戶資訊。作為 ISO/IEC 27000 家族國際信息安全標準的創始機構，BSI 在 ISO/IEC JTC 1 SC 27 開發 ISO/IEC 27018 認證計劃期間與 Ribose 以及 ISO/IEC JTC 1 SC 27 的專家緊密合作，確保我們的嚴謹認證程序能精確評估他們對該標準的遵守情況。」

Ronald Tse, 擎威 Ribose 創辦人，解釋道：「Ribose 很自豪成為第一家為所有用戶（包括付費和免費用戶）提供 ISO/IEC 27018 級別隱私保護的 CSP。我們的認證證明了 ISO/IEC 27018 與現有的全球和區域雲端安全標準（包括 CSA 的 CCM 和 C-STAR、新加坡的 MTCS 和中國國家標準）是互補的。」

「作為雲端安全和隱私的先驅，我們採用 '最高標準' 方法，在我們運營的每個司法管轄區實施最嚴格的國際認證安全標準：香港、美國、英國/歐盟、澳大利亞、新西蘭、新加坡和中國。我們相信隱私是一項權利，而不是奢侈品——保護我們用戶的數據和隱私至關重要」，Tse 總結道。

「在當今互聯的世界中，隱私對於協作工作比以往任何時候都更加重要——這通常包括機密商業數據。隨著越來越多的敏感信息被存儲在雲端，數據洩露的後果可能對組織、用戶及其數據主體造成災難性影響。隱私和安全是最終的區別因素，而 Ribose 已獲得世界上最高標準的認證。」
