---
layout: post
title: "擎威 Ribose 獲得 Red Herring 2015 全球百大獎"
date: 2015-11-26 16:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  擎威 Ribose 獲得 Red Herring 2015 全球百大獎
---
= 擎威 Ribose 獲得 Red Herring 2015 全球百大獎

*成功加入全球科技創新的知名榜單，憑藉其安全的雲端協作平台*

[香港] -- 2015年 11 月 24 日 -- 擎威 Ribose 成為首家獲得獨家
http://www.redherring.com/events/red-herring-global/[Red Herring 2015
Top 100 Global] 獎項的安全雲端協作公司，加入了全球科技新星的知名榜單。Ribose 的平台將協作技術民主化——過去僅大型企業和政府組織才能負擔得起——將世界級的安全性和技術提供給所有用戶，完全免費。

今年的 Top 100 Global 獎項競爭尤為激烈，由過去三年獲得 Top 100 亞洲、歐洲和北美獎項的公司組成。Red Herring 發起 Top 100 Global 論壇，旨在提供一個國際聚會的價值，讓企業家、金融家和企業高管能夠在私密和親密的環境中建立有意義的個人和專業關係。

Red Herring 的 Top 100 Global 是一項享有盛譽的認可，旨在表彰來自亞洲、歐洲和北美的最有前途的私人科技企業。該榜單已成為新興公司和企業家的榮譽標誌，Ribose 加入了包括 Google、Facebook、Twitter、Skype、Salesforce.com、eBay 和 YouTube 在內的知名 Top 100 Global 校友。這一全球獎項緊隨 Ribose 在 2015 年 9 月被選為 Red Herring Top 100 亞洲獎的榮譽。

每年，Red Herring 編輯團隊根據多項定量和定性因素選擇候選公司進行評估，包括財務表現、技術創新、管理質量、戰略執行以及在各自行業中的整合情況。在 2015 年 11 月 17-19 日於加利福尼亞州洛杉磯舉行的 Red Herring Global 論壇上，Ribose 向評審展示了其安全的雲端協作平台。最終，Ribose 被評為今年的獲獎者。

過去一年，Ribose 成為全球首家獲得雲端安全聯盟（CSA）三重保證的雲服務提供商，完成了 CSA 的三項嚴格保證計劃。此外，Ribose 創建了全球最廣泛的綜合管理系統，並獲得 PAS 99 標準認證，成為英國以外首家獲得 ISO 9001:2015 認證的組織，以及全球第二家獲得 ISO14001:2015 認證的組織。為確保用戶信息的安全，公司還於九月獲得 ISO/IEC 27018 雲端隱私認證。

Ribose 提供全球最嚴格的安全要求，通過倡導「最高標準」的方法來確保雲端安全和隱私。憑藉其可及性、可靠性和安全性，Ribose 平台讓用戶能夠安心專注於手頭的工作。

Alex Vieux，Red Herring 的出版人兼首席執行官表示：「能夠從過去三年獲得 Top 100 亞洲、歐洲和北美獎項的公司中選出全球百大獎的獲獎者是一項具有挑戰性的任務。經過嚴格的考慮和討論，我們從 1,200 家潛在公司中縮小到 200 家入圍者。被選中的前 100 家公司應該感到非常自豪。Ribose 憑借其在雲安全、數據隱私和管理標準方面的專注，通過其願景、動力和對創新的承諾，在一個極具競爭力的領域中脫穎而出。」

Anam Alpenia，Herring International 的董事總經理表示：「提供企業級協作技術和世界級安全性的 Ribose，完全免費地為所有用戶提供服務，已經改變了雲協作領域的範式。給予個人和團隊工具，使他們能夠超越時間和物理位置的限制無縫協作，Ribose 創建了一個真正值得被列入 Red Herring 全球百大公司的平台，從而加入了科技行業領導者和創新者的傑出名單。」

擎威 Ribose 的創辦人 Ronald Tse 補充道：「Ribose 很高興能夠在 2015 年 9 月被選為 Red Herring Top 100 亞洲獎後，獲得 Red Herring 2015 全球百大獎。我們與今年競爭的眾多成功的私人公司並列，對評審對我們使命的認可以及對我們團隊奉獻精神的認可表示衷心的感謝。」

Tse 解釋：「現今世界越來越全球化；人們變得更加互聯；創新和發明越來越多地來自跨越全球的多學科工作。通過促進團隊合作和協作，Ribose 正在賦能全球的企業家和發明家共同努力，造福未來的世代」

Tse 補充道：「我們要感謝 Alex 和 Red Herring 團隊，感謝他們的遠見卓識，識別出世界上最有前途的新興科技先鋒。這個獎項對我們 Ribose 團隊來說是一個巨大的榮譽和鼓舞，激勵我們繼續推進我們的使命，為所有用戶帶來世界級、高度安全的協作技術。」
