---
layout: post
title: "擎威 Ribose 獲得 2015 年度 Technology Innovator Awards 最佳雲端協作平台"
date: 2015-09-07 16:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  擎威 Ribose 獲得 2015 年度 Technology Innovator Awards 最佳雲端協作平台
---
= 擎威 Ribose 獲得 2015 年度 Technology Innovator Awards 最佳雲端協作平台

香港 -- 2015 年 9 月 8 日 -- 擎威 Ribose 獲得 2015 年度 Technology Innovator Awards 最佳雲端協作平台，由 Corporate Vision Magazine 主辦。

Ribose 與其他獲獎者包括 AIG、Level 3 Communications 和 Standard Life 一同接受了該獎項，表彰其雲端協作平台，該平台將以往僅大型企業和政府機構才能負擔的協作技術，通過提供世界級的安全性和技術，讓所有用戶都能使用。

2015 年 9 月 3 日公布的 2015 Technology Innovator Awards 為表彰那些在技術創新方面表現卓越的公司、組織和個人而設立。這些獎項旨在表彰那些通過其承諾、經驗和願意探索和利用所提供的機會，正在開發和分享將繼續增強並從根本上改變商業世界的技術的個人、部門和公司。獲獎者由 Corporate Vision Magazine 的尊敬行業合作夥伴網絡收集的投票和由專業行業內部人士和企業專家進行的嚴格內部研究相結合決定。

擎威 Ribose 受到 Fortune 和 TechTarget 的關注，吸引了科技和商業界的注意。Ribose 平台可隨時隨地訪問，提供企業級服務可靠性，並符合國際治理標準，讓用戶安心專注於手頭的任務。Ribose 通過滿足全球最嚴格的指定要求，為所有用戶提供高水平的安全性，倡導對雲安全的「最高標準」方法。

除了獲得 Technology Innovator Award，Ribose 還在 2015 年國際商業獎中獲得兩項金 Stevie® 獎，分別被評為 _亞洲最具創新公司_ 和 _最佳新協作服務_。

擎威 Ribose 創辦人 Ronald Tse 表示，「Ribose 非常高興能夠收到對我們產品和使命的正面肯定。這個獎項真正證明了我們團隊的奉獻精神和辛勤工作。我還必須感謝所有提名和投票給 Ribose 的人——我們對這一對我們世界級協作平台的認可感到榮幸，這使得合作變得簡單而有趣。」

「用戶經常依賴我們的平台來創造涉及重要知識產權或高度機密信息的高價值、關鍵任務結果。考慮到這一點，我們需要了解用戶的現實需求——他們可能不會表達甚至意識到的需求。Ribose 的世界級安全性源於這一理念，這是我們用戶真正欣賞的承諾，」Tse 解釋道。

Laura Hunter，Technology Innovator Awards的協調員表示，「
科技不斷改進和轉變商業世界和我們的日常生活是毋庸置疑的。Ribose 已經證明了其創新的協作平台在行業中填補了獨特的需求——它的持續發展為高度安全、易於使用的協作軟件的未來鋪平了道路。」

如需了解更多有關 2015 年 Technology Innovator Awards 的信息，請查看獲獎者名單並了解他們成功背後的故事，請訪問
http://www.corp-vis.com/[corp-vis.com]。
