---
layout: post
title: "擎威 Ribose 獲得 2015 年度國際商業獎最佳新協作服務和亞洲、澳大利亞及新西蘭最具創新公司"
date: 2015-08-12 16:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  擎威 Ribose 獲得 2015 年度國際商業獎最佳新協作服務和亞洲、澳大利亞及新西蘭最具創新公司
---
= 擎威 Ribose 獲得 2015 年度國際商業獎最佳新協作服務和亞洲、澳大利亞及新西蘭最具創新公司

*公司在世界頂級商業獎項中獲得兩項金 Stevie® 獎*

香港 -- 2015 年 8 月 13 日 -- 擎威 Ribose 獲得 2015 年度國際商業獎最佳新協作服務和亞洲、澳大利亞及新西蘭最具創新公司兩項金 Stevie® 獎。

國際商業獎是世界頂級的商業獎項計劃。全球所有個人和組織——公共和私人、營利和非營利、大型和小型——均有資格提交提名。2015 年度國際商業獎收到了來自 60 多個國家和地區的參賽作品。今年，共有來自各行各業、各種規模的組織提交了超過 3,700 份提名，涵蓋了廣泛的類別。

Ribose 雲端協作平台將以往僅大型企業和政府機構才能負擔的協作技術，通過提供世界級的安全性和技術，讓所有用戶都能使用。Ribose 吸引了科技和商業界的注意，並被 Fortune 和 TechTarget 報導。

無論身在何處，Ribose 平台都能提供企業級的服務可靠性，並符合國際治理標準，讓用戶安心專注於手頭的任務。Ribose 採用「最高標準」的雲安全方法，通過滿足全球最嚴格的指定要求，為所有用戶提供更高水平的安全性。

擎威 Ribose 創辦人 Ronald Tse 表示，「Ribose 非常高興能夠在今年的國際商業獎中，不僅獲得一項，而是兩項金 Stevie® 獎，分別是 _年度最佳新產品或服務_ 和 _亞洲、澳大利亞及新西蘭年度最具創新公司_。這些獎項證明了我們提供世界級協作能力的使命，使合作變得簡單而有趣，同時以最高、國際認證的安全標準保護用戶的數據。」

他繼續說道，「我們要感謝主辦單位籌辦今年的獎項，並對專家評審對我們工作的認可感到謙卑——尤其是考慮到來自全球的令人印象深刻的提名名單。代表我們在 Ribose 的團隊，我們祝賀今年所有的獲獎者和提名者。能夠與如此傑出的公司同列，對我們來說是一種榮譽。」

Stevie Award 得主是由來自全球的 200 多位高管在 5 月至 8 月初參與評審過程中給出的平均分數決定的。

IBA 評審讚揚 Ribose 平台在民主化安全協作方面的表現，提供了一個 "`技術上強大的產品`"，並配備了
前所未有的靈活性，使 「開放平台」 能夠在 「專業工作和娛樂」 環境中使用，通過 "非常易於使用且具有吸引力的界面設計" -- 作為將 Ribose 平台命名為軟體協作/社交網路解決方案類別年度最佳新產品或服務的獲勝因素。Ribose 的安全重點被一位評審總結為：「大多數現有的雲端協作軟體根本無法提供必要的安全級別來保護關鍵任務、商業敏感的項目。」

在將 Ribose 命名為亞洲、澳大利亞及新西蘭年度最具創新公司時，IBA 評審讚揚該公司 「極大的承諾和出色的團隊，將技術應用於公司和社區的利益，」 「專業的管理」 和 「卓越的表現」，以及其 「在獲得多項認證方面的令人印象深刻的成就」，為用戶提供 「企業級協作平台的所有好處，而無需承擔相關的基礎設施和成本。」

Michael Gallagher, Stevie Awards 的創始人兼主席表示，「我們祝賀 Ribose 在 12 屆年度國際商業獎中獲得兩項金 Stevie® 獎。今年，Stevie Awards 收到了來自全球的超過 3,700 份提名，讚揚了全球各地的成功和成就故事。在所有這些世界級的提名中，我們的評審選擇 Ribose 獲得兩項金 Stevie® 獎，這證明了該公司的創新和卓越聲譽。」

如需了解國際商業獎的詳細資訊以及 Stevie 獎得主名單，請訪問
http://www.stevieawards.com/IBA[www.StevieAwards.com/IBA]。

