---
layout: post
title: "擎威 Ribose 獲得 Cloud Security Alliance APAC 年度安全創新獎"
date: 2016-01-20 16:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  擎威 Ribose 獲得 Cloud Security Alliance APAC 年度安全創新獎
---
= 擎威 Ribose 獲得 Cloud Security Alliance APAC 年度安全創新獎

[香港] -- 2016 年 1 月 21 日 -- 擎威 Ribose 獲得 Cloud Security Alliance (CSA) 年度安全創新獎，該組織是雲端安全行業的頂尖機構。

Ribose 在 2015 年 12 月 3 日於中國廣州舉行的 CSA 亞太區首屆頒獎典禮上獲得該獎項，經評審委員會對專業性、卓越性、創新性和可衡量的成功進行仔細評估後，該獎項旨在表彰技術行業中的佼佼者，獎勵在雲端領域中具有創新性和卓越表現的組織。Ribose 與 Trend Micro 和 DBApp Security 一同被評為年度安全創新獎，表彰其在雲端安全方面的真正創新方法。

Ribose 積極參與 CSA 的雲端安全事務，其創辦人 Ronald Tse 是 CSA 國際標準化委員會的成員，該委員會與多個合作夥伴（包括創建 ISO/IEC 27001 國際標準的信息安全管理系統的 ISO/IEC JTC1 SC27）一起制定與雲端安全相關的國際標準。自 2013 年加入 CSA 以來，Ribose 已參與多個 CSA 研究計劃，以促進和開發改進的雲端安全實踐，惠及用戶和提供商。

由於這些努力，Ribose 擁有眾多雲端安全的「第一」成就，並積極參與多司法管轄區的雲端安全計劃，認為這些實踐應成為行業標準，因為雲端安全提供商（CSP）必須確保用戶數據在地緣政治和監管邊界上的安全。

擎威 Ribose 作為雲端安全的先驅，是首家採用並推廣 CSA 的 CCM 3 控制框架的 CSP，也是全球首家同時獲得 CSA 三項雲端安全評估計劃認證的 CSP：STAR 認證（最高金級成熟度）、STAR 認證聲明和 C-STAR 評估。Ribose 也是全球首家使用 CCM 3.0 和 CCM 3.0.1 獲得 CSA STAR 認證和 STAR 認證聲明的組織；同時也是首家獲得 STAR 認證和 C-STAR 評估的軟體即服務（SaaS）提供商。

雲安全聯盟首席執行官兼聯合創辦人 Jim Reavis 表示：「我們最初邀請 Ribose 加入 CSA，是因為看到他們致力於為用戶提供最佳的安全保護。作為雲端安全的先驅，Ribose 在追求用戶安全保障方面引領行業，並成為全球首家同時獲得 CSA 三項雲端安全評估計劃認證的組織：STAR 認證、STAR 認證聲明和 C-STAR 評估。在評選 Ribose 為年度安全創新獎時，我們認可其為用戶提供最高水平安全保護的奉獻精神，以及通過與 CSA 的合作惠及整個雲端安全行業的承諾。」


雲安全聯盟亞太區總經理兼國際標準化委員會秘書長 Aloysius Cheang 表示：「Ribose 作為亞洲 CSP 的領先典範，在用戶安全和隱私方面樹立了最佳實踐。亞洲正迅速崛起為科技創新的下一個中心，像 Ribose 這樣獲得認證的世界級組織正在引領潮流。通過廣泛使用 CCM 並協助其開發，Ribose 開創了一種高標準的雲端安全方法——採用一個簡化的流程，為所有用戶提供強大的保護。」

擎威 Ribose 創辦人 Ronald Tse 解釋道：「獲得這一認可對 Ribose 來說是一個極高的榮譽，因為我們與許多行業機構（如 CSA——雲端安全的權威機構）密切合作。我們很高興獲得這一榮譽，這是對我們對雲端安全的深厚承諾以及我們的方法和實施效果的外部證明。」

Tse 解釋道：「CSA作為雲端安全行業的標準機構，他們的研究對雲端安全行業以及當今全球使用的幾乎所有雲端安全標準產生了強烈影響。作為 CSA 的企業會員和雲端安全的領導者，我們強烈支持 CSA 的工作，並幫助他們制定和推動行業標準，從而提高全球雲端提供商和用戶的信心。」

「作為一個協作平台，Ribose 依賴最高水平的雲端安全來保護我們用戶的知識產權。知道他們的工作受到獲獎、國際認證的安全水平保護，讓我們的用戶能夠安心地專注於手頭的任務，」Tse 總結道。
