---
layout: post
title: "擎威 Ribose 獲得雲端產業首個安全數位交易 Kitemark 認證"
date: 2016-09-25 00:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  擎威 Ribose 獲得雲端產業首個安全數位交易 Kitemark 認證
---
= 擎威 Ribose 獲得雲端產業首個安全數位交易 Kitemark 認證

*全球首個通過 BSI 嚴格應用安全認證的協作平台*

[香港] -- 擎威 Ribose 成為全球首個獲得 BSI 享有盛譽且高度嚴格的
http://www.bsigroup.com/en-GB/kitemark/services/secure-digital-transactions/[安全數位交易 Kitemark] 的雲端軟體即服務平台，該認證確保應用程式具備適當的安全控制措施，以通過嚴格的安全測試處理高度敏感的線上資訊。

機密的財務和個人資訊越來越多地被儲存和共享，但服務本身始終面臨持續的威脅和攻擊。根據 PwC 的資料，90% 的大型組織已經遭受過資料外洩，因此組織必須通過適當的安全措施來保護其在雲端中的機密資訊。

保護協作數據尤為重要，因為這些數據通常包含組織中最有價值但也最脆弱的資產——知識產權、商業機密或關於客戶和員工的個人資訊、患者健康資訊以及財務資訊。

英國標準協會 BSI 的
http://www.bsigroup.com/en-GB/kitemark/services/secure-digital-transactions/[Kitemark for Secure Digital Transactions]
是迄今為止最嚴格的安全測試計劃，用於驗證和評估個別應用程式的安全性。最初由銀行業試點，該計劃是
http://www.bsigroup.com/en-GB/kitemark/[BSI Kitemark] 家族的最新成員，該家族象徵著信任和產品質量，自 1903 年首次授予以來，已在全球廣受認可。

BSI 也長期以來一直是資訊安全的先驅，作為國際資訊安全管理系統標準的創始者，
http://www.iso.org/iso/iso27001[ISO/IEC 27001] 的制定者。

達到此 Kitemark 認證的應用程式展示了對銀行級安全的嚴格驗證，以及開發和運營該應用程式的組織的數據保護措施，確認其已經過徹底測試並符合公認的安全、可靠性和質量標準。

為取得安全數位交易認證標誌，
該應用程式或服務必須達成三項關鍵標準。首先，安全服務必須在強調組織安全與流程完整性的安全環境中開發與運作。此標準的最佳驗證方式，是要求組織本身取得並維持ISO/IEC 27001認證，涵蓋服務相關所有環節及所處理的敏感資訊，包括應用程式開發、基礎設施運作與交易處理。

安全數位交易認證標章的第二項原則是驗證應用程式安全性，要求服務須通過最高等級的嚴格內部與外部滲透測試，確保不存在已知重大漏洞或安全缺陷。應用程式安全測試由具備逾30,000小時滲透測試經驗、經http://www.crest-approved.org/（CREST）認證的世界級安全團隊執行，遵循https://www.owasp.org/（OWASP）ASVS v2.0標準——此為業界最嚴苛的測試規範。在第二級驗證中，Ribose 需通過涵蓋應用程式安全各層面的 147 項安全控管測試，透過黑盒與白盒測試方式，從商業邏輯至加密技術、靜態分析至 OWASP 十大漏洞皆全面檢驗。此機制確保 Ribose 平台能為重大交易提供安全保障，包括處理醫療資訊、執行關鍵業務或敏感功能，以及處理其他敏感資產等情境。

第三項準則是持續的獨立監控與評估，以確保服務的安全性配置能為其處理的數據類型提供保障，包括持續性應用程式安全測試、組織安全稽核，以及Kitemark合規稽核與風險評估。

英國標準協會認證總監克里斯·路易斯指出：「隨著行動與雲端運算的普及，資訊安全正日益成為關鍵的競爭優勢。許多組織雖已建立完善資訊安全流程，但欲取得BSI安全數位交易Kitemark認證，其系統必須定期接受獨立嚴格的滲透測試與監控。Ribose成為雲端產業首家獲此認證的企業，彰顯其對保障用戶私密資訊安全的堅定承諾。」

BSI亞太區標準與專業服務副總裁暨BSI香港董事總經理Emmanuel Hervé表示：「BSI品牌與BSI Kitemark標誌被公認為信任象徵，我們在推動網路與資訊安全卓越實踐方面擁有卓越紀錄。此認證彰顯Ribose對雲端應用程式與服務持續安全的承諾。成為首個取得全新『安全數位交易認證標章』的雲端服務商，
印證了Ribose成為雲端安全先驅的承諾。」

Ribose創辦人謝永昌解釋：「本次認證標章的取得，
彰顯Ribose始終如一地致力打造安全平台，
將客戶資料保護列為首要任務。
在我們已取得的
http://www.iso.org/iso/catalogue_detail?csnumber=43757[ISO/IEC 27017]
雲端安全認證及
http://www.iso.org/iso/catalogue_detail.htm?csnumber=61498[ISO/IEC 27018]雲端隱私認證為基礎，此Kitemark認證進一步確保
我們的應用程式本身具備保護高度敏感資訊的完善防護機制。"

"Ribose採用最高標準的雲端安全策略，讓使用者能安心
在關鍵任務專案中自由協作，確信其機密資訊受到國際雲端
安全標準及BSI Kitemark的雙重保障。所有這些認證皆是對Ribose平台安全性的有力證明。」

儘管任何認證皆無法保證百分之百安全，但BSI安全數位交易Kitemark標章能確保網站或應用程式已針對其處理的資訊實施適當的安全管控措施。
