---
layout: post
title: "擎威 Ribose 獲得 ISO/IEC 27017 雲端安全認證"
date: 2016-06-08 16:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  擎威 Ribose 獲得 ISO/IEC 27017 雲端安全認證
---
= 擎威 Ribose 獲得 ISO/IEC 27017 雲端安全認證

*_全球首個符合國際雲端安全標準的 SaaS 平台_*

[香港] -- 2016 年 6 月 9 日 -- 擎威 Ribose 成為全球首個
軟體即服務平台獲得 ISO/IEC 27017 認證，該標準是專為雲端服務設計的資訊安全控制國際標準。由國際標準組織 (ISO) 和國際電工委員會 (IEC) 發布，ISO/IEC 27017 是 ISO/IEC 27001（資訊安全管理系統）家族中的特定行業標準。

雲端提供了巨大的好處，允許雲端服務客戶在任何給定時間使用所需的計算資源。
然而，由於雲端環境的開放性——提供廣泛的網路存取、快速彈性、自助配置功能和資源池化——雲端資訊安全需求與 ISO/IEC 27001 最初設計保護的傳統環境有很大不同。

針對雲端安全的特定需求，ISO/IEC 27017 在 ISO/IEC 27001 的基礎上進一步提供了額外的控制措施和實施指南，涵蓋架構、技術和流程，以確保雲端中的資訊安全得到充分保護。考慮到許多雲端服務提供商通常也是其他雲端服務的客戶，ISO/IEC 27017 還為雲端服務客戶和雲端服務提供商提供了實施指南，強調每個實體在雲端安全中的角色。

ISO/IEC JTC1 SC27委員會負責制定與管理ISO/IEC 27001系列標準，該委員會於2011年10月首度批准日本提出的雲端安全管理標準提案。歷經五年專注研發，ISO/IEC 27017標準最終於2015年12月正式發布，為雲端服務資訊安全管理提供實務規範。日本ISO/IEC JTC1 SC27代表、ISO/IEC 27017原始起草人暨提案者之一——JASA秘書長長 Tadashi Nagamiya
評論道：「Ribose取得此認證，彰顯其在雲端環境中保護用戶資訊的承諾與努力。」

作為首家同時取得CSA CCM 3合規認證、CSA STAR認證及新加坡MTCS認證的雲端服務供應商，Ribose憑藉現有系統與流程即能滿足ISO/IEC 27017規範要求。

BSI亞太區標準與專業服務副總裁暨BSI香港董事總經理Emmanuel Hervé強調： 「我們讚揚Ribose致力以最高標準保護用戶資訊。作為ISO/IEC資訊安全管理體系標準的創始機構，以及首家為ISO/IEC 27001行業特定標準提供完善認證計劃的認證機構，BSI在ISO/IEC JTC 1 SC 27開發ISO/IEC 27017認證計劃期間，與Ribose及ISO/IEC JTC 1 SC 27專家緊密合作，確保我們的嚴謹認證計劃能精準評估標準遵循度。」
SC 27專家團隊共同制定ISO/IEC 27017認證方案，確保嚴謹的認證程序能精準評估標準遵循度。」

擎威 Ribose創辦人Ronald Tse 闡述：「ISO/IEC 27017認證明確彰顯Ribose對雲端安全的堅定承諾。
我們自豪成為全球首家同時取得CSA STAR認證、STAR認證聲明、C-STAR評估及ISO/IEC 27017認證的雲端服務供應商。儘管存在部分規範重疊，ISO/IEC 27017已證實能完善補充我們現有的區域性與全球性雲端安全要求。」

謝先生續稱：「Ribose始終以雲端安全先驅的嚴謹形象著稱。本次ISO/IEC 27017認證證實我們不僅透過自身平台實施完善管控措施，更藉由合作供應商網絡為客戶數據提供全面保障。」

謝總結道：「透過採用最高標準的雲端安全策略，Ribose讓使用者能安心在平台上自由創作與協作——確信其機密資訊受到多重國際認證的最高等級雲端安全防護。」
