---
layout: post
title: "擎威 Ribose 在 2016 年國際商業獎中被評為最佳新協作服務、最佳新社交商業解決方案和最佳社交協作應用"
date: 2016-09-28 00:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  擎威 Ribose 在 2016 年國際商業獎中被評為最佳新協作服務、最佳新社交商業解決方案和最佳社交協作應用
---
= 擎威 Ribose 在 2016 年國際商業獎中被評為最佳新協作服務、最佳新社交商業解決方案和最佳社交協作應用

*公司在世界頂級商業獎項中獲得三項金 Stevie(R) 獎*

[香港] -- 2016 年 9 月 28 日 -- 擎威 Ribose 在第 13 屆國際商業獎中獲得三項金 Stevie(R) 獎，分別是「年度最佳新產品或服務 - 軟體協作/社交網路解決方案」、「年度最佳新產品或服務 - 軟體社交商業解決方案」和「最佳社交移動應用」，此外還獲得「年度最佳新產品或服務 - 軟體安全解決方案」的銅 Stevie(R) 獎。

http://stevieawards.com/iba[國際商業獎]，或稱「Stevies」，是全球頂級的商業獎項，旨在表彰全球最受尊敬的個人和商業組織。2016 年的國際商業獎吸引了來自 60 多個國家和地區的 3,800 多個提名，涵蓋了幾乎所有行業的公共和私人、盈利和非盈利、小型和大型組織。

擎威 Ribose 提供了一個獨特且安全的雲端協作平台，幫助用戶有效地協作，同時通過先進的雲
端安全和隱私保護技術保護其高價值的協作數據，並通過直觀的用戶體驗提供服務，符合現
今消費者軟體的期望。該平台採用全球最嚴格的指定安全要求，倡導「最高標準」的雲端安
全和隱私保護方法。 平台的可訪問性、可靠性和安全性為用戶提供了安心，讓他們能夠專注於手頭的任務。

擎威 Ribose 創辦人 Ronald Tse 評論道：「Ribose 很高興在第 13 屆國際商業獎中比去年取得更好的成績——在競爭激烈的最佳新協作服務、最佳新社交商業服務和最佳社交移動應用類別中獲得
http://stevieawards.com/iba/2016-stevie-award-winners[三項金 Stevie(R) 獎]。
我們也很高興在競爭激烈的最佳新安全解決方案類別中獲得銅 Stevie(R) 獎。這些獎項證明了我們以「最高標準」的方法民主化安全協作的使命與我們的用戶和評委產生了共鳴，幫助我們讓協作變得簡單有趣，同時以最高、國際認證的安全水平保護用戶的數據。」

他繼續說道：「我們對評審團對我們工作的認可感到既謙卑又榮幸，並且我想祝賀今年所有的 IBA 獲獎者和提名者，感謝他們分享來自世界各地的經驗和成功故事。對於我們 Ribose 團隊來說，能夠在國際商業領域的一些領先名稱中被認可，始終是一個自豪的來源。」

http://stevieawards.com/iba/2016-stevie-award-winners[Stevie 獲獎者]
是由來自全球 200 多位高管的平均分數決定的，他們從五月到八月初參與了評審過程。

在頒發最佳社交協作應用的金 Stevie 獎時，評審們讚揚 Ribose「在社交的同時高度保護雲端平台」以及「實用且強大的技術應用，以促進更大的全球化和數字化」。

選擇 Ribose 獲得最佳協作/社交網路解決方案類別金 Stevie 獎的評審稱其為「客戶參與和業務運營參與的絕佳範例」，並表示「絕對是一家值得關注的公司」，讚揚 Ribose 提供了「在安全協作方面的新穎角度」。在評分最佳社交商業解決方案的提交時，評審團強調
Ribose 的「世界級雲端平台」和「卓越的安全功能」，並以「眾多國際獎項和認證」作為支持。

IBA 評審還授予 Ribose 銅 Stevie 獎，表彰其為年度最佳新產品或服務 - 軟體 - 安全解決方案，評語為：「Ribose 使客戶能夠將全部精力投入到業務發展中，同時將安全交給他們可靠的手中。它是真正的多行業推動者。」

Stevie 獎主席兼創始人 Michael Gallagher 評論道：「我們很高興祝賀 Ribose 在第 13 屆國際商業獎中獲得三項金 Stevie 獎和一項銅 Stevie 獎。繼去年取得的非凡成功後，Ribose 繼續展示其在安全雲計算方面的熱情和卓越承諾——今年共獲得四項 Stevie 獎」

如欲了解更多有關國際商業獎及 Stevie 獎得主的資訊，請訪問
http://www.stevieawards.com/IBA[www.StevieAwards.com/IBA]。
