---
layout: post
title: "擎威 Ribose 在2018年國際商業大獎中榮獲六項金、銀、銅 Stevie® 獎"
date: 2018-08-22 11:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  擎威 Ribose 在2018年國際商業大獎中榮獲六項金、銀、銅 Stevie® 獎
---
= 擎威 Ribose 在2018年國際商業大獎中榮獲六項金、銀、銅 Stevie® 獎

*因廣泛的非對稱安全解決方案和 Metanorma 出版技術而獲得認可*

{blank}[2018 年 8 月 22 日 -- 香港]

http://www.ribose.com[擎威 Ribose] 於第15屆國際商業大獎中榮獲四項金 Stevie 獎，分別是
「最佳新語義技術平台、工具和應用」、
「最佳新國際數據保護解決方案」、
「最佳新協作/社交網絡解決方案」 和 「最佳新學術出版信息解決方案」，此外還獲得
一項銀 Stevie 獎，「年度最具創新技術公司 - 員工人數不超過100人」，以及一項銅 Stevie 獎，「年度技術創新 - 員工人數不超過100人」。

// [quote]
// Ribose wins Six Stevie Awards at 2018 International Business Awards
// for cutting-edge asymmetric security and technical publishing innovations

國際商業大獎是全球頂尖的商業獎項計畫，開放全球所有個人與組織參與提名。2018年國際商業大獎共收到逾3,900件參賽作品，來自74個國家，涵蓋各規模組織及幾乎所有產業領域。

擎威 Ribose 提供非對稱安全解決方案和技術，專注於提升高安全敏感環境的生產力。其在網路安全方面的專業知識獲得了多項成就的認可，包括為關注數據主權的組織提供獨一無二的地理定位服務，以及具有增強橢圓曲線加密功能的擴展「零知識協作」技術。

其他擎威 Ribose 的創新包括「`Engyon`」安全文件方案，該方案允許數據元素被單獨加密和數位簽名，同時支持分層安全級別。結果是一個獨立的「`區塊鏈文件`」安全文件，可以通過傳統渠道如電子郵件傳輸。

擎威 Ribose 也因構思和開發「Metanorma」而獲得認可——這是一個用於國際標準化組織如 CalConnect 和 ISO 的標準文件標準，以實現端到端的作者到印刷工作流程。

擎威 Ribose 創辦人 Ronald Tse 表示：「擎威 Ribose 很高興在第15屆國際商業大獎中獲得如此高的認可，贏得四項金 Stevie 獎，包括「年度最佳新產品或服務」，以及一項銀 Stevie 獎「年度最具創新技術公司」和一項銅 Stevie 獎「年度技術創新」。在這些競爭激烈的類別中獲獎，是對我們在非對稱安全解決方案和標準推進方面承諾的有力證明。」

他繼續說：「我想祝賀所有2018年IBA的獲獎者和提名者，感謝他們分享來自世界各地的成功故事。今年的競爭是歷年來最激烈的，能在這麼多傑出的商業和技術領袖中脫穎而出，我們感到非常自豪。」
擎威 Ribose 團隊一直以來都以能在國際商業領域的領先企業中獲得認可為榮；我們對今年的結果既感到謙卑，也感到榮幸。

Stevie 獎的獲獎者是由全球超過270位高管在12個評審團中參與評分後決定的。

評審們讚揚擎威 Ribose 創造了一個「可擴展、以社會為中心、高度生產力且值得信賴的產品，並由高度合格且受認可的組織認證其頂級安全性。」他們還指出，「Ribose 的安全解決方案在當今的網路安全環境中具有重要意義，並且在保護敏感數據方面提供了強大的功能。」

評審們讚揚 Engyon 使用類區塊鏈技術來創建安全、可共享的文件——一位評審評論道：「使用區塊鏈來保障協作是非常聰明的！」另一位評審則表示：「獨立但安全的文件可以通過傳統渠道如電子郵件傳輸，這個想法非常出色。」

評審們也讚揚擎威 Ribose 開發的 Metanorma，稱其為「革命性的概念」，並指出，「為標準化設定標準是一個非常重要的需求。這是一個偉大的倡議。」另一位評審則表示，「對於任何需要管理這些標準的人來說，這個 [Metanorma] 將如同天賜之物。」

Michael Gallagher, Stevie Awards 的創辦人兼主席表示：「今年的 Stevie 獎得主是我們迄今為止最傑出的一群獲獎者。Ribose 應該特別為他們在今年的國際商業大獎中的成就感到自豪，因為我們提高了2018年IBA的最低評分要求，以應對越來越多令人印象深刻的全球提名。今年帶回六個 Stevie 獎是 Ribose 在網路安全和國際標準方面處於領先地位的有力證明。」

欲了解國際商業大獎的詳細信息和獲獎者名單，請訪問 www.StevieAwards.com/IBA[www.StevieAwards.com/IBA]。