---
layout: post
title: "擎威 Ribose 獲得 2019 年國際商業獎兩金一銀 Stevie® 獎"
date: 2019-09-23 11:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  擎威 Ribose 獲得 2019 年國際商業獎兩金一銀 Stevie® 獎
---
= 擎威 Ribose 獲得 2019 年國際商業獎兩金一銀 Stevie® 獎

*因在安全解決方案、Metanorma 出版技術及標準創新方面的表現而獲得認可*

{blank}[2019 年 9 月 23 日 - 香港]

http://www.ribose.com[擎威 Ribose]
於2019 年 https://stevieawards.com/iba[第16屆國際商業獎（International Business Awards®）] 中獲得兩項金 Stevie® 獎，分別為「國際數據保護解決方案」和「語義技術平台、工具和應用」，以及一項銀 Stevie® 獎，為「年度最具創新科技公司 - 員工人數少於 100 人」。

Maggie Gallagher，Stevie® 獎總裁表示：
"Ribose 公司應為其在本屆國際商業大獎中的成就倍感自豪，這充分彰顯了該公司在網路安全領域的領導地位，以及在國際標準制定方面同樣令人矚目的創新成果。
國際商業大獎是全球頂尖的商業獎項計畫，開放全球所有個人與組織參與提名。
2019年國際商業大獎共收到逾4,000件參賽作品，來自74個國家，涵蓋各規模組織及幾乎所有產業領域。2019年國際商業大獎共收到來自74個國家逾4,000件參賽作品，涵蓋各規模組織及幾乎所有產業領域。」

Ribose提供非對稱安全解決方案與技術，專注於提升高安全敏感環境的生產力。秉持網路安全核心理念，Ribose是全球唯一同時通過CSA三重認證、並經英國政府通訊安全局（CESG）安全測試的雲端服務供應商（CSP）。其平台不僅取得NIST CFS第4級、MTCS第3級及ISO/IEC 27017認證，更榮獲英國標準協會（BSI）
安全數位交易認證標章。其獨特的數據地理定位服務（通過ISO/IEC 27018認證）滿足企業對數據主權的訴求，同時透過橢圓曲線加密技術實現端到端加密協作，全面保障數據隱私。

Ribose在推動國際標準創新方面的貢獻亦獲業界認可。2018年，Ribose獲任命為ISO大地測量註冊機構官方註冊機構，實現不同GNSS系統間的座標轉換。今年更推出ISO/TC 211官方多語種術語資料庫「 https://www.geolexica.org[Geolexica]」，提供14種語言的地理資訊術語。
種語言。

評審團高度讚揚Ribose對全球最重要標準之一的貢獻——ISO 8601-1與ISO 8601-2（日期與時間表示的國際標準），此標準現今應用於所有運算裝置。評審團同時肯定該機構在制定物理與郵政地址標準（ISO 19160-6）、轉寫系統代碼（ISO 24229）、日期時間概念（ISO 34000）及曆法代碼（ISO 34300）等領域的領導地位。

Ribose更因構思並開發「Metanorma」標準化框架而廣受讚譽，此框架專為標準文件設計，供國際標準化機構實現端對端、從作者到印刷的完整工作流程。透過推動SMART標準（可機讀、可讀取且可轉移的標準），Metanorma已在國際標準化社群中迅速普及，獲CalConnect、開放地理空間聯盟、國際電信聯盟及雲端安全聯盟等組織採用，並獲IETF、ISO與IEC作者群廣泛應用。
可轉移標準），已在國際標準化社群中迅速普及，採用機構包括CalConnect、開放地理空間聯盟、國際電信聯盟及雲端安全聯盟，同時獲IETF、ISO與IEC的標準制定者廣泛採用。

Ribose創辦人Ronald Tse表示：「Ribose能於第十六屆國際商業大獎中榮獲如此殊榮，深感榮幸與謙卑。
同時榮獲『國際資料保護解決方案』與『語義技術平台、工具及應用』兩項史帝夫金獎，以及『年度最具創新力科技企業』銀獎，充分印證我們在安全與標準領域的尖端成就。」

他續稱：「謹代表Ribose團隊，向所有
2019年國際商業大獎得主與入圍者持續追求卓越的努力。本屆競賽無疑是歷屆最為激烈，能在如此眾多傑出的商業與科技領袖中脫穎而出，我們深感自豪。」

史提夫獎得主由全球逾250位高階主管組成的12個評審團，經綜合評分後決定。

針對Ribose榮獲金獎的「語義技術平台、工具與應用」項目，評審指出：「就商業目標而言，Metanorma確實彰顯其戰略宗旨」，並稱讚「該產品為需協作制定標準並追蹤進度的組織應用場景創造巨大價值」。另一位評審表示：「這是解決跨產業重大問題的強大方案，見證其持續創新令人欣喜。」

針對Ribose另一項金獎作品「國際資料保護解決方案」，評審稱其為「頂尖資料保護方案之一」，並指出「單一資料元素加密與數位簽章等功能令人印象深刻」。

Ribose榮獲銀獎的「年度最具創新科技企業」參賽項目同樣贏得評審團讚譽，其「卓越技術具備廣泛應用潛力與顯著時間效益」備受肯定。另一位評審盛讚該方案為「運用雲端平台保障服務安全的最佳實踐」。史提夫獎主席瑪姬·加拉格表示：「本屆得獎者的競爭激烈程度堪稱歷年之最。Ribose應為其在國際舞台上的成就深感自豪。」

史提夫獎主席瑪姬·加拉格表示：「今年史提夫獎得主的競爭激烈程度堪稱歷年之最。Ribose應為其在國際商業大獎中的成就倍感自豪，這不僅彰顯了該公司在網路安全領域的領導地位，更印證其在國際標準制定方面同樣令人矚目的創新成果。」

國際商業大獎詳情及得獎名單請參閱： https://www.StevieAwards.com/IBA[www.StevieAwards.com/IBA]。
