---
title: 隐私政策
description: Ribose Open 隐私政策
revision_date: 2023-11-15
revision_date_template: "最后修订日期：{{ revision_date | date: '%Y年%-m月%-d日' }}"
layout: page
hero_include: index-page-hero.html
---
:page-liquid:

CAUTION: 本页面为英文版本的翻译，仅供参考。如中英文版本有任何不一致之处，应以+++<a href="https://open.ribose.com/privacy/">英文版本</a>+++为准。

== 简介

. 您的隐私对 Ribose 至关重要。我们致力于保护您与我们分享的任何信息。

. 本隐私政策阐述了我们从您那里收集的或您提供给我们的任何个人信息将被我们处理的基础。

. 本隐私政策适用于所有服务，并已按照 Ribose 运营所在司法管辖区的隐私法律起草，以证明合规性。我们将根据数据保护法规处理您的个人信息。

. 本政策还描述了关于 Ribose 使用您个人信息的可用选择，以及您可以采取的访问个人信息、要求我们更正或删除它，或投诉我们处理您个人信息的任何方面的步骤。

. 注册您的账户、其使用和接受本隐私政策的条款表示您已审阅本隐私政策并同意受其约束。

. 在注册您的账户之前（或在继续使用服务之前），您需要接受本隐私政策，任何使用您账户的用户也将需要在首次访问（或在继续访问）我们通过您账户提供的服务之前明确接受本隐私政策。如果您不同意这些条款，必须立即离开我们的网站。如果您选择接受本隐私政策，我们将保留您在此方面的接受记录。

== 条款和定义

. 本文件中的「Ribose」、「我们」和「我方」统指 Ribose 集团公司，包括 Ribose Inc.（美国）、Ribose Limited（英国）和 Ribose Asia Limited（香港）。

. 「服务」是指 Ribose 提供的所有产品和服务，其中每一项被称为「服务」。

. 「您的账户」是指由您创建的服务注册账户。

. 「个人信息」是指与在世个人有关的数据，该个人可以从数据中或从数据与我们拥有或可能拥有的其他信息的结合中被识别，包括数据保护法规中描述的个人数据。

. 「数据保护法规」是指香港个人资料（私隐）条例以及与处理个人数据和隐私有关的任何其他适用法律或法规，如加州消费者隐私法、1988年和2003年数据保护法和指令95/46/EC，此类法规将不时被修订、修订或取代，包括通过通用数据保护条例（EU）2016/679（以下简称「GDPR」）（以及实施或补充GDPR的法律）的实施。

. 「用户数据」是指由您或他人通过您的账户上传的数据（可能包括个人信息），可能是您或他人在与服务相关联时提供或使用的任何信息、数据或材料，包括但不限于用户凭证、与服务相关联的用户或其他方共享的数据，和/或您在支持请求等过程中提供的任何个人信息。Ribose 是用户数据的数据处理者（如数据保护法规中所定义）。

. 「外部资源」是指非 Ribose 运营的资源。

== 我们从您那里收集的信息

我们充分尊重您与服务互动相关的隐私权，并努力在与您的交易中对我们将收集哪些信息以及我们将如何使用您的信息保持透明。

=== 您提供的信息

. Ribose 持有的大部分个人信息由您（用户）提供。我们只在法律允许的情况下收集和使用个人信息。

. 账户和个人资料信息。您需要提供个人信息才能成为服务的用户（以下简称「用户」）。我们在您注册账户、创建或修改个人资料、设置偏好、通过服务注册或购买时收集有关您的信息。注册过程要求提供全名、密码和电子邮件地址。您还可以选择在个人资料信息中添加头像照片以及其他详细信息，如生日、电话等，以在我们的服务中显示。我们会跟踪您在服务中输入的偏好。虽然您被要求向 Ribose 提供真实姓名和有效的联系方式，但您可以使用别名（「屏幕名称」）参与所有活动，如空间和对话。

. 您使用服务提供的内容。此内容包括您输入平台及其应用程序的信息，如对话、日历、联系人、空间成员资格等。您还可以选择从自己的联系人来源将特定联系人上传到 Ribose，但 Ribose 不会制作和存储整个用户通讯录的副本。您上传的任何联系人只能由您访问，除非并直到您邀请他们加入空间并且他们选择成为用户，或者如果您在空间内容中明确包含有关他们的信息（如在上传的文件或对话中）。

. 您通过我们的支持渠道提供的信息。这包括提供给服务客户支持功能的信息以及与之的互动，包括给我们支持团队的任何信息。您可能会被要求提供联系方式和其他必要信息以解决您报告的特定支持案例。

. 付款信息：我们在您注册某些付费服务时收集某些付款和账单信息。

=== 我们从服务使用中自动收集的信息

. 我们在使用服务（包括浏览我们的网站和在服务中采取某些操作）时收集有关您的信息。

. 您对服务的使用。我们会跟踪您与服务互动时的某些信息，如您使用的功能及其参数。我们还收集有关您互动的空间和用户的信息。

. Cookie。我们的 Cookie 页面描述了我们使用的 Cookie。您可以将浏览器设置为拒绝 Cookie。但是，如果禁用 Cookie，某些服务可能无法正常工作。

. 服务器日志。当您访问我们的服务时，我们的服务器会自动记录某些信息，其中可能包括您的 IP 地址、浏览器类型、浏览器语言、Web 请求、与服务的互动、请求的日期和时间、使用服务前访问的网页地址以及 Cookie 信息（见上文）。

. 客户端信息。当您通过浏览器或移动应用程序（以下简称「客户端设备」）登录我们的服务时，我们的服务会自动记录您的客户端设备发送到我们服务的信息。此信息包括客户端配置和插件、语言偏好、应用程序标识符和崩溃数据。

. 通信。我们保留您与 Ribose 之间的通信，无论您是否是服务的用户。如果您注册 Ribose 新闻通讯、网络研讨会或其他通信，或者您想总体上联系我们，我们将收集您的联系信息以满足您的请求。在为您提供客户支持的同时，我们也可能从您那里收集额外信息。

. 位置数据。某些服务可能提供额外功能，这些功能需要比您的 IP 地址提供的更详细的位置感知。只有在您选择接受这些服务并被明确通知后，才会收集详细的位置信息。

=== 我们从其他来源接收的信息

. 服务与第三方的集成。某些服务允许用户配置与第三方服务的集成，例如用于导入联系人。我们从这些集成接收的信息取决于第三方服务的参数。

. 合作伙伴。我们与提供与我们互补服务的合作伙伴合作，如转售商、集成商或基础设施提供商，他们向我们提供有关您对服务的兴趣和使用以及其他信息和联系方式的信息，以维持您对服务的使用。

. 对服务的外部访问。某些服务在其他第三方网站上或通过其他第三方网站提供。提供给这些网站的个人信息可能会发送给 Ribose 以便向您提供服务。此类信息在 Ribose 持有时受本隐私政策保护。

. 第三方。营销和广告公司可能会向我们提供有关您对服务兴趣的信息。

== 我们如何使用收集的信息

. Ribose 使用其持有的个人信息来提供和改进服务，并保护 Ribose 和 Ribose 用户的权利和财产。

. 提供服务并个性化您的体验。我们使用您的个人信息向您提供服务，如用于身份验证、提供支持和处理必要的交易。服务可能包括个性化功能，例如上传头像照片的能力，在包含协作功能的服务中，有必要通过个人姓名识别用户。

. 与您通信。我们使用您的个人信息向您发送有关您使用服务的消息，如活动通知和客户支持，以及服务本身的任何更新。在大多数情况下，这些通信可以通过您账户中的设置区域进行定制。

. Ribose 持有的个人信息仅根据用户做出的选择使用和披露；例如，加入协作空间并参与对话。每个空间的隐私设置由其所有者/管理员设置；加入空间的用户会被通知这些设置，并通过加入接受它们。

. 服务器日志。我们使用此信息来管理服务，了解访问者如何浏览服务，并增强您使用服务的体验。

. 通信。Ribose 使用此信息以回应您的查询并改进我们的服务。

. Cookie。Ribose 使用 Cookie 来提高服务质量，包括促进登录和注册过程、个性化您的体验、分析和跟踪用户趋势、衡量广告和促销效果。

. IP 地址。我们使用您的 IP 地址和/或国家偏好来近似确定您的位置，以便为您提供更好的服务体验。

. 位置信息。我们可能将此信息与从您的 IP 地址派生的信息（例如区域位置）结合使用，以改善您的用户体验（例如使用特定语言或显示天气）。

=== 您的信息如何被共享

. Ribose 不会在未经您同意或除非法律要求的情况下共享您的数据（本隐私政策中规定的除外）。Ribose 仅在以下情况下向第三方（即非用户）披露个人信息。

. 与服务用户促进协作。您可以使用服务的功能与其他用户共享内容，他们随后能够看到您的某些个人信息（如您的姓名）以识别该内容的来源。

. 与组织账户管理员进行管理。如果您对服务的访问是由组织账户授予的，您的账户信息和使用情况将可由组织账户所有者以及所有者授权的人员访问。

. 在 Ribose 集团内部。当第三方是 Ribose 集团的一部分并且该信息是提供服务所需时。对您个人信息的访问仅限于需要代表 Ribose 处理它的 Ribose 员工、承包商和代理人，并受保密要求约束。

. 与签约方促进提供服务。Ribose 签约的服务提供商帮助执行付款处理和其他必要服务，以便我们向您提供服务，对此访问或使用您的个人信息是必要的。签约方必须按照本隐私政策合规处理此类信息。

. 与第三方。只有在您提供明确同意与特定第三方共享此类信息的情况下，我们才会与外部方共享信息。

. 与您对第三方服务的集成。您的账户可能已配置为与某些第三方服务集成，因此可能允许这些第三方访问您的账户和其中的信息。我们敦促用户查看这些第三方服务的隐私政策，因为他们对个人信息的处理和程序不受我们控制，因为本隐私政策不涵盖第三方如何使用您的信息。

. 获得明确同意。在某些情况下，您可能提供明确同意允许我们显示某些个人信息，如在发布的成功案例中放置您的姓名。

. 确保安全。如果我们善意地认为披露对您或任何其他人的健康或安全是必要的。

. 遵守法律。如果 Ribose 被法律要求披露信息，例如遵守传票（或类似的法律程序）或可执行的政府请求。Ribose 将在收到具有法律约束力的个人信息披露请求时通知您，除非法律禁止。

. 保护我们的权利。如果我们善意地认为披露对保护我们的权利、执行我们的条款、检测、预防或以其他方式处理欺诈、安全或技术问题是必要的。此类信息将按照适用的法律和法规披露。

. 业务转让。如果任何服务涉及合并、收购或任何形式的出售其部分或全部资产，我们将在您的数据受不同隐私政策约束之前提供通知。

== 儿童使用服务

. Ribose 仅向组织和 13 岁以上的个人提供服务，并不将任何服务定向于年幼儿童。作为用户加入的个人需要确认他们年满 13 岁或以上。

. 如果我们意识到 13 岁以下儿童向我们提供了个人信息，我们将采取措施删除此类信息。如果您意识到儿童向我们提供了个人信息，请联系我们。

== 我们如何存储和保护信息

=== 我们如何保护信息

. Ribose 非常重视个人信息的保护安全。我们采取适当的安全措施，防止未经授权访问、或未经授权更改、披露或销毁您的个人信息。有关我们遵守的安全方案和防止未经授权访问和披露的具体安全措施的详情在我们的网站上提供。

=== 我们保留信息多长时间

. 个人信息。Ribose 在提供您的账户使用的服务所需的时间内以及适当的备份和归档目的保留个人信息。如果用户被删除，仅与用户相关的个人信息将立即删除，但备份除外，备份将在之后的合理时间内保留，以防您决定重新激活服务。

. 共享信息。此信息将由包含它的空间的所有者或拥有该空间的组织账户控制。Ribose 在向这些空间和/或组织账户提供服务所需的时间内保留此信息。

. 其他义务。我们还根据需要保留您的某些信息以遵守我们的法律义务、解决争议、执行我们的协议、支持业务运营以及继续开发和改进我们的服务。在我们为改进和开发服务保留信息的情况下，我们采取措施对此类信息进行匿名化处理，并且仅使用此类信息发现有关我们服务使用的集体见解，而不是具体分析有关您的个人特征。

. 营销信息。如果您选择接收我们的营销电子邮件，我们将在您最后一次表达对我们服务兴趣（例如您最后一次打开我们的电子邮件或停止使用服务）之日起的合理时间内保留有关您营销偏好的信息。我们将在创建此类信息之日起的合理时间内保留从 Cookie 和其他跟踪数据派生的信息。

== 个人信息的国际传输

. Ribose 持有的个人信息在位于美国的服务器上处理。

. 使用服务的交易和通信将涉及信息至少暂时保存在参与用户所在的司法管辖区。

. 某些服务允许用户明确选择服务的数据处理和存储发生的司法管辖区，包括美国和香港，在这种情况下，相关的必要个人信息也将在位于这些选定司法管辖区的服务器上处理。

. 由于为服务处理的信息以加密状态存储和传输，因此除预期参与者或 Ribose 的授权人员外，在任何司法管辖区的任何人都无法"清晰地"看到个人信息。

== 您的权利

您可以通过服务访问、审查和更改您的基本个人信息，通常从服务的设置区域。您可以向 Ribose 索取您的个人数据副本。我们可能会对此服务收取少量费用。您可以通过删除您的账户要求 Ribose 撤回、限制或反对处理您的个人数据。您可以要求 Ribose 将我们收集的数据传输给另一组织，或直接传输给您。

对于与个人信息相关的任何问题，您需要通过我们服务中的反馈或 {{ site.emails.privacy }} 向 Ribose 发出手动请求。您需要表明身份并请求访问、更改或删除的信息。我们可能会拒绝需要不成比例努力或可能侵犯他人权利的手动请求。如果我们接受删除请求，我们将开始删除存储在服务上的个人信息的过程，通常为 1 个月，只要法律不要求保留且合法业务目的不需要。由于我们服务的结构，在您的个人信息被删除后，残留副本从我们的服务和我们的备份系统中删除可能需要不超过 150 天。

== 外部链接和应用程序

本隐私政策仅适用于我们的服务。我们的服务可能提供指向非 Ribose 运营的资源（以下简称「外部资源」）的链接。如果您选择向任何外部资源提交个人信息，您的个人信息将受其隐私政策约束。我们鼓励您仔细阅读您访问的任何外部资源的隐私政策。

== 违规报告

. 我们将在知悉严重数据违规后立即向 DPC 通知有关您数据的严重数据违规，并在可行的情况下不迟于 72 小时。如果在 72 小时后未发出通知，我们将记录延迟的合理理由；但是，如果个人信息违规不太可能对自然人的权利和自由造成风险，则无需通知 DPC。在此上下文中，个人信息违规是指导致传输、存储或以其他方式处理的个人信息意外或非法破坏、丢失、更改、未经授权披露或访问的安全违规。

. 我们将保留任何数据违规的记录，包括其影响和采取的补救措施，并将在数据保护法规要求时通知您任何影响您个人信息的数据违规（这对您构成高风险）。在以下情况下，我们将不需要通知您数据违规：

.. 我们已实施适当的技术和组织措施，使个人信息对任何未经授权访问它的人无法理解，如加密；或

.. 我们已采取后续措施，确保数据主体的高风险不太可能实现；或

.. 这将涉及不成比例的努力，在这种情况下，我们可以改为进行公开沟通。

. 在发生严重的用户数据违规时，我们将尽快通知相关的数据控制者。

== 隐私政策的变更

. 我们可能会不时更改本隐私政策。最近修订的日期将出现在本页面上。如果隐私政策发生重大变更，我们将通过在我们的网站上放置更显著的通知或向您发送与此相关的通知来通知您。

. 如果您不同意本隐私政策的任何变更，您将需要停止使用服务并停用您的账户。

== 联系我们

如果您对本隐私政策有疑问或想就我们如何处理您的个人信息联系我们，请发送电子邮件至 {{ site.emails.privacy }}，或写信至我们联系页面上显示的地址。
