---
title: 服务条款
description: Ribose 服务条款
revision_date: 2023-11-16
revision_date_template: "最后修订日期：{{ revision_date | date: '%Y年%-m月%-d日' }}"
layout: page
hero_include: index-page-hero.html
---
:page-liquid:

CAUTION: 本页面为英文版本的翻译，仅供参考。如中英文版本有任何不一致之处，应以+++<a href="https://open.ribose.com/tos/">英文版本</a>+++为准。

== 条款

. Ribose 是 Ribose Inc.（一家英属维尔京群岛公司）（以下简称"Ribose"、"我们"或"我方"）的 Ribose 产品、软件、服务和网站（以下简称"服务"）的唯一所有者。

. 以下列出的是使用服务的条款和条件（以下简称"一般条款"）。

. 某些服务可能适用额外的法律声明和/或条款（以下简称"附加条款"）。

. 一般条款和附加条款共同构成您与 Ribose 之间具有法律约束力的协议（以下简称"条款"）。对于附加条款适用的特定服务，如有附加条款与一般条款之间的任何冲突，以附加条款为准。

== 接受

. 您使用服务即表示您同意受条款约束。点击接受或同意条款也表示您接受条款。

. 建议您定期查看一般条款的更新，因为您继续使用服务表示您接受任何变更的项目。一般条款可在 link:/tos/[服务条款] 找到。

== 服务提供

. Ribose 子公司和关联法律实体（以下简称"子公司和关联公司"）可以代表 Ribose 向您提供服务。您承认并同意子公司和关联公司将有权向您提供服务。

. Ribose 致力于为用户提供最佳体验。您承认并同意服务的形式和性质可能会不时变更，恕不另行通知。

. Ribose 可自行决定随时暂时或永久停止向您提供部分或全部服务，恕不另行通知。您可以随时停止使用服务，无需特别通知 Ribose。

. 您承认并同意，如果 Ribose 禁用您账户的访问权限，您可能无法访问服务、您的账户详情或与您账户相关的任何内容。

. 您承认并同意，虽然 Ribose 目前可能未对服务的交易或容量设定限制，但 Ribose 可随时自行决定设定或更改此类限制，恕不另行通知。

. 您提供给 Ribose 的数据可能根据类型和来源进行分类。您声明并保证，您不会将服务用于任何适用于与您使用服务相关数据的任何法律或法规所禁止的任何目的，并且您同意您使用服务和任何内容的风险由您自行承担。

== 知识产权

. 您承认并同意 Ribose 拥有服务的所有法律权利、所有权和利益，包括服务中存在的任何知识产权。此类权利在全球范围内属于 Ribose，无论此类权利的注册状态如何。

. 服务可能包含 Ribose 指定为机密的信息。您同意未经 Ribose 事先书面同意，不得披露此类信息。

. 服务及其所有内容（文章、文本、照片、图像、插图、图形、视频材料、音频材料和软件——统称为"知识产权"）受专利、版权、商标和各国法律及国际公约的保护。知识产权由 Ribose 拥有或控制。服务受专利和发明（以下简称"专利和发明"）的保护。此外，服务本身作为汇编作品和/或编辑作品受版权保护。

. 未经 Ribose 明确许可，不得复制、复制、复制、出售或以其他方式利用服务的任何部分用于任何商业目的。

. 除条款中明确规定外，您不得复制、下载、显示、分发、发布、输入数据库、表演、修改、创作衍生作品、传输、发布、反编译、反向工程、反汇编或以任何方式利用我们的任何知识产权或服务本身或其任何部分。

. 您同意不得删除、掩盖或更改服务中可能附带或包含的任何专有权利声明（包括版权和商标声明）。

. Ribose 名称和 Ribose 品牌印章、标志和相关标记是 Ribose 的注册商标/设计商标，或其他承载 Ribose 商誉的未注册商标。保留所有权利。条款中的任何内容均不授予您使用 Ribose 任何商业名称、商标、服务标记、标志、域名和其他独特品牌特征的权利。

. 如果 Ribose 通过单独的书面协议明确允许您使用任何这些品牌特征，您同意您对此类特征的使用将符合该协议、条款和 Ribose 的品牌特征指南。可以通过发送电子邮件至 {{ site.emails.support }} 索取 Ribose 的品牌特征指南。

.. 直接或间接质疑专利和发明或任何司法管辖区内源自专利和发明的任何专利或专利申请的有效性、可执行性或范围，并且在不限制前述一般性的情况下，同意不干扰审查程序或开始或参与任何反对程序或司法无效诉讼，无论是全部还是部分，关于专利和发明；或

.. 基于专利和发明或源自专利和发明提交或导致提交任何专利申请，包括但不限于基于或与专利和发明相关的任何改进专利申请或专利，或设计绕过专利和发明的任何专利申请或专利。基于或源自专利和发明的任何发明应完全归 Ribose 所有，您同意将任何此类发明转让给 Ribose。

== 账户信息和安全

. 您可能需要提供有关自己的信息（以下简称"个人信息"）才能访问某些服务或继续使用服务。此类信息可能在服务注册过程中或通过您继续使用服务时被要求提供。您同意您提供给 Ribose 的个人信息将始终准确、正确和最新。

. 您同意并理解，您对账户的访问控制负有唯一责任，包括对访问服务的账户访问凭证保密。因此，您同意您对账户下发生的所有活动向 Ribose 承担全部责任。

. 如果您知道您的账户或访问凭证有任何未经授权的使用，您同意立即通过 {{ site.emails.support }} 通知 Ribose。

. 您同意按照 Ribose 的隐私政策使用您的数据。Ribose 的隐私政策位于 link:/privacy/[隐私声明]。

== 正确使用

. 您不得将服务用于任何非法或条款禁止的目的，或在服务上造成损害。您承诺您在服务上或通过服务的任何行为都不会违反任何适用的地方、州、国家或国际法律、法规、普遍接受的做法或准则。

. 您同意仅通过 Ribose 提供的界面访问服务，除非您在与 Ribose 的单独协议中被特别允许这样做。您同意不使用自动化手段（包括脚本和爬虫）访问或尝试访问服务。

. 您同意不会从事或试图从事任何干扰或破坏服务或支持服务的任何部分的活动，或构成或促进服务的活动。

. 您同意赔偿、保护并使 Ribose 及其高级职员、董事、员工、代理人、许可方、业务合作伙伴和供应商免受因您以违反或被指控违反条款或任何适用法律的方式使用服务而产生或被指控产生的任何实际或威胁的索赔、诉讼或要求、责任和和解（包括但不限于合理的法律和会计费用）的损害。

== 内容

. 作为服务一部分或通过使用服务可访问的信息可能源自 Ribose 以外的第三方（以下简称"内容"）。此类内容是该内容来源方的唯一责任。Ribose 不对此类内容作任何陈述、推荐或保证，并且不对此类内容的任何部分承担任何责任或义务。

. 您理解服务中或通过服务呈现的某些内容（包括广告和赞助内容）可能是向 Ribose 提供此类内容的第三方拥有的知识产权。您同意不得全部或部分修改、租赁、借出、出售、分发或基于此类内容创作衍生作品，除非您已获得该内容所有者的授权。

. Ribose 保留筛选、过滤、审查、修改、拒绝或删除服务中任何内容的权利。

== 您的内容

. Ribose 根据条款不从您（或您的许可方）获得对您在服务上或通过服务提交、发布或显示的任何内容的任何权利、所有权或利益，下述有限许可除外。您同意保护和执行您的权利是您的唯一责任，Ribose 没有义务代表您这样做。

. 您同意您对通过服务或在服务中创建、传输或显示的任何内容负有唯一责任（并且 Ribose 对您或任何第三方不承担任何责任），因此对此类行为的任何后果负有唯一责任，包括对 Ribose 的任何损害或损失。

. 您同意不会以可能或意图引起对此类标记、名称或标志的所有者或授权用户的混淆的方式使用任何公司或组织的任何商标、服务标记、商业名称、标志。

. 对于在服务上或通过服务提交、发布或显示的内容（以下简称"您的内容"），您授予 Ribose 永久、不可撤销、全球、免版税和非独占许可，以复制、改编、修改、翻译、发布、公开表演、公开显示和分发您的内容，唯一目的是使 Ribose 能够显示、分发、提供和推广服务（以下简称"内容许可"）。

. Ribose 可能通过或与其他方联合提供联合服务。您允许 Ribose 将您的内容提供给 Ribose 有关系的其他方以提供联合服务，并在提供这些服务时使用此类内容，根据内容许可。

. 您向 Ribose 确认并保证您拥有授予内容许可所需的所有权利、权力和权限。此外，您确认并保证 Ribose 不会侵犯任何第三方的任何权利，也不会因您向 Ribose 提交您的内容或向您提供服务而招致任何类型的责任或损害。

== 广告内容

. 您同意 Ribose 可以在服务上放置广告。某些广告或促销可能针对服务上存储或与服务相关的某些信息。Ribose 在服务上的广告形式、性质和实施可能随时变更，恕不另行通知。

== 外部内容

. 服务可能提供指向非 Ribose 运营的资源的链接（以下简称"外部资源"）。您承认并同意 Ribose 不对外部资源负责，因此不对您因访问外部资源或依赖外部资源而可能招致的任何损失或损害承担责任。

. Ribose 保留在不事先通知和不承担任何责任的情况下删除或取消链接任何外部资源的权利。

. 您承认并同意 Ribose 人员在外部资源上的引用或评论不反映 Ribose 的意见。

== Ribose 软件

. Ribose 向您分配个人、全球、免版税、不可转让和非独占许可，以使用 Ribose 作为服务的一部分或为便于向您提供服务而提供给您的软件（以下简称"软件"）。此许可的唯一目的是使您能够根据条款使用服务。

. 除非法律要求或 Ribose 书面明确许可，否则您不得复制、下载、显示、分发、发布、输入数据库、表演、修改、创作衍生作品、传输、发布、反编译、反向工程、反汇编、尝试提取源代码或以任何方式利用软件或其任何部分。

. 软件可能需要 Ribose 不时更新。您同意接收此类更新并允许 Ribose 将这些更新提供给您，以便向您提供服务。

== 交易

. 服务的某些区域使您能够申请加入一个或多个 Ribose 计划。这些计划的条款以及管辖您注册申请和参与这些计划的条款在该计划的许可协议中规定。您收到电子或其他形式的订单确认并不表示我们接受您的申请，也不构成被接受进入该计划。Ribose 保留在收到您的订单后根据管辖您申请的特定计划的许可协议接受或拒绝您的申请的权利。

== 终止

. 条款将继续适用，直到按以下规定终止。

. 您可以通过以下方式终止与 Ribose 的法律协议：

.. 向 Ribose 在条款开头描述的地址发送书面通知通知 Ribose；以及

.. 关闭或删除您所有服务的账户，如果此选项对您可用。

. 如果出现以下情况，Ribose 可以终止与您的法律协议：

.. 您违反了条款的任何规定，或 Ribose 认定您无法遵守条款；或

.. Ribose 被法律要求这样做；或

.. Ribose 不再能够向您提供服务

. 在条款终止时，您和 Ribose 受益于、受制于（或在条款有效期间累积的）或明示无限期继续适用的所有法律权利、义务和责任，以及"免责声明、责任限制和免除"和"其他"部分的规定应不受此终止的影响，并应无限期继续适用于此类权利、义务和责任。

== 免责声明、责任限制和免除

. Ribose 不保证服务上信息的准确性。您对服务上信息的信赖风险自担。

. 服务及其所有内容均"按原样"提供给您。RIBOSE 不作任何明示或暗示的保证或陈述，包括但不限于适销性、特定用途适用性、所有权、不侵犯第三方权利、数据准确性或安静享用的暗示保证。

. 在任何情况下，RIBOSE 或参与创建服务及其内容的任何其他人都不对任何损害或伤害承担责任，包括因涉及服务或其内容的任何情况而产生的任何直接、间接、偶然、特殊、后果性、惩罚性或其他损害（包括但不限于由错误、遗漏、中断、缺陷、性能故障、错误定向或重定向传输、互联网连接失败、服务未经授权使用、数据丢失、操作或传输延迟、安全漏洞、线路故障、服务任何用户的诽谤、冒犯或非法行为或计算机病毒、蠕虫、木马或其他有害组件造成的损害或伤害），即使您事先已告知 RIBOSE 此类损害的可能性。

. RIBOSE 不对服务上的材料在任何方面（包括及时性、正确性、准确性、可靠性或其他方面）作出任何保证或陈述。虽然我们做出合理努力提供有关服务上 Ribose 的准确和及时信息，但您不应假设所提供的信息始终是最新的，也不应假设服务包含有关我们公司的所有相关可用信息。我们不承担核实或维护此类信息时效性的义务。

. 适用法律可能不允许排除某些保证或限制或排除偶然或后果性损害的责任。因此，上述某些限制或排除可能不适用于您。但是，在任何情况下，Ribose 对您或任何第三方的损害、损失和诉讼原因的累计责任不得超过您为访问服务支付的金额（如有）或 100 美元，以较低者为准。您同意在诉讼原因产生之日起一年内提起任何和所有诉讼，在此日期之后提起的诉讼将被禁止。

. 如果您与 Ribose 发生争议，您免除 Ribose（以及我们的高级职员、董事、代理人和员工）因与此类争议相关或以任何方式连接的已知和未知、怀疑和未怀疑、披露和未披露的各种性质的索赔、要求和损害（实际和后果性）。

== 其他

. Ribose 保留寻求法律和衡平法上可用的所有补救措施以执行条款的权利，包括暂停或阻止您访问服务。

. 条款中的任何内容均不构成或被视为构成各方之间的合伙关系，任何一方均无权力或权力以任何方式或为任何目的约束任何其他方或对任何其他方产生责任。

. 未获得 Ribose 事先书面通知，您不得全部或部分转让、转移、转让、许可、分包、委托或以其他方式处置您在条款下的任何权利或义务。

. Ribose 延迟或未能执行条款的任何规定均不构成对我们在条款下任何权利的放弃。Ribose 收到的任何资金或任何人对我们行为的信赖均不被视为构成对条款任何部分的放弃。只有由 Ribose 授权代表签署的特定书面放弃才具有法律效力。

. 如果条款中规定的任何条款或规定被确定为根据现行或未来法律非法、无效或不可执行，则该条款或规定应被视为已删除，不影响所有剩余条款或规定的可执行性。

== 管辖法律和司法管辖权

. 用户同意条款以及条款和/或隐私声明或服务下产生或与之相关的任何争议将受香港特别行政区法律管辖并根据其解释，不考虑法律冲突，与本协议相关的任何争议的专属场所应为香港特别行政区法院，但 Ribose 应始终被允许在任何其他有管辖权的法院对用户提起任何诉讼或程序，Ribose 应始终被允许选择任何其他有管辖权的法律。

. 本英文版服务条款声明是 Ribose 与服务用户的正式协议。如果本英文版服务条款声明与其翻译成另一种语言的版本之间存在任何不一致，以本英文版文件为准。

. 明确排除适用于本协议的是称为《联合国国际货物销售合同公约》的法律。

== 条款变更

. Ribose 保留自行决定随时修改、更改或以其他方式变更条款的权利。我们将在一般条款页面上提供此类变更的通知。

. 您继续使用服务构成您接受并同意受这些变更的约束，不受限制、资格或变更。如果您在任何时候确定不接受这些变更，请参阅"终止"部分以终止关系。

== 更多信息

. 如果您对我们的服务条款有任何疑问，请发送电子邮件至 {{ site.emails.support }}。
