---
title: 隱私政策
description: Ribose Open 隱私政策
revision_date: 2023-11-15
revision_date_template: "最後修訂日期：{{ revision_date | date: '%Y年%-m月%-d日' }}"
layout: page
hero_include: index-page-hero.html
---
:page-liquid:

CAUTION: 本頁面為英文版本的翻譯，僅供參考。如中英文版本有任何不一致之處，應以+++<a href="https://open.ribose.com/privacy/">英文版本</a>+++為準。

== 簡介

. 您的隱私對 Ribose 至關重要。我們致力於保護您與我們分享的任何信息。

. 本隱私政策闡述了我們從您那裡收集的或您提供給我們的任何個人信息將被我們處理的基礎。

. 本隱私政策適用於所有服務，並已按照 Ribose 運營所在司法管轄區的隱私法律起草，以證明合規性。我們將根據數據保護法規處理您的個人信息。

. 本政策還描述了關於 Ribose 使用您個人信息的可用選擇，以及您可以採取的訪問個人信息、要求我們更正或刪除它，或投訴我們處理您個人信息的任何方面的步驟。

. 註冊您的賬戶、其使用和接受本隱私政策的條款表示您已審閱本隱私政策並同意受其約束。

. 在註冊您的賬戶之前（或在繼續使用服務之前），您需要接受本隱私政策，任何使用您賬戶的用戶也將需要在首次訪問（或在繼續訪問）我們通過您賬戶提供的服務之前明確接受本隱私政策。如果您不同意這些條款，必須立即離開我們的網站。如果您選擇接受本隱私政策，我們將保留您在此方面的接受記錄。

== 條款和定義

. 本文件中的「Ribose」、「我們」和「我方」統指 Ribose 集團公司，包括 Ribose Inc.（美國）、Ribose Limited（英國）和 Ribose Asia Limited（香港）。

. 「服務」是指 Ribose 提供的所有產品和服務，其中每一項被稱為「服務」。

. 「您的賬戶」是指由您創建的服務註冊賬戶。

. 「個人信息」是指與在世個人有關的數據，該個人可以從數據中或從數據與我們擁有或可能擁有的其他信息的結合中被識別，包括數據保護法規中描述的個人數據。

. 「數據保護法規」是指香港個人資料（私隱）條例以及與處理個人數據和隱私有關的任何其他適用法律或法規，如加州消費者隱私法、1988年和2003年數據保護法和指令95/46/EC，此類法規將不時被修訂、修訂或取代，包括通過通用數據保護條例（EU）2016/679（以下簡稱「GDPR」）（以及實施或補充GDPR的法律）的實施。

. 「用戶數據」是指由您或他人通過您的賬戶上傳的數據（可能包括個人信息），可能是您或他人在與服務相關聯時提供或使用的任何信息、數據或材料，包括但不限於用戶憑證、與服務相關聯的用戶或其他方共享的數據，和/或您在支持請求等過程中提供的任何個人信息。Ribose 是用戶數據的數據處理者（如數據保護法規中所定義）。

. 「外部資源」是指非 Ribose 運營的資源。

== 我們從您那裡收集的信息

我們充分尊重您與服務互動相關的隱私權，並努力在與您的交易中對我們將收集哪些信息以及我們將如何使用您的信息保持透明。

=== 您提供的信息

. Ribose 持有的大部分個人信息由您（用戶）提供。我們只在法律允許的情況下收集和使用個人信息。

. 賬戶和個人資料信息。您需要提供個人信息才能成為服務的用戶（以下簡稱「用戶」）。我們在您註冊賬戶、創建或修改個人資料、設置偏好、通過服務註冊或購買時收集有關您的信息。註冊過程要求提供全名、密碼和電子郵件地址。您還可以選擇在個人資料信息中添加頭像照片以及其他詳細信息，如生日、電話等，以在我們的服務中顯示。我們會跟蹤您在服務中輸入的偏好。雖然您被要求向 Ribose 提供真實姓名和有效的聯繫方式，但您可以使用別名（「屏幕名稱」）參與所有活動，如空間和對話。

. 您使用服務提供的內容。此內容包括您輸入平台及其應用程序的信息，如對話、日曆、聯繫人、空間成員資格等。您還可以選擇從自己的聯繫人來源將特定聯繫人上傳到 Ribose，但 Ribose 不會製作和存儲整個用戶通訊錄的副本。您上傳的任何聯繫人只能由您訪問，除非並直到您邀請他們加入空間並且他們選擇成為用戶，或者如果您在空間內容中明確包含有關他們的信息（如在上傳的文件或對話中）。

. 您通過我們的支持渠道提供的信息。這包括提供給服務客戶支持功能的信息以及與之的互動，包括給我們支持團隊的任何信息。您可能會被要求提供聯繫信息和其他必要信息以解決您報告的特定支持案例。

. 付款信息：我們在您註冊某些付費服務時收集某些付款和賬單信息。

=== 我們從服務使用中自動收集的信息

. 我們在使用服務（包括瀏覽我們的網站和在服務中採取某些操作）時收集有關您的信息。

. 您對服務的使用。我們會跟蹤您與服務互動時的某些信息，如您使用的功能及其參數。我們還收集有關您互動的空間和用戶的信息。

. Cookie。我們的 Cookie 頁面描述了我們使用的 Cookie。您可以將瀏覽器設置為拒絕 Cookie。但是，如果禁用 Cookie，某些服務可能無法正常工作。

. 服務器日誌。當您訪問我們的服務時，我們的服務器會自動記錄某些信息，其中可能包括您的 IP 地址、瀏覽器類型、瀏覽器語言、Web 請求、與服務的互動、請求的日期和時間、使用服務前訪問的網頁地址以及 Cookie 信息（見上文）。

. 客戶端信息。當您通過瀏覽器或移動應用程序（以下簡稱「客戶端設備」）登錄我們的服務時，我們的服務會自動記錄您的客戶端設備發送到我們服務的信息。此信息包括客戶端配置和插件、語言偏好、應用程序標識符和崩潰數據。

. 通信。我們保留您與 Ribose 之間的通信，無論您是否是服務的用戶。如果您註冊 Ribose 新聞通訊、網絡研討會或其他通信，或者您想總體上聯繫我們，我們將收集您的聯繫信息以滿足您的請求。在為您提供客戶支持的同時，我們也可能從您那裡收集額外信息。

. 位置數據。某些服務可能提供額外功能，這些功能需要比您的 IP 地址提供的更詳細的位置感知。只有在您選擇接受這些服務並被明確通知後，才會收集詳細的位置信息。

=== 我們從其他來源接收的信息

. 服務與第三方的集成。某些服務允許用戶配置與第三方服務的集成，例如用於導入聯繫人。我們從這些集成接收的信息取決於第三方服務的參數。

. 合作夥伴。我們與提供與我們互補服務的合作夥伴合作，如轉售商、集成商或基礎設施提供商，他們向我們提供有關您對服務的興趣和使用以及其他信息和聯繫方式的信息，以維持您對服務的使用。

. 對服務的外部訪問。某些服務在其他第三方網站上或通過其他第三方網站提供。提供給這些網站的個人信息可能會發送給 Ribose 以便向您提供服務。此類信息在 Ribose 持有時受本隱私政策保護。

. 第三方。營銷和廣告公司可能會向我們提供有關您對服務興趣的信息。

== 我們如何使用收集的信息

. Ribose 使用其持有的個人信息來提供和改進服務，並保護 Ribose 和 Ribose 用戶的權利和財產。

. 提供服務並個性化您的體驗。我們使用您的個人信息向您提供服務，如用於身份驗證、提供支持和處理必要的交易。服務可能包括個性化功能，例如上傳頭像照片的能力，在包含協作功能的服務中，有必要通過個人姓名識別用戶。

. 與您通信。我們使用您的個人信息向您發送有關您使用服務的消息，如活動通知和客戶支持，以及服務本身的任何更新。在大多數情況下，這些通信可以通過您賬戶中的設置區域進行定制。

. Ribose 持有的個人信息僅根據用戶做出的選擇使用和披露；例如，加入協作空間並參與對話。每個空間的隱私設置由其所有者/管理員設置；加入空間的用戶會被通知這些設置，並通過加入接受它們。

. 服務器日誌。我們使用此信息來管理服務，了解訪問者如何瀏覽服務，並增強您使用服務的體驗。

. 通信。Ribose 使用此信息以回應您的查詢並改進我們的服務。

. Cookie。Ribose 使用 Cookie 來提高服務質量，包括促進登錄和註冊過程、個性化您的體驗、分析和跟蹤用戶趨勢、衡量廣告和促銷效果。

. IP 地址。我們使用您的 IP 地址和/或國家偏好來近似確定您的位置，以便為您提供更好的服務體驗。

. 位置信息。我們可能將此信息與從您的 IP 地址派生的信息（例如區域位置）結合使用，以改善您的用戶體驗（例如使用特定語言或顯示天氣）。

=== 您的信息如何被共享

. Ribose 不會在未經您同意或除非法律要求的情況下共享您的數據（本隱私政策中規定的除外）。Ribose 僅在以下情況下向第三方（即非用戶）披露個人信息。

. 與服務用戶促進協作。您可以使用服務的功能與其他用戶共享內容，他們隨後能夠看到您的某些個人信息（如您的姓名）以識別該內容的來源。

. 與組織賬戶管理員進行管理。如果您對服務的訪問是由組織賬戶授予的，您的賬戶信息和使用情況將可由組織賬戶所有者以及所有者授權的人員訪問。

. 在 Ribose 集團內部。當第三方是 Ribose 集團的一部分並且該信息是提供服務所需時。對您個人信息的訪問僅限於需要代表 Ribose 處理它的 Ribose 員工、承包商和代理人，並受保密要求約束。

. 與簽約方促進提供服務。Ribose 簽約的服務提供商幫助執行付款處理和其他必要服務，以便我們向您提供服務，對此訪問或使用您的個人信息是必要的。簽約方必須按照本隱私政策合規處理此類信息。

. 與第三方。只有在您提供明確同意與特定第三方共享此類信息的情況下，我們才會與外部方共享信息。

. 與您對第三方服務的集成。您的賬戶可能已配置為與某些第三方服務集成，因此可能允許這些第三方訪問您的賬戶和其中的信息。我們敦促用戶查看這些第三方服務的隱私政策，因為他們對個人信息的處理和程序不受我們控制，因為本隱私政策不涵蓋第三方如何使用您的信息。

. 獲得明確同意。在某些情況下，您可能提供明確同意允許我們顯示某些個人信息，如在發布的成功案例中放置您的姓名。

. 確保安全。如果我們善意地認為披露對您或任何其他人的健康或安全是必要的。

. 遵守法律。如果 Ribose 被法律要求披露信息，例如遵守傳票（或類似的法律程序）或可執行的政府請求。Ribose 將在收到具有法律約束力的個人信息披露請求時通知您，除非法律禁止。

. 保護我們的權利。如果我們善意地認為披露對保護我們的權利、執行我們的條款、檢測、預防或以其他方式處理欺詐、安全或技術問題是必要的。此類信息將按照適用的法律和法規披露。

. 業務轉讓。如果任何服務涉及合併、收購或任何形式的出售其部分或全部資產，我們將在您的數據受不同隱私政策約束之前提供通知。

== 兒童使用服務

. Ribose 僅向組織和 13 歲以上的個人提供服務，並不將任何服務定向於年幼兒童。作為用戶加入的個人需要確認他們年滿 13 歲或以上。

. 如果我們意識到 13 歲以下兒童向我們提供了個人信息，我們將採取措施刪除此類信息。如果您意識到兒童向我們提供了個人信息，請聯繫我們。

== 我們如何存儲和保護信息

=== 我們如何保護信息

. Ribose 非常重視個人信息的保護安全。我們採取適當的安全措施，防止未經授權訪問、或未經授權更改、披露或銷毀您的個人信息。有關我們遵守的安全方案和防止未經授權訪問和披露的具體安全措施的詳情在我們的網站上提供。

=== 我們保留信息多長時間

. 個人信息。Ribose 在提供您的賬戶使用的服務所需的時間內以及適當的備份和歸檔目的保留個人信息。如果用戶被刪除，僅與用戶相關的個人信息將立即刪除，但備份除外，備份將在之後的合理時間內保留，以防您決定重新激活服務。

. 共享信息。此信息將由包含它的空間的所有者或擁有該空間的組織賬戶控制。Ribose 在向這些空間和/或組織賬戶提供服務所需的時間內保留此信息。

. 其他義務。我們還根據需要保留您的某些信息以遵守我們的法律義務、解決爭議、執行我們的協議、支持業務運營以及繼續開發和改進我們的服務。在我們為改進和開發服務保留信息的情況下，我們採取措施對此類信息進行匿名化處理，並且僅使用此類信息發現有關我們服務使用的集體見解，而不是具體分析有關您的個人特徵。

. 營銷信息。如果您選擇接收我們的營銷電子郵件，我們將在您最後一次表達對我們服務興趣（例如您最後一次打開我們的電子郵件或停止使用服務）之日起的合理時間內保留有關您營銷偏好的信息。我們將在創建此類信息之日起的合理時間內保留從 Cookie 和其他跟蹤數據派生的信息。

== 個人信息的國際傳輸

. Ribose 持有的個人信息在位於美國的服務器上處理。

. 使用服務的交易和通信將涉及信息至少暫時保存在參與用戶所在的司法管轄區。

. 某些服務允許用戶明確選擇服務的數據處理和存儲發生的司法管轄區，包括美國和香港，在這種情況下，相關的必要個人信息也將在位於這些選定司法管轄區的服務器上處理。

. 由於為服務處理的信息以加密狀態存儲和傳輸，因此除預期參與者或 Ribose 的授權人員外，在任何司法管轄區的任何人都無法"清晰地"看到個人信息。

== 您的權利

您可以通過服務訪問、審查和更改您的基本個人信息，通常從服務的設置區域。您可以向 Ribose 索取您的個人數據副本。我們可能會對此服務收取少量費用。您可以通過刪除您的賬戶要求 Ribose 撤回、限制或反對處理您的個人數據。您可以要求 Ribose 將我們收集的數據傳輸給另一組織，或直接傳輸給您。

對於與個人信息相關的任何問題，您需要通過我們服務中的反饋或 {{ site.emails.privacy }} 向 Ribose 發出手動請求。您需要表明身份並請求訪問、更改或刪除的信息。我們可能會拒絕需要不成比例努力或可能侵犯他人權利的手動請求。如果我們接受刪除請求，我們將開始刪除存儲在服務上的個人信息的過程，通常為 1 個月，只要法律不要求保留且合法業務目的不需要。由於我們服務的結構，在您的個人信息被刪除後，殘留副本從我們的服務和我們的備份系統中刪除可能需要不超過 150 天。

== 外部鏈接和應用程序

本隱私政策僅適用於我們的服務。我們的服務可能提供指向非 Ribose 運營的資源（以下簡稱"外部資源"）的鏈接。如果您選擇向任何外部資源提交個人信息，您的個人信息將受其隱私政策約束。我們鼓勵您仔細閱讀您訪問的任何外部資源的隱私政策。

== 違規報告

. 我們將在知悉嚴重數據違規後立即向 DPC 通知有關您數據的嚴重數據違規，並在可行的情況下不遲於 72 小時。如果在 72 小時後未發出通知，我們將記錄延遲的合理理由；但是，如果個人信息違規不太可能對自然人的權利和自由造成風險，則無需通知 DPC。在此上下文中，個人信息違規是指導致傳輸、存儲或以其他方式處理的個人信息意外或非法破壞、丟失、更改、未經授權披露或訪問的安全違規。

. 我們將保留任何數據違規的記錄，包括其影響和採取的補救措施，並將在數據保護法規要求時通知您任何影響您個人信息的數據違規（這對您構成高風險）。在以下情況下，我們將不需要通知您數據違規：

.. 我們已實施適當的技術和組織措施，使個人信息對任何未經授權訪問它的人無法理解，如加密；或

.. 我們已採取後續措施，確保數據主體的高風險不太可能實現；或

.. 這將涉及不成比例的努力，在這種情況下，我們可以改為進行公開溝通。

. 在發生嚴重的用戶數據違規時，我們將儘快通知相關的數據控制者。

== 隱私政策的變更

. 我們可能會不時更改本隱私政策。最近修訂的日期將出現在本頁面上。如果隱私政策發生重大變更，我們將通過在我們的網站上放置更顯著的通知或向您發送與此相關的通知來通知您。

. 如果您不同意本隱私政策的任何變更，您將需要停止使用服務並停用您的賬戶。

== 聯繫我們

如果您對本隱私政策有疑問或想就我們如何處理您的個人信息聯繫我們，請發送電子郵件至 {{ site.emails.privacy }}，或寫信至我們聯繫頁面上顯示的地址。
