---
title: 服務條款
description: Ribose 服務條款
revision_date: 2023-11-16
revision_date_template: "最後修訂日期：{{ revision_date | date: '%Y年%-m月%-d日' }}"
layout: page
hero_include: index-page-hero.html
---
:page-liquid:

CAUTION: 本頁面為英文版本的翻譯，僅供參考。如中英文版本有任何不一致之處，應以
https://www.ribose.com/tos/"[英文版本]
為準。

== 條款

. Ribose 是 Ribose Inc.（一家英屬維爾京群島公司）（以下簡稱"Ribose"、"我們"或"我方"）的 Ribose 產品、軟件、服務和網站（以下簡稱"服務"）的唯一所有者。

. 以下列出的是使用服務的條款和條件（以下簡稱"一般條款"）。

. 某些服務可能適用額外的法律聲明和/或條款（以下簡稱"附加條款"）。

. 一般條款和附加條款共同構成您與 Ribose 之間具有法律約束力的協議（以下簡稱"條款"）。對於附加條款適用的特定服務，如有附加條款與一般條款之間的任何衝突，以附加條款為準。

== 接受

. 您使用服務即表示您同意受條款約束。點擊接受或同意條款也表示您接受條款。

. 建議您定期查看一般條款的更新，因為您繼續使用服務表示您接受任何變更的項目。一般條款可在 link:/tos/[服務條款] 找到。

== 服務提供

. Ribose 子公司和關聯法律實體（以下簡稱"子公司和關聯公司"）可以代表 Ribose 向您提供服務。您承認並同意子公司和關聯公司將有權向您提供服務。

. Ribose 致力於為用戶提供最佳體驗。您承認並同意服務的形式和性質可能會不時變更，恕不另行通知。

. Ribose 可自行決定隨時暫時或永久停止向您提供部分或全部服務，恕不另行通知。您可以隨時停止使用服務，無需特別通知 Ribose。

. 您承認並同意，如果 Ribose 禁用您賬戶的訪問權限，您可能無法訪問服務、您的賬戶詳情或與您賬戶相關的任何內容。

. 您承認並同意，雖然 Ribose 目前可能未對服務的交易或容量設定限制，但 Ribose 可隨時自行決定設定或更改此類限制，恕不另行通知。

. 您提供給 Ribose 的數據可能根據類型和來源進行分類。您聲明並保證，您不會將服務用於任何適用於與您使用服務相關數據的法律或法規所禁止的任何目的，並且您同意您使用服務和任何內容的風險由您自行承擔。

== 知識產權

. 您承認並同意 Ribose 擁有服務的所有法律權利、所有權和利益，包括服務中存在的任何知識產權。此類權利在全球範圍內屬於 Ribose，無論此類權利的註冊狀態如何。

. 服務可能包含 Ribose 指定為機密的信息。您同意未經 Ribose 事先書面同意，不得披露此類信息。

. 服務及其所有內容（文章、文本、照片、圖像、插圖、圖形、視頻材料、音頻材料和軟件——統稱為"知識產權"）受專利、版權、商標和各國法律及國際公約的保護。知識產權由 Ribose 擁有或控制。服務受專利和發明（以下簡稱"專利和發明"）的保護。此外，服務本身作為彙編作品和/或編輯作品受版權保護。

. 未經 Ribose 明確許可，不得複製、複製、複製、出售或以其他方式利用服務的任何部分用於任何商業目的。

. 除條款中明確規定外，您不得複製、下載、顯示、分發、發布、輸入數據庫、表演、修改、創作衍生作品、傳輸、發布、反編譯、反向工程、反彙編或以任何方式利用我們的任何知識產權或服務本身或其任何部分。

. 您同意不得刪除、掩蓋或更改服務中可能附帶或包含的任何專有權利聲明（包括版權和商標聲明）。

. Ribose 名稱和 Ribose 品牌印章、標誌和相關標記是 Ribose 的註冊商標/設計商標，或其他承載 Ribose 商譽的未註冊商標。保留所有權利。條款中的任何內容均不授予您使用 Ribose 任何商業名稱、商標、服務標記、標誌、域名和其他獨特品牌特徵的權利。

. 如果 Ribose 通過單獨的書面協議明確允許您使用任何這些品牌特徵，您同意您對此類特徵的使用將符合該協議、條款和 Ribose 的品牌特徵指南。可以通過發送電子郵件至 {{ site.emails.support }} 索取 Ribose 的品牌特徵指南。

.. 直接或間接質疑專利和發明或任何司法管轄區內源自專利和發明的任何專利或專利申請的有效性、可執行性或範圍，並且在不限制前述一般性的情況下，同意不干擾審查程序或開始或參與任何反對程序或司法無效訴訟，無論是全部還是部分，關於專利和發明；或

.. 基於專利和發明或源自專利和發明提交或導致提交任何專利申請，包括但不限於基於或與專利和發明相關的任何改進專利申請或專利，或設計繞過專利和發明的任何專利申請或專利。基於或源自專利和發明的任何發明應完全歸 Ribose 所有，您同意將任何此類發明轉讓給 Ribose。

== 賬戶信息和安全

. 您可能需要提供有關自己的信息（以下簡稱"個人信息"）才能訪問某些服務或繼續使用服務。此類信息可能在服務註冊過程中或通過您繼續使用服務時被要求提供。您同意您提供給 Ribose 的個人信息將始終準確、正確和最新。

. 您同意並理解，您對賬戶的訪問控制負有唯一責任，包括對訪問服務的賬戶訪問憑證保密。因此，您同意您對賬戶下發生的所有活動向 Ribose 承擔全部責任。

. 如果您知道您的賬戶或訪問憑證有任何未經授權的使用，您同意立即通過 {{ site.emails.support }} 通知 Ribose。

. 您同意按照 Ribose 的隱私政策使用您的數據。Ribose 的隱私政策位於 link:/privacy/[隱私聲明]。

== 正確使用

. 您不得將服務用於任何非法或條款禁止的目的，或在服務上造成損害。您承諾您在服務上或通過服務的任何行為都不會違反任何適用的地方、州、國家或國際法律、法規、普遍接受的做法或準則。

. 您同意僅通過 Ribose 提供的界面訪問服務，除非您在與 Ribose 的單獨協議中被特別允許這樣做。您同意不使用自動化手段（包括腳本和爬蟲）訪問或嘗試訪問服務。

. 您同意不會從事或試圖從事任何干擾或破壞服務或支持服務的任何部分的活動，或構成或促進服務的活動。

. 您同意賠償、保護並使 Ribose 及其高級職員、董事、員工、代理人、許可方、業務合作夥伴和供應商免受因您以違反或被指控違反條款或任何適用法律的方式使用服務而產生或被指控產生的任何實際或威脅的索賠、訴訟或要求、責任和和解（包括但不限於合理的法律和會計費用）的損害。

== 內容

. 作為服務一部分或通過使用服務可訪問的信息可能源自 Ribose 以外的第三方（以下簡稱"內容"）。此類內容是該內容來源方的唯一責任。Ribose 不對此類內容作任何陳述、推薦或保證，並且不對此類內容的任何部分承擔任何責任或義務。

. 您理解服務中或通過服務呈現的某些內容（包括廣告和贊助內容）可能是向 Ribose 提供此類內容的第三方擁有的知識產權。您同意不得全部或部分修改、租賃、借出、出售、分發或基於此類內容創作衍生作品，除非您已獲得該內容所有者的授權。

. Ribose 保留篩選、過濾、審查、修改、拒絕或刪除服務中任何內容的權利。

== 您的內容

. Ribose 根據條款不從您（或您的許可方）獲得對您在服務上或通過服務提交、發布或顯示的任何內容的任何權利、所有權或利益，以下述有限許可除外。您同意保護和執行您的權利是您的唯一責任，Ribose 沒有義務代表您這樣做。

. 您同意您對通過服務或在服務中創建、傳輸或顯示的任何內容負有唯一責任（並且 Ribose 對您或任何第三方不承擔任何責任），因此對此類行為的任何後果負有唯一責任，包括對 Ribose 的任何損害或損失。

. 您同意不會以可能或意圖引起對此類標記、名稱或標誌的所有者或授權用戶的混淆的方式使用任何公司或組織的任何商標、服務標記、商業名稱、標誌。

. 對於在服務上或通過服務提交、發布或顯示的內容（以下簡稱"您的內容"），您授予 Ribose 永久、不可撤銷、全球、免版稅和非獨佔許可，以複製、改編、修改、翻譯、發布、公開表演、公開顯示和分發您的內容，唯一目的是使 Ribose 能夠顯示、分發、提供和推廣服務（以下簡稱"內容許可"）。

. Ribose 可能通過或與其他方聯合提供聯合服務。您允許 Ribose 將您的內容提供給 Ribose 有關係的其他方以提供聯合服務，並在提供這些服務時使用此類內容，根據內容許可。

. 您向 Ribose 確認並保證您擁有授予內容許可所需的所有權利、權力和權限。此外，您確認並保證 Ribose 不會侵犯任何第三方的任何權利，也不會因您向 Ribose 提交您的內容或向您提供服務而招致任何類型的責任或損害。

== 廣告內容

. 您同意 Ribose 可以在服務上放置廣告。某些廣告或促銷可能針對服務上存儲或與服務相關的某些信息。Ribose 在服務上的廣告形式、性質和實施可能隨時變更，恕不另行通知。

== 外部內容

. 服務可能提供指向非 Ribose 運營的資源的鏈接（以下簡稱"外部資源"）。您承認並同意 Ribose 不對外部資源負責，因此不對您因訪問外部資源或依賴外部資源而可能招致的任何損失或損害承擔責任。

. Ribose 保留在不事先通知和不承擔任何責任的情況下刪除或取消鏈接任何外部資源的權利。

. 您承認並同意 Ribose 人員在外部資源上的引用或評論不反映 Ribose 的意見。

== Ribose 軟件

. Ribose 向您分配個人、全球、免版稅、不可轉讓和非獨佔許可，以使用 Ribose 作為服務的一部分或為便於向您提供服務而提供給您的軟件（以下簡稱"軟件"）。此許可的唯一目的是使您能夠根據條款使用服務。

. 除非法律要求或 Ribose 書面明確許可，否則您不得複製、下載、顯示、分發、發布、輸入數據庫、表演、修改、創作衍生作品、傳輸、發布、反編譯、反向工程、反彙編、嘗試提取源代碼或以任何方式利用軟件或其任何部分。

. 軟件可能需要 Ribose 不時更新。您同意接收此類更新並允許 Ribose 將這些更新提供給您，以便向您提供服務。

== 交易

. 服務的某些區域使您能夠申請加入一個或多個 Ribose 計劃。這些計劃的條款以及管轄您註冊申請和參與這些計劃的條款在該計劃的許可協議中規定。您收到電子或其他形式的訂單確認並不表示我們接受您的申請，也不構成被接受進入該計劃。Ribose 保留在收到您的訂單後根據管轄您申請的特定計劃的許可協議接受或拒絕您的申請的權利。

== 終止

. 條款將繼續適用，直到按以下規定終止。

. 您可以通過以下方式終止與 Ribose 的法律協議：

.. 向 Ribose 在條款開頭描述的地址發送書面通知通知 Ribose；以及

.. 關閉或刪除您所有服務的賬戶，如果此選項對您可用。

. 如果出現以下情況，Ribose 可以終止與您的法律協議：

.. 您違反了條款的任何規定，或 Ribose 認定您無法遵守條款；或

.. Ribose 被法律要求這樣做；或

.. Ribose 不再能夠向您提供服務

. 在條款終止時，您和 Ribose 受益於、受制於（或在條款有效期間累積的）或明示無限期繼續適用的所有法律權利、義務和責任，以及"免責聲明、責任限制和免除"和"其他"部分的規定應不受此終止的影響，並應無限期繼續適用於此類權利、義務和責任。

== 免責聲明、責任限制和免除

. Ribose 不保證服務上信息的準確性。您對服務上信息的信賴風險自負。

. 服務及其所有內容均"按原樣"提供給您。RIBOSE 不作任何明示或暗示的保證或陳述，包括但不限於適銷性、特定用途適用性、所有權、不侵犯第三方權利、數據準確性或安靜享用的暗示保證。

. 在任何情況下，RIBOSE 或參與創建服務及其內容的任何其他人都不對任何損害或傷害承擔責任，包括因涉及服務或其內容的任何情況而產生的任何直接、間接、偶然、特殊、後果性、懲罰性或其他損害（包括但不限於由錯誤、遺漏、中斷、缺陷、性能故障、錯誤定向或重定向傳輸、互聯網連接失敗、服務未經授權使用、數據丟失、操作或傳輸延遲、安全漏洞、線路故障、服務任何用戶的誹謗、冒犯或非法行為或計算機病毒、蠕蟲、木馬或其他有害組件造成的損害或傷害），即使您事先已告知 RIBOSE 此類損害的可能性。

. RIBOSE 不對服務上的材料在任何方面（包括及時性、正確性、準確性、可靠性或其他方面）作出任何保證或陳述。雖然我們做出合理努力提供有關服務上 Ribose 的準確和及時信息，但您不應假設所提供的信息始終是最新的，也不應假設服務包含有關我們公司的所有相關可用信息。我們不承擔核實或維護此類信息時效性的義務。

. 適用法律可能不允許排除某些保證或限制或排除偶然或後果性損害的責任。因此，上述某些限制或排除可能不適用於您。但是，在任何情況下，Ribose 對您或任何第三方的損害、損失和訴訟原因的累計責任不得超過您為訪問服務支付的金額（如有）或 100 美元，以較低者為準。您同意在訴訟原因產生之日起一年內提起任何和所有訴訟，在此日期之後提起的訴訟將被禁止。

. 如果您與 Ribose 發生爭議，您免除 Ribose（以及我們的高級職員、董事、代理人和員工）因與此類爭議相關或以任何方式連接的已知和未知、懷疑和未懷疑、披露和未披露的各種性質的索賠、要求和損害（實際和後果性）。

== 其他

. Ribose 保留尋求法律和衡平法上可用的所有補救措施以執行條款的權利，包括暫停或阻止您訪問服務。

. 條款中的任何內容均不構成或被視為構成各方之間的合夥關係，任何一方均無權力或權力以任何方式或為任何目的約束任何其他方或對任何其他方產生責任。

. 未獲得 Ribose 事先書面通知，您不得全部或部分轉讓、轉移、轉讓、許可、分包、委託或以其他方式處置您在條款下的任何權利或義務。

. Ribose 延遲或未能執行條款的任何規定均不構成對我們在條款下任何權利的放棄。Ribose 收到的任何資金或任何人對我們行為的信賴均不被視為構成對條款任何部分的放棄。只有由 Ribose 授權代表簽署的特定書面放棄才具有法律效力。

. 如果條款中規定的任何條款或規定被確定為根據現行或未來法律非法、無效或不可執行，則該條款或規定應被視為已刪除，不影響所有剩餘條款或規定的可執行性。

== 管轄法律和司法管轄權

. 用戶同意條款以及條款和/或隱私聲明或服務下產生或與之相關的任何爭議將受香港特別行政區法律管轄並根據其解釋，不考慮法律衝突，與本協議相關的任何爭議的專屬場所應為香港特別行政區法院，但 Ribose 應始終被允許在任何其他有管轄權的法院對用戶提起任何訴訟或程序，Ribose 應始終被允許選擇任何其他有管轄權的法律。

. 本英文版服務條款聲明是 Ribose 與服務用戶的正式協議。如果本英文版服務條款聲明與其翻譯成另一種語言的版本之間存在任何不一致，以本英文版文件為準。

. 明確排除適用於本協議的是稱為《聯合國國際貨物銷售合同公約》的法律。

== 條款變更

. Ribose 保留自行決定隨時修改、更改或以其他方式變更條款的權利。我們將在一般條款頁面上提供此類變更的通知。

. 您繼續使用服務構成您接受並同意受這些變更的約束，不受限制、資格或變更。如果您在任何時候確定不接受這些變更，請參閱"終止"部分以終止關係。

== 更多信息

. 如果您對我們的服務條款有任何疑問，請發送電子郵件至 {{ site.emails.support }}。
