---
layout: post
title: "Casual Collaboration Platform from Ribose Now Open for Beta Users"
date: 2012-08-29 15:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Casual Collaboration Platform from Ribose Now Open for Beta Users
---
= Casual Collaboration Platform from Ribose Now Open for Beta Users

*Take the hassle out of making plans with friends and family for Labor
Day*

BOSTON, Aug. 30, 2012 /PRNewswire/ -- The Labor Day weekend is a great
opportunity to connect with family and friends for one last time over
the summer, but coordinating plans can be more time consuming than
working! Just in time for the holiday, http://www.ribose.com/[Ribose]
today announced that it is offering a limited number of beta log-ins for
its new online platform, http://www.ribose.com/[www.ribose.com].

Ribose is designed to simplify the way groups of all sizes collaborate. 
The platform brings together an unmatched collection of tools,
applications and widgets that harness the real-time, social and
cloud-based flexibility of today's internet to help streamline, organize
and plan anything from a small family gathering to a social club's
ongoing activities.  

Beta access to the Ribose site is free for registered users. Beta users
will be allowed up to 10 invitations to begin building their
collaboration teams. To learn more, or to register for beta access and
begin tapping into the power of casual collaboration, visit
http://www.ribose.com/[www.ribose.com]. The site will launch as a full
release in the fall of 2012.

Follow Ribose on Twitter: https://twitter.com/RiboseUS

'''

== About Ribose

For busy people who struggle to plan and manage all of the personal or
business projects, events and adventures that make their life
interesting, Ribose is a full-featured casual collaboration platform
that provides all the necessary tools and connections needed to
simultaneously plan activities of all sizes with friends, family,
colleagues and partners. Founded by Ronald Tse, Ribose brings together
in one secure site the real-time, social and cloud based flexibility of
today's internet with a full catalogue of tools, applications and
widgets, to uncover even more linkages, better streamline activities and
create customizable new ways to organize anything from a small, casual
family gathering to a social club's ongoing activities.

---

Originally published at:

* http://www.prnewswire.com/news-releases/casual-collaboration-platform-from-ribose-now-open-for-beta-users-168078926.html[PRNewswire: Casual Collaboration Platform from Ribose Now Open for Beta Users]

