---
layout: post
title: "Online Collaboration -- Losing The Human Touch and Connection?"
date: 2013-11-18 16:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Online Collaboration -- Losing The Human Touch and Connection?
---
= Online Collaboration -- Losing The Human Touch and Connection?

Wanted to comment on an article that was published today in Global
Business Hub ---
*http://www.boston.com/business/blogs/global-business-hub/2013/11/tech_changes_ho.html*
-- that talks about the importance of keeping employees happy at work by
keeping them engaged.  The article further explains how social networks
like Yammer, Huddle, and Jive are making employees more engaged and that
ultimately more engaged employees, are more productive employees.  The
author also discusses how the technologies in our personal lives to
connect and communicate are also becoming technologies we use at work.  
More and more, the technical experience we have at work is mimicking the
one at home --making the distinction between our working life and our
personal life more blurred.

Ribose gets this concept and believes that collaborating should not only
be a process that keeps people more productive, but it also should be a
way for people to get to know one another and how they tick as
co-workers and individuals.   A key point in the article that we at
Ribose get is that millennials are looking to create a seamless
work/play existence where  baby boomers like our "`unconnected`" moments.
It's the millennials who are the drivers for getting a Facebook-like
experience at the office.  So we ask, is using social collaboration
tools  going to be the way we communicate in and out of the office?
 Take a look at how we use our phones today for text messages and
emails.  On-line collaboration tools are everywhere and are for personal
and professional use.  We believe that everyone is driving for that
"Facebook" experience.

Our goal is to connect all people whether they are millennials or baby
boomers in an effort to help them work smarter and have fun while
working. And most importantly, we want people to be more productive
while collaborating so they can get out of their offices and do the
things they love and connect person to person in the flesh.   Technology
will enable people to connect and collaborate like never before.  Some
see it as taking away the human touch.   But in order to work with
others on a virtual basis collaboration platforms are essential.  And
most importantly, they can also have a human touch because collaborating
is about connecting and building relationships.
