---
layout: post
title: "We've revamped www.ribose.com!"
date: 2013-06-24 00:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  We've revamped www.ribose.com!
---
= We've revamped www.ribose.com!

Hello from the UX team,

If you haven't already, check out - www.ribose.com as we have (finally)
revamped the design. From our private beta we found that many of you had
difficulty explaining the site to your friends, family and colleagues.
The updated design should make it easier to demonstrate the benefits of
using Ribose for your collaboration needs without too much effort on
your side. We hope the new content will help potential new users
understand Ribose from the get go so that you can get on with what's
important - collaborating!
So what's new? The most obvious changes are - on the home page you will
find an overview of features, examples ('user scenarios') of how you
could potentially use Ribose as well as a brief 2 min video that aims to
explain Ribose to the new user. Design, content and navigation have been
greatly improved so that you get the information you want, easily.

We are still tweaking and adding stuff, feel free to send an email to
feedback@ribose.com if you have any suggestions or criticism. We are
listening.

Meanwhile, expect a lot of design changes within my.ribose in the coming
months!

