---
layout: post
title: "Collaborate to Solve World Issues"
date: 2013-11-07 08:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Collaborate to Solve World Issues
---
= Collaborate to Solve World Issues

As many people are facing tougher times and dealing with poverty and
homelessness, it is so important now to work together as communities to
help those in need. Today an article in the Huffington Post talked about
the issue of how many children are homeless in the States. We need to
collaborate with other individuals and communities to help solve such an
issue and it can be done. Your neighborhood can work together to help
one child as well as local support organizations you are working with.
Collaboration is about teamwork. And if we can work together to help
those in need we are heading in the right direction.

Read more about the issues of children students who are homeless in the
United States.   You can make a difference by working with a team to
figure out how to help.  

http://www.huffingtonpost.com/2013/11/07/childhood-homelessness_n_4233503.html?ref=topbar
