---
layout: post
title: "Origins of the Ribose name"
date: 2013-07-26 00:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Origins of the Ribose name
---
= Origins of the Ribose name

Since our beta launch, we have often been asked about the reasoning
behind our name. Our choice all links back to our goal: to empower
like-minded people to collaborate effectively and successfully.

Ribose literally is sweet -- a type of sugar with the chemical formula
C5H10O5, which tastes sweet just like table sugar.

Although simple by itself, ribose sugar is capable of linking into a
long, complex structure. In fact, this structure forms the backbone for
RNA and DNA, the basic building blocks of earth's living forms. RNA and
DNA are much more than the sum of their parts, helping build life as we
know it.

Similarly, the value of successful collaboration lies in positive,
synergistic results. A lion's share of mankind's achievements arose
through people working together, with the results realized being far
superior to those of people working separately.

Just as how ribose sugar forms the backbone to essential life, we strive
to serve the fabric of the collaboration experience for everyone. By
helping people work together more productively, Ribose allows you (and
your team) more time to focus on what you love, providing a greater
opportunity to make our world a better place!
