---
layout: post
title: "Ribose: World's first cloud service provider certified to Multi-Tier Cloud Security standard achieves highest Level 3 security tier"
date: 2014-12-07 16:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose: World's first cloud service provider certified to Multi-Tier Cloud Security standard achieves highest Level 3 security tier
---
= Ribose: World's first cloud service provider certified to Multi-Tier Cloud Security standard achieves highest Level 3 security tier

*Singapore/Hong Kong, 8 December 2014 --* http://www.ribose.com[Ribose],
the world's first cloud service provider (CSP) certified to Singapore's
https://www.imda.gov.sg/about/newsroom/archived/ida/media-releases/2013/new-multi-tier-cloud-security-mtcs-standard-launched-in-singapore[Multi-Tier
Cloud Security (MTCS)] program, has recently achieved the highest
possible security tier: Level 3.

Initiated by the https://www.imda.gov.sg[Infocomm Development Authority of
Singapore (IDA)] and launched by http://www.spring.gov.sg[SPRING
Singapore], the MTCS standard (SS 584:2013) specifies stringent security
and operational requirements for CSPs, encouraging adoption of sound
risk management and security practices. MTCS Certification specifies
three tiers of security levels, with Level 3 being the highest. The
http://www.sac-accreditation.gov.sg[Singapore Accreditation Council
(SAC)] has recently launched an accreditation program for MTCS
Certification.

Ribose was the first CSP worldwide to achieve MTCS certification in June
2014 with a security tier of Level 1. Following a thorough evaluation by
http://www.bsigroup.com[BSI (British Standards Institution)], a
participating Certification Body for the MTCS standard, Ribose has
upgraded its certification to the highest security tier, Level 3 --
indicating its platform is suitable for running high-impact workloads,
serving business- and mission-critical purposes, and hosting sensitive
information as well as highly confidential business data.

"`Ribose is proud to be the first Software-as-a-Service (Saas) provider
certified to the MTCS standard, and the first SaaS platform to achieve
the coveted Level 3 security tier,`" explained Ronald Tse, founder of
Ribose.  "`This is a major milestone for Ribose, confirming our
platform's government-approved security standards for handling users'
highly sensitive and confidential data.`"

Owen Xu, General Manager of BSI Singapore, commented, "`BSI takes pride
in employing the most stringent auditing standards in the industry. With
over 60,000 clients around the globe, our experts have audited many of
the world's largest companies and government organizations that require
top-notch security. By achieving MTCS at Level 3, Ribose has
demonstrated its platform's security is indeed world-class.`"

'''

== About Ribose

Ribose is a cloud collaboration platform that makes working together
easy and fun. A forerunner in cloud security, Ribose is the world's
first cloud service provider certified to
https://cloudsecurityalliance.org/star/[CSA STAR]
(https://cloudsecurityalliance.org/research/ccm/[CCM 3.0.1]) and
https://www.imda.gov.sg/regulations-licensing-and-consultations/ict-standards-and-quality-of-service/it-standards-and-frameworks/mtcs-certification-scheme[MTCS].
It is also certified to http://www.iso.org/iso/iso27001[ISO/IEC 27001],
http://www.isoiec20000certification.com[ISO/IEC 20000] and
https://www.mesalliance.org/communities/CDSA/production-security-guidelines/[CDSA
CPS] standards, and approved by the
https://www.digitalmarketplace.service.gov.uk/[UK Government's G-Cloud
program] for government use.

Ribose is free to use: http://www.ribose.com[ribose.com].

== About BSI

BSI (British Standards Institution) helps businesses turn best practices
into habits of excellence. As the world's first national standards body
and a founding member of http://www.iso.org/[ISO], BSI's standards
inspire excellence across the globe:
http://www.bsigroup.com[bsigroup.com].

---

Originally published at:

* https://en.prnasia.com/releases/global/Ribose_World_s_first_cloud_service_provider_certified_to_Multi_Tier_Cloud_Security_standard_achieves_highest_Level_3_security_tier-111168.shtml[PRNewswire: Ribose: World's first cloud service provider certified to Multi-Tier Cloud Security standard achieves highest Level 3 security tier]
* http://hk.prnasia.com/story/archive/1284149_XG84149_2[PRNewswire HK: Ribose 通過多層雲端安全（MTCS）最高評級第三級安全認證]
* http://www.prnasia.com/story/archive/1284149_ZH84149_1[PRNewswire China: Ribose 通过多层云安全（MTCS）最高评级第三级安全认证]
