---
layout: post
title: "The Collaboration Economy - Hot Topic and Trend for 2014"
date: 2014-01-18 08:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  The Collaboration Economy - Hot Topic and Trend for 2014
---
= The Collaboration Economy - Hot Topic and Trend for 2014

Ribose is excited to see how collaboration is becoming more of a way to
help people and businesses live a more sustainable life.  One of the hot
topics and trends we are reading about is called *The Collaboration
Economy.*  In a recent article in the publication *Sustainable Brands*
we see how collaboration is key in reducing waste around the world.
 Here are a few soundbites from the article that give you an idea about
how this concept works.  

The Collaborative Economy is associated with sharing resources to reduce
waste, but its primary focus is on the economics of collaboration and
the efficiencies of networks. The Collaborative Economy seeks to harness
crowds, collectives, communities and co-ops to co-create, co-ideate,
co-design, co-fund, co-own, co-build, co-distribute, co-market, co-sell,
co-profit and co-prosper.  

While http://www.sustainablebrands.com/news_and_views/Collaboration/all[collaboration
in business] may seem counterintuitive to competition, many highly
competitive industries such as auto and hospitality are adopting
collaborative practices that are disrupting and innovating. Some call
this "`co-opetition,`" while others call it "`open API business`" (a nod to
the app-ification of our world).

As marketers, there are three questions that we should be asking
ourselves relative to the *Collaborative Economy: *

\1.  How does it impact my customers, products, services, distribution
and pricing model?

\2.   Within my organization, how do I develop a greater awareness for
collaboration and sharing?

\3.   If Brand = Crowd & Co, then how do I maintain control over my
brand?

Next year, we will see the Collaborative Economy concept, or ideal,
shift from being mostly a niche, male-dominated topic associated with
Silicon Valley programmers to a mainstream topic that marketers and
brands will be discussing — and looking for ways to address. Social
listening indicates that men comprise double the percentage of women
discussing the Collaborative Economy right now, but this is starting to
change.

And just as we
see http://www.sustainablebrands.com/news_and_views/leadership/women-leadership-good-us-all[women]become
more involved, we will also see new jobs arise, such as the "`Chief
Collaboration Officer`" as companies introduce "`Collaboration
Departments`" to work in tandem with marketing departments. Imagine your
brand's social media has a "`collaborate`" button next to "`shares`" and
"`likes.`" If this were the case, social collaboration could trump social
engagement.
