---
layout: post
title: "Ribose becomes world's first casual collaboration platform to achieve ISO 9001:2008 certification"
date: 2014-10-11 15:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose becomes world's first casual collaboration platform to achieve ISO 9001:2008 certification
---
= Ribose becomes world's first casual collaboration platform to achieve ISO 9001:2008 certification

*Achieves internationally recognized standard for quality management
systems *

*Hong Kong, 13 October 2014* -- http://www.ribose.com[Ribose] has become
the world's first casual collaboration platform to be awarded the
http://www.iso.org/iso/iso_9000[ISO 9001:2008] certification for
international quality management systems.

ISO 9001 is the world's most widely recognized standard for quality
management systems. This latest certification verifies Ribose's ability
to consistently meet the needs of customers and other key stakeholders
in both the delivery and continuous improvement of products and
services.

Ribose's certification -- awarded by http://www.bsigroup.com[BSI (British
Standards Institution)], the originator of the ISO 9001 standard --
covers all processes within the company, ranging from the design and
development of services to ongoing customer support for the company's
online collaboration platform. Ribose's adoption of ISO 9001:2008
standards will help ensure customers receive consistently high-quality
products and services as the company continues to grow. 

"`Ribose is committed to helping people work together more effectively
and efficiently,`" said Ronald Tse, founder of Ribose. "`Quality
improvement has always been a cornerstone of that commitment -- which is
why our ISO 9001:2008 certification represents a powerful validation of
our systematic framework for service improvement, and the effectiveness
of our information security, business continuity and management
systems.`"

BSI awarded Ribose the ISO 9001:2008 certification after validation of
all applications, systems, processes and services within the company by
an independent accredited auditor.

"`As the world's most widely adopted quality management system
certification standard, ISO 9001 represents a badge of confidence
between customers and companies,`" said Emmanuel Herve, Managing Director
of BSI Hong Kong. "`Ribose's certification demonstrates its firm
commitment to delivering quality services which help people work
together better.`"

'''

== About Ribose

Ribose makes collaborating easy and fun. Whether planning business
projects or social events, the Ribose platform helps users collaborate
through world-class security certified to the highest standards,
including http://www.iso.org/iso/iso27001[ISO/IEC 27001],
https://cloudsecurityalliance.org/star/certification/[CSA STAR],
https://www.mesalliance.org/communities/CDSA/production-security-guidelines/[CDSA
CPS] and
https://www.imda.gov.sg/regulations-licensing-and-consultations/ict-standards-and-quality-of-service/it-standards-and-frameworks/mtcs-certification-scheme[IDA
MTCS]. Ribose is also certified to the
http://www.iso.org/iso/iso_9000[ISO 9001],
http://www.iso.org/iso/catalogue_detail?csnumber=50038[ISO 22301] and
http://www.bsigroup.com/en-GB/pas-99-integrated-management/[PAS 99]
standards. Also available as part of the
https://www.digitalmarketplace.service.gov.uk/search?keyword=ribose[UK
Government's G-Cloud] program, Ribose is free to use:
http://www.ribose.com.

== About BSI

The British Standards Institution is the business standards company that
helps businesses turn best practices into habits of excellence. As the
world's first national standards body and a founding member of ISO, BSI
is an organization whose standards inspire excellence across the globe:
http://www.bsigroup.com.

---

Originally published at:

* http://www.prnewswire.com/news-releases/ribose-becomes-worlds-first-casual-collaboration-platform-to-achieve-iso-90012008-certification-278986301.html[PRNewswire: Ribose becomes world's first casual collaboration platform to achieve ISO 9001:2008 certification]
* http://en.prnasia.com/story/106689-0.shtml[PRNewswire HK: Ribose becomes world's first casual collaboration platform to achieve ISO 9001:2008 certification]
* http://hk.prnasia.com/story/106690-2.shtml[PRNewswire HK: Ribose 成為全球首家通過 ISO 9001:2008 認證的休閒協作平臺 -- 質量管理體系受到國際公認標準認可]
* http://www.prnasia.com/story/106691-1.shtml[PRNewswire CN: Ribose 成为全球首家通过 ISO 9001:2008 认证的休闲协作平台]
