---
layout: post
title: "Ribose committed to health and safety with OHSAS 18001:2007 certification"
date: 2014-10-26 15:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose committed to health and safety with OHSAS 18001:2007 certification

---
= Ribose committed to health and safety with OHSAS 18001:2007 certification

*Hong Kong, 27 October 2014 --* http://www.ribose.com[Ribose] has
achieved certification to the
http://www.bsigroup.com/en-GB/ohsas-18001-occupational-health-and-safety/[OHSAS
18001:2007] international standard for occupational health and safety
management systems. OHSAS 18001:2007 promotes healthy and safe working
environments by setting out international best practices -- helping
organizations manage and control risks, and continuously improve
performance.

Ribose's OHSAS 18001 certification was awarded by
http://www.bsigroup.com[BSI (British Standards Institution)] -- who
established the British Standard BS OHSAS 18001:2007 -- after validation
of Ribose's applications, systems, processes and services by an
independent accredited auditor.

"`Our staff are the heart of our company, and their wellbeing is our top
priority,`" explained Ribose founder Ronald Tse. "`Achieving OHSAS 18001
certification demonstrates the sincerity of Ribose's commitment to
health and safety, and provides us with a framework for constant
improvement.`"

"`Offices tend to be low-risk environments and health and safety risks
are often overlooked in the technology industry -- however repetitive
strain injuries and back injuries are quite common,`" Tse noted. "`Having
formal health and safety measures in place increases our efficiency and
reduces costs in the long run by avoiding accidents, reducing illness
and improving staff motivation. Implementing OHSAS 18001 standards has
allowed us to thoroughly consider health and safety issues in a holistic
way across the entire organization.`"

Emmanuel Herve, Managing Director of BSI Hong Kong, commented, "`Many
people associate construction and manufacturing with high risks, but
wellness and safety considerations apply to all industries -- including
office-based environments. By achieving OHSAS 18001 certification,
Ribose is taking responsibility for the wellbeing of its staff and
customers, setting a robust example for the technology industry.`"

'''

== About Ribose

Ribose is a cloud collaboration platform that makes working together
easy and fun. A forerunner in cloud security, Ribose is the world's
first cloud service provider certified to
https://cloudsecurityalliance.org/star/[CSA STAR] using
https://cloudsecurityalliance.org/research/ccm/[CCM v3] and
https://www.imda.gov.sg/regulations-licensing-and-consultations/ict-standards-and-quality-of-service/it-standards-and-frameworks/mtcs-certification-scheme[MTCS].
It is also certified to http://www.iso.org/iso/iso27001[ISO/IEC 27001]
and
https://www.mesalliance.org/communities/CDSA/production-security-guidelines/[CDSA
CPS] standards, and approved by the
https://www.digitalmarketplace.service.gov.uk/[UK Government's G-Cloud
program] for government use.

Ribose is free to use: http://www.ribose.com[ribose.com].

== About BSI

BSI (British Standards Institution) helps businesses turn best practices
into habits of excellence. As the world's first national standards body
and a founding member of http://www.iso.org/[ISO], BSI's standards
inspire excellence across the globe:
http://www.bsigroup.com[bsigroup.com].

---

Originally published at:

* http://www.prnewswire.com/news-releases/ribose-committed-to-health-and-safety-with-ohsas-180012007-certification-311505406.html[PRNewswire: Ribose committed to health and safety with OHSAS 18001:2007 certification]
* http://en.prnasia.com/story/107792-0.shtml[PRNewswire HK: Ribose committed to health and safety with OHSAS 18001:2007 certification]
* http://hk.prnasia.com/story/107794-2.shtml[PRNewswire HK: Ribose 榮獲 OHSAS 18001:2007 職業健康和安全體系認證]
* http://www.prnasia.com/story/107795-1.shtml[PRNewswire CN: Ribose 荣获 OHSAS 18001:2007 职业健康安全体系认证]

