---
layout: post
title: "Ribose awarded PAS 99 certification for integrated management systems"
date: 2014-06-16 15:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose awarded PAS 99 certification for integrated management systems
---
= Ribose awarded PAS 99 certification for integrated management systems

*Ribose* *awarded PAS 99 certification for integrated management
systems*

*Achieves internationally certified corporate governance and compliance
management*

*Hong Kong, 17 June 2014 --* http://www.ribose.com[Ribose] has achieved
PAS 99:2012 certification, the internationally accepted framework for
integrated management systems (IMS).

Ribose is the first collaboration platform in the world and the first
organization in Hong Kong to achieve this certification. Ribose's IMS
integrates its existing business continuity and information security
management systems, satisfying both ISO 22301:2012 and ISO 27001:2013,
the international standards for business continuity and information
security, respectively.

Ribose's certification was awarded by http://www.bsigroup.com[BSI
(British Standards Institution)], the originator of the PAS 99, ISO
22301 and ISO 27001 standards. Certification is awarded only after an
independent accredited auditor has thoroughly checked all applications,
systems, processes and services.

PAS 99 is a framework for integrating management systems built on
different management systems standards (MSS). It specifies requirements
for streamlining and managing MSSs, allowing for improved business
focus, a more universal approach to risk mitigation and improved
operational efficiency.

"`Ribose is dedicated to providing our users with the highest standards
of service. Achieving PAS 99 certifies that our management systems are
tightly integrated -- including our highly dynamic information security
management system, which has been awarded numerous security
certifications such as ISO 27001, CSA STAR and CDSA CPS,`" explained
Ronald Tse, founder of Ribose. "`We believe the holistic approach is key
to effective collaboration, and we've taken that to heart in integrating
our management systems -- which will augment service for all users.`"

Emmanuel Herve, Managing Director of BSI Hong Kong, stated: "`By
achieving PAS 99 certification for its IMS, Ribose has again
demonstrated its commitment to industry-leading corporate governance.
The certified efficiency of its management systems allows Ribose to
focus its resources on enhancing its platform, and delivering effective
solutions to users.`"

'''

== About Ribose

Ribose makes collaborating easy and fun. Whether planning business
projects or social events, the Ribose platform helps users collaborate
through world-class security certified to the highest standards,
including ISO 27001, CSA STAR and CDSA CPS. Also available as part of
the UK Government's G-Cloud program, Ribose is free to use:
http://www.ribose.com./[http://www.ribose.com].

== About BSI

The British Standards Institution is the business standards company that
helps businesses turn best practices of into habits of excellence. As
the world's first national standards body and a founding member of ISO,
BSI is an organization whose standards inspire excellence across the
globe: http://www.bsigroup.com

---

Originally published at:

* http://www.prnewswire.com/news-releases/ribose-awarded-pas-99-certification-for-integrated-management-systems-263422351.html[PRNewswire: Ribose awarded PAS 99 certification for integrated management systems]
* http://www.prnewswire.co.uk/news-releases/ribose-awarded-pas-99-certification-for-integrated-management-systems-263422081.html[PRNewswire UK: Ribose awarded PAS 99 certification for integrated management systems]
* http://hk.prnasia.com/story/99260-2.shtml[PRNewswire HK: Ribose 榮獲 PAS 99 整合管理體系認證 -- 體現國際級公司治理與合規管理水平]
* http://www.prnasia.com/story/99259-1.shtml[PRNewswire CN: Ribose 荣获 PAS 99 整合管理体系认证]

