---
layout: post
title: "Ribose Wins Red Herring Asia Top 100 Asia Award"
date: 2015-09-22 16:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose Wins Red Herring Asia Top 100 Asia Award
---
= Ribose Wins Red Herring Asia Top 100 Asia Award

*First secure cloud collaboration company chosen for prestigious technology recognition*

Hong Kong -- 21 September 2015 -- Cloud collaboration platform provider
Ribose has been named a winner of the
http://www.redherring.com/events/red-herring-asia/[Red Herring 2015 Top
100 Asia] Award. Ribose is the first secure cloud collaboration company
to be included in global media conglomerate Red Herring's annual lineup
of rising stars in the technology world.

Red Herring's Top 100 Asia is a prestigious recognition for the region's
most promising private technology ventures. The list has become a mark
of distinction for up-and-coming companies and entrepreneurs, and Ribose
joins prominent previous Top 100 winners including Google, Facebook,
Kakao, Twitter, Rakuten, Salesforce.com, Xiaomi and YouTube.

Ribose's award-winning cloud collaboration platform democratizes
collaboration technology -- previously only affordable to large
enterprises and government organizations -- by putting world-class
security and technology into the hands of all users. Capturing the
attention of the technology and business worlds, Ribose has been
featured in Fortune and TechTarget.

Accessible anywhere, offering enterprise-level service dependability,
and complying with international governance and security standards -- the
Ribose platform gives users peace of mind to focus on their tasks at
hand. Advocating a 'highest-bar' approach to cloud security, Ribose
provides the world's most stringent specified security requirements for
all users, absolutely free of charge.

Choosing from a pool of hundreds of companies across Asia each year, the
Red Herring editorial team selects the most innovative candidates for
further assessment. Nominees are evaluated on both quantitative and
qualitative criteria including financial performance, technological
innovation, quality of management, execution of strategy and integration
into their respective industries. Ribose was named a winner after
presenting its secure cloud collaboration platform to judges at the Red
Herring Asia Forum held in Manila on 14-16 September 2015.

"`Choosing the companies with the strongest potential was by no means a
small feat,`" said Alex Vieux, publisher and CEO of Red Herring. "`After
rigorous contemplation and discussion, we narrowed our list down from
hundreds of candidates from across Asia to the Top 100 Winners. With its
focus on cloud security, data privacy and management standards; Ribose
embodies the vision, drive and innovation that define a successful
entrepreneurial venture.`"

"`Ribose disrupted the collaboration space by democratizing
enterprise-strength cloud security and privacy for all users, which will
become increasingly important as more businesses and organizations
embrace collaboration in the cloud. We are proud to include Ribose in
Red Herring's Top 100 Asia this year, and are confident they will join
previous winners in creating a new wave of revolutionary technology,`"
commented Mr. Vieux.

According to Ribose founder Ronald Tse, "`Ribose is delighted to win Red
Herring's Top 100 Asia award. We stand humbled by the judges'
recognition of our mission to democratize cloud collaboration, our
secure platform, and the hard work and dedication of our team.`"

"`Ribose is committed to world-class security. Users often rely on our
platform to create high-value, mission-critical results involving
important intellectual property or highly confidential information, and
our dedication to meeting the world's most stringent cloud security
standards embodies our efforts to protect users' private information,`"
explained Tse.

Tse concluded, "`I'd like to thank Red Herring for putting this year's
awards together, as well as the judges for their recognition of our work
-- especially considering the impressive nominees from around the region.
On behalf of our team at Ribose, we congratulate all members of this
year's Top 100 Asia list. It is an honor to be included amongst such
distinguished company.`"

'''

== https://www.ribose.com/[About Ribose]

Ribose is a cloud collaboration platform that makes
https://www.ribose.com/features[working together easy and fun] while
https://www.ribose.com/commitments[keeping your data safe]. As the
world's first cloud service provider certified to
https://www.imda.gov.sg/regulations-licensing-and-consultations/ict-standards-and-quality-of-service/it-standards-and-frameworks/mtcs-certification-scheme[MTCS
(Multi-Tier Cloud Security)],
https://cloudsecurityalliance.org/star/attestation/[CSA STAR
Attestation], https://cloudsecurityalliance.org/star/certification/[CSA
STAR Certification]
(https://cloudsecurityalliance.org/research/ccm/[Cloud Controls Matrix,
CCM 3.0.1]) and the first Software-as-a-Service platform to complete the
https://cloudsecurityalliance.org/star/c-star/[CSA C-STAR Assessment],
Ribose has been consistently awarded the industry's highest cloud
security ratings year after year: the highest security tier, Level 3, in
MTCS and the highest maturity level, Gold, in STAR Certification.

This year, Ribose won two http://www.stevieawards.com/[Gold Stevie®
Awards] at the 2015 http://www.stevieawards.com/iba/[International
Business Awards], where it was named _Most Innovative Company in Asia_
and also _Best New Collaboration Service_; and was also named _Best
Cloud Collaboration Platform_ at the 2015
http://www.corp-vis.com/awards/top-tech-awards/[Technology Innovator
Awards] hosted by http://www.corp-vis.com/[Corporate Vision Magazine].

Ribose is also certified to http://www.iso.org/iso/iso_9000[ISO 9001],
http://www.iso.org/iso/home/standards/management-standards/iso14000.htm[ISO
14001],
http://www.bsigroup.com/en-GB/ohsas-18001-occupational-health-and-safety/[OHSAS
18001], http://www.isoiec20000certification.com/[ISO/IEC 20000],
http://www.bsigroup.com/en-GB/iso-22301-business-continuity/[ISO 22301],
http://www.iso.org/iso/iso27001[ISO/IEC 27001],
http://www.iso.org/iso/home/standards/management-standards/iso50001.htm[ISO
50001], http://www.bsigroup.com/en-GB/pas-99-integrated-management/[PAS
99], https://www.cyberstreetwise.com/cyberessentials[Cyber Essentials
Plus],
https://www.mesalliance.org/communities/CDSA/production-security-guidelines/[CDSA
Content Protection Security (CPS)] and http://www.aicpa.org/soc[AICPA
Service Organization Control (SOC)] standards, and approved by the
https://www.digitalmarketplace.service.gov.uk/[UK Government's G-Cloud
program] for government use.

Ribose is free to use: https://www.ribose.com/[ribose.com].

== http://www.redherring.com/[About Red Herring]

Red Herring is a global media company which unites the world's best high
technology innovators, venture investors and business decision makers in
a variety of forums, including print, online and
exclusive http://www.redherring.com/top-100/[events] for technology
leaders around the globe. Red Herring provides an insider's access to
the global innovation economy, featuring unparalleled insights on the
emerging technologies driving the economy.

Its Red Herring 100 awards for North America, Europe, Asia and Global
have recognized more than 5,000 companies in their early stages,
including Baidu, Google, eBay and Skype.

For more information, please visit: http://www.redherring.com.

---

Originally published at: https://www.businesswire.com/news/home/20151126005007/en/Ribose-Wins-Red-Herring-Top-100-Global-Award[BusinessWire]
