---
layout: post
title: "Ribose becomes first collaboration platform to complete UK Cyber Essentials Plus"
date: 2015-05-19 16:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose becomes first collaboration platform to complete UK Cyber Essentials Plus
---
= Ribose becomes first collaboration platform to complete UK Cyber Essentials Plus

*20 May 2015 -- London / Hong Kong --* Ribose has become the world's first
collaboration platform to complete the UK Cyber Essentials Plus
assessment, a UK Government-backed and industry-supported scheme that
helps to protect businesses against cyber threats.

Launched in June 2014, Cyber Essentials was developed by
https://www.cesg.gov.uk[CESG] (the information security arm of
http://www.gchq.gov.uk[GCHQ]) and the
https://www.gov.uk/government/organisations/department-for-business-innovation-skills[Department
of Business, Innovation and Skills] in conjunction with
http://www.bsigroup.com[BSI (British Standards Institution)],
the Information Assurance for Small and Medium Enterprises (IASME)
consortium and the https://www.securityforum.org/[Information Security
Forum (ISF)]. Since October 2014, Cyber Essentials certification has
been mandatory for UK central government ICT (Information and
Communications Technology) suppliers that handle sensitive and personal
information.

A two-level program, Cyber Essentials certification is awarded upon
completion of a self-assessment questionnaire with independent
verification. Cyber Essential Plus certification is optional, and
provides a higher level of assurance through independent security
controls testing by an external certifying body, focusing on resilience
against external cyber threats.

"`Ribose is proud to be the world's first collaboration platform to
achieve both Cyber Essentials and Cyber Essential Plus certification,`"
commented Ronald Tse, founder of Ribose. "`After being awarded our Cyber
Essentials certification by IASME in August 2014, we were excited to
receive Cyber Essential Plus certification accredited by
http://www.crest-approved.org/[CREST] following an independent
assessment by Cyberis.`"

"`Cyber Essentials Plus provides independent, third-party verification of
our security systems and controls, and also demonstrates our commitment
to information security -- especially in respect of the UK market,`" Tse
explained.

According to Geoff Jones, Director of Cyberis, "Cyberis is pleased to
award a successful pass certificate to Ribose under the
http://www.crest-approved.org/industry-government/cyber-essentials/[CREST
Cyber Essentials Plus scheme]. This shows a clear commitment to
information security within Ribose, and demonstrates fundamental
technical security controls are in place to help defend against
Internet-borne threats."
