---
layout: post
title: "Ribose Wins Red Herring Top 100 Global Award"
date: 2015-11-26 16:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose Wins Red Herring Top 100 Global Award
---
= Ribose Wins Red Herring Top 100 Global Award

*Joins prestigious list of global technology innovators with its secure cloud collaboration platform*

[Hong Kong] -- 24 November 2015 -- Ribose has become the first secure
cloud collaboration company to win an exclusive
http://www.redherring.com/events/red-herring-global/[Red Herring 2015
Top 100 Global] Award, joining a prestigious list of rising technology
stars. Ribose's platform democratizes collaboration technology --
previously only affordable to large enterprises and government
organizations -- by putting world-class security and technology into the
hands of all users, absolutely free.

This year's Top 100 Global award had a particularly competitive lineup
consisting of previous winners of the Top 100 Asia, Europe and North
America awards over the past 3 years. Red Herring launched the Top 100
Global forum knowing the value of an international gathering where
entrepreneurs, financiers, and corporate executives could meet and build
meaningful relationships, both personal and professional, in a private
and intimate setting.

Red Herring's Top 100 Global is a prestigious recognition that
recognizes the most promising private technology ventures from Asia,
Europe and North America. The list has become a mark of distinction for
up-and-coming companies and entrepreneurs, and Ribose joins prominent
previous Top 100 Global alumni including Google, Facebook, Twitter,
Skype, Salesforce.com, eBay and YouTube. This global award follows
Ribose's selection as winner of Red Herring's Top 100 Asia in September
2015.

Every year, the Red Herring editorial team selects nominees for
evaluation based on a number of quantitative and qualitative factors,
including financial performance, technological innovation, quality of
management, execution of strategy and integration into their respective
industries. After presenting its secure cloud collaboration platform to
judges at the Red Herring Global Forum held in Los Angeles, California
on 17-19 November 2015, Ribose was named a winner of this year's award.

Over the past year, Ribose became the world's first cloud service
provider triple-assured by the Cloud Security Alliance (CSA), having
achieved all three of the CSA's stringent assurance programs. Moreover,
Ribose has created the world's most extensive integrated management
system certified to the PAS 99 standard, and become the first
organization outside the UK to achieve ISO 9001:2015 certification and
the world's 2^nd^ organization to receive ISO14001:2015 certification.
Working to ensure the security of users' information, the company also
received certification to ISO/IEC 27018 for cloud privacy in September.

Ribose provides the world's most stringent specified security
requirements for all users by advocating a 'highest-bar' approach to
cloud security and privacy. With its accessibility, dependability and
security, the Ribose platform gives users the peace of mind to focus on
their tasks at hand.

"`It was a challenging task to select the 'best of the best' from the
past 3 years' winners,`" said Alex Vieux, publisher and CEO of Red
Herring. "`After rigorous contemplation and discussion, we narrowed our
list down from 1,200 potential companies to 200 finalists. The top 100
companies that were chosen should be extremely proud. Ribose - with its
focus on cloud security, data privacy and management standards --
distinguished itself from an extremely competitive field through its
vision, drive and commitment to innovation.`"

"`Offering enterprise-strength collaboration technology with world-class
security to all users, completely free of charge, Ribose has shifted the
paradigm of the cloud collaboration space. Giving individuals and teams
the tools to work seamlessly together beyond the constraints of time and
physical location, Ribose has created a platform truly worthy of
inclusion in Red Herring's Top 100 Global -- thereby joining a
distinguished list of leaders and innovators in the technology
industry,`" said Anam Alpenia, Managing Director of Herring
International.

Ribose founder Ronald Tse added, "`Ribose is delighted to be named as a
Red Herring Top 100 Global company following our inclusion in Red
Herring's Top 100 Asia list in September 2015. We stand humbled
alongside the highly successful private companies at the competition
this year, and truly appreciate the judges' recognition of our mission
to democratize secure cloud collaboration and the dedication of our
team.

"`As the world becomes more globalized; people become more
interconnected; and innovation and inventions increasingly arise from
multidisciplinary work that spans the globe. By facilitating teamwork
and collaboration, Ribose is empowering entrepreneurs and inventors
around the world to work together for the benefit of future
generations,`" explained Tse.

Tse concluded, "`We'd like to thank Alex and the team at Red Herring for
their vision and foresight in identifying the world's most promising
up-and-coming technology pioneers. This award is a source of great pride
and encouragement to our team at Ribose, inspiring us to charge ahead
with our mission of bringing world-class, highly secure collaboration
technology to all of our users.`"

