---
layout: post
title: "Ribose achieves world's most extensive integrated management system compliant to PAS 99: Certified integration of seven management systems"
date: 2015-07-07 16:00:00 
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose achieves world's most extensive integrated management system compliant to PAS 99: Certified integration of seven management systems
---
= Ribose achieves world's most extensive integrated management system compliant to PAS 99: Certified integration of seven management systems

{blank}[8 July 2015 -- Hong Kong] -- Cloud collaboration platform provider Ribose
has achieved the world's most extensive
http://www.thecqi.org/Knowledge-Hub/Resources/Factsheets/Integrated-management-systems/[integrated management system (IMS)]
certified to the
http://www.bsigroup.com/en-GB/pas-99-integrated-management/[PAS 99]
standard.

Certified by http://www.bsigroup.com[BSI (British Standards Institution)],
Ribose's IMS covers all seven of the company's management
systems, each already compliant to a separate management system standard
(MSS) including:

* http://www.iso.org/iso/iso_9000[ISO 9001:2008] Quality management
systems -- Requirements, the international standard for quality
management systems (QMS)
* http://www.iso.org/iso/home/standards/management-standards/iso14000.htm[ISO
14001:2004] Environmental management systems -- Requirements with
guidance for use, the international standard for environmental
management systems (EMS)
* http://www.bsigroup.com/en-GB/ohsas-18001-occupational-health-and-safety/[BS
OHSAS 18001:2007] Occupational health and safety management systems --
Requirements, the internationally applied British Standard for
occupational health and safety management systems (OHSMS)
* http://www.isoiec20000certification.com[ISO/IEC 20000-1:2011]
Information technology -- Service management -- Part 1: Service management
system requirements, the international standard for IT service
management systems (SMS)
* http://www.bsigroup.com/en-GB/iso-22301-business-continuity/[ISO
22301:2012] Societal security -- Business continuity management systems --
Requirements, the international standard for business continuity
management systems (BCMS)
* http://www.iso.org/iso/iso27001[ISO/IEC 27001:2013] Information
technology -- Security techniques -- Information security management
systems -- Requirements, the international standard for information
security management systems (ISMS)
* http://www.iso.org/iso/home/standards/management-standards/iso50001.htm[ISO
50001:2011] Energy management systems -- Requirements with guidance for
use, the international standard for energy management systems (EnMS)

PAS 99 is the world's first framework for integrating management systems
built on different management systems standards (MSS), specifying
requirements for streamlining MSSs, allowing for improved business
focus, a more universal approach to risk mitigation and improved
operational efficiency.

Created to align with the http://www.iso.org/directives[ISO Directive
Annex SL], the PAS 99:2012 standard goes a step further by ensuring the
results of streamlining management systems work effectively and as
intended. At present, PAS 99 certification is the only impartial way to
determine if an IMS has achieved its intention of integrating operating
systems efficiently and effectively, providing a common bar on how an
integrated management system should function and continuously improve
through certification.

According to Ribose's founder Ronald Tse, "`Ribose chose to build a
streamlined, integrated management system right from the beginning. As a
small company with a limited number of staff, we wanted to manage all
aspects of the company as efficiently as possible. Streamlining our IMS
through PAS 99 certification helped us avoid overlapping elements and
duplicated effort across our different management systems.`"

"`Taking our commitment to holistic, comprehensive collaboration to
heart, we have integrated our information security, business continuity,
quality, IT services, environmental, energy and occupational health and
safety management systems into a whole -- allowing us to effectively
manage these aspects of our operations without the typical overhead that
can bog down non-integrated systems,`" explained Mr. Tse. "`Our highly
dynamic information security management system, which has continuously
received the highest security ratings and certified to the most
stringent security standards including CSA STAR, CSA C-STAR, MTCS and
AICPA SOC, also operates as part of this IMS.`"

Mr. Tse concluded, "`PAS 99 certification confirms that Ribose has
integrated its management systems correctly, and that the IMS performs
effectively -- providing better oversight and control for our management
team, while ensuring the highest level of service for our users.`"

Emmanuel Herve, Managing Director of BSI Hong Kong and VP of Standards,
remarked, "`We commend Ribose for its commitment to the highest levels of
corporate governance. Standards are designed to level the playing field,
and Ribose's numerous achievements in certification attest that smaller
businesses can indeed compete against larger organizations by building
upon standards.`"

Mr. Herve added, "`Management systems help companies get more from their
business, and integrating these management systems allows them to
realize even greater benefits without additional investment of time or
money. PAS 99 provides a framework for the most streamlined method to
achieve this goal. We congratulate Ribose on being the first company to
integrate seven management systems under PAS 99, setting a strong
example for the industry to follow.`"
