---
layout: post
title: "Ribose Wins Red Herring Asia Top 100 Asia Award"
date: 2015-09-22 16:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose Wins Red Herring Asia Top 100 Asia Award
---
= Ribose Wins Red Herring Asia Top 100 Asia Award

*First secure cloud collaboration company chosen for prestigious technology recognition*

Hong Kong -- 21 September 2015 -- Cloud collaboration platform provider
Ribose has been named a winner of the
http://www.redherring.com/events/red-herring-asia/[Red Herring 2015 Top
100 Asia] Award. Ribose is the first secure cloud collaboration company
to be included in global media conglomerate Red Herring's annual lineup
of rising stars in the technology world.

Red Herring's Top 100 Asia is a prestigious recognition for the region's
most promising private technology ventures. The list has become a mark
of distinction for up-and-coming companies and entrepreneurs, and Ribose
joins prominent previous Top 100 winners including Google, Facebook,
Kakao, Twitter, Rakuten, Salesforce.com, Xiaomi and YouTube.

Ribose's award-winning cloud collaboration platform democratizes
collaboration technology -- previously only affordable to large
enterprises and government organizations -- by putting world-class
security and technology into the hands of all users. Capturing the
attention of the technology and business worlds, Ribose has been
featured in Fortune and TechTarget.

Accessible anywhere, offering enterprise-level service dependability,
and complying with international governance and security standards -- the
Ribose platform gives users peace of mind to focus on their tasks at
hand. Advocating a 'highest-bar' approach to cloud security, Ribose
provides the world's most stringent specified security requirements for
all users, absolutely free of charge.

Choosing from a pool of hundreds of companies across Asia each year, the
Red Herring editorial team selects the most innovative candidates for
further assessment. Nominees are evaluated on both quantitative and
qualitative criteria including financial performance, technological
innovation, quality of management, execution of strategy and integration
into their respective industries. Ribose was named a winner after
presenting its secure cloud collaboration platform to judges at the Red
Herring Asia Forum held in Manila on 14-16 September 2015.

"`Choosing the companies with the strongest potential was by no means a
small feat,`" said Alex Vieux, publisher and CEO of Red Herring. "`After
rigorous contemplation and discussion, we narrowed our list down from
hundreds of candidates from across Asia to the Top 100 Winners. With its
focus on cloud security, data privacy and management standards; Ribose
embodies the vision, drive and innovation that define a successful
entrepreneurial venture.`"

"`Ribose disrupted the collaboration space by democratizing
enterprise-strength cloud security and privacy for all users, which will
become increasingly important as more businesses and organizations
embrace collaboration in the cloud. We are proud to include Ribose in
Red Herring's Top 100 Asia this year, and are confident they will join
previous winners in creating a new wave of revolutionary technology,`"
commented Mr. Vieux.

According to Ribose founder Ronald Tse, "`Ribose is delighted to win Red
Herring's Top 100 Asia award. We stand humbled by the judges'
recognition of our mission to democratize cloud collaboration, our
secure platform, and the hard work and dedication of our team.`"

"`Ribose is committed to world-class security. Users often rely on our
platform to create high-value, mission-critical results involving
important intellectual property or highly confidential information, and
our dedication to meeting the world's most stringent cloud security
standards embodies our efforts to protect users' private information,`"
explained Tse.

Tse concluded, "`I'd like to thank Red Herring for putting this year's
awards together, as well as the judges for their recognition of our work
-- especially considering the impressive nominees from around the region.
On behalf of our team at Ribose, we congratulate all members of this
year's Top 100 Asia list. It is an honor to be included amongst such
distinguished company.`"

