---
layout: post
title: "Ribose named Best New Collaboration Service, Best New Social Business Solution and  Best Social Collaboration App at 2016 International Business Awards"
date: 2016-09-28 00:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose named Best New Collaboration Service, Best New Social Business Solution and  Best Social Collaboration App at 2016 International Business Awards
---
= Ribose named Best New Collaboration Service, Best New Social Business Solution and  Best Social Collaboration App at 2016 International Business Awards

*Company wins three Gold Stevie(R) Awards in world's premier business awards program*

[Hong Kong] -- 28 September 2016 -- Ribose has won three Gold Stevie(R)
Awards in the "Best New Product or Service of the Year -- Software
Collaboration/Social Networking Solution", "Best New Product or Service
of the Year - Software - Social Business Solution" and "Best Social
Mobile App" categories, as well as a Bronze Stevie(R) Award for "Best New
Product or Service of the Year - Software - Security Solution" at The
http://stevieawards.com/iba[13^th^ Annual International Business
Awards].

http://stevieawards.com/iba[The International Business Awards], or
"Stevies", are the world's premier business awards program recognizing
the most respected individuals and commercial organizations around the
world. The 2016 IBAs attracted more than 3,800 nominations from over 60
nations and territories -- representing a wide range of public and
private, profit and non-profit, small and large organizations from
virtually every industry.

Ribose provides a unique and secure cloud collaboration platform that
helps users work together effectively, while protecting their
highly-valuable collaborative data through pioneering cloud security and
privacy -- delivered through an intuitive user experience expected in
today's consumer software. The platform adopts the world's most
stringent specified security requirements by advocating a 'highest-bar'
approach to cloud security and privacy. With its accessibility,
dependability and security, the Ribose platform gives users the peace of
mind to focus on their tasks at hand.

Ribose founder Ronald Tse commented, "Ribose is delighted to improve
on last year's results at the 13^th^ Annual International Business
Awards -- winning
http://stevieawards.com/iba/2016-stevie-award-winners[three Gold Stevie
Awards] in the extremely competitive Best New Collaboration Service,
Best New Social Business Service and Best Social Mobile App categories.
We are also pleased to win a Bronze Stevie Award for Best New Security
Solution in a very strong field of competitors. These awards stand as
proof that our mission of democratizing secure collaboration with a
'highest bar' approach resonates with our users and judges alike,
helping us make working together easy and fun -- while protecting users'
data with the highest, internationally certified levels of security."

He continued, "We are both humbled and flattered by the judging
panel's recognition of our work, and I'd like to congratulate all of
this year's IBA winners and nominees for sharing their experiences and
success stories from around the world. It's always been a source of
pride for our team at Ribose to be recognized amongst some of the
leading names in international business."

http://stevieawards.com/iba/2016-stevie-award-winners[Stevie Award
winners] were determined by the average scores of more than 200
executives worldwide who participated in the judging process from May
through early August.

In awarding Ribose the Gold Stevie for Best Social Collaboration App,
judges commended Ribose for "being social but at the same time highly
protected in a cloud based platform" and for "practical and strong use
of technology to enable greater globalization and digitization."

Judges who selected Ribose for the Gold Stevie in the Best
Collaboration / Social Networking Solution category called it "a great
example of customer engagement and involvement in business operations"
and "definitely a company to watch out for," praising Ribose for
offering a "clever new angle on secured collaboration." Scoring the
submission for Best Social Business Solution, the panel highlighted
Ribose's "world class cloud platform" and "exceptional security
features", backed by "numerous international awards and certifications."

IBA judges also presented Ribose with a Bronze Stevie Award for Best New
Product or Service of the Year - Software - Security Solution,
commenting, "Ribose empowers customers to devote their full energy to
developing their business, while leaving security in their capable
hands. It is a true enabler to many industries."

"We are delighted to congratulate Ribose on winning three Gold and one
Bronze Stevies at the 13^th^ Annual International Business Awards.
Building on their remarkably successful debut last year, Ribose has
continued to demonstrate its passion and commitment to excellence in
secure cloud computing -- taking home an impressive four Stevie Awards
this year," remarked Michael Gallagher, president and founder of the
Stevie Awards.

Details about The International Business Awards and the lists of Stevie
Award winners are available at
http://www.stevieawards.com/IBA[www.StevieAwards.com/IBA].
