---
layout: post
title: "Ribose wins Security Innovation of the Year by Cloud Security Alliance APAC"
date: 2016-01-20 16:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose wins Security Innovation of the Year by Cloud Security Alliance APAC
---
= Ribose wins Security Innovation of the Year by Cloud Security Alliance APAC

[Hong Kong] -- 21 January 2016 -- Ribose has been named Security
Innovation of the Year by the Cloud Security Alliance (CSA), the premier
organization for the cloud security industry.

Ribose received the award at the CSA APAC Inaugural Awards Ceremony on 3
December 2015 in Guangzhou, China after careful appraisal of
professionalism, excellence, innovation and measurable success by the
judging committee. The prestigious award recognizes the very best in the
technology industry, rewarding industry-leading organizations for
innovation and performance in the cloud sector. Ribose was named
Security Innovation of the Year alongside Trend Micro and DBApp
Security, recognizing its genuinely innovative approach to cloud
security.

Ribose is actively involved with the CSA on cloud security matters, with
Ribose founder Ronald Tse a member of its International Standardization
Council -- which develops international standards relating to cloud
security with multiple partners including the ISO/IEC JTC1 SC27, the
group that created the ISO/IEC 27001 international standard for
Information Security Management Systems. Since joining the CSA in 2013,
Ribose has participated in multiple CSA research programs to promote and
develop improved cloud security practices for both users and providers.

As a result, Ribose holds numerous cloud security "`firsts`" and heavily
participates in multi-jurisdictional cloud security programs, believing
the practice should be an industry standard as Cloud Security Providers
(CSPs) must ensure the security of users' data across geopolitical and
regulatory borders.

A pioneer in cloud security, Ribose was the first CSP to adopt and
promote CSA's CCM 3 control framework, and the world's first CSP
simultaneously certified to all three of CSA's cloud security assessment
schemes: STAR Certification to the highest Gold maturity level, STAR
Attestation and C-STAR Assessment. Ribose was the first organization
worldwide to achieve CSA STAR Attestation and STAR Certification using
CCM 3.0 and CCM 3.0.1; as well as the first Software-as-a-Service (SaaS)
to achieve STAR Certification and C-STAR Assessment.

According to Jim Reavis, CEO and co-founder of the CSA, "`We first
invited Ribose to join CSA having seen their dedication to providing the
best security protection to their users. As pioneers in cloud security,
Ribose is leading the industry in pursuing security assurance for its
users, and became the world's first organization simultaneously
certified to all three of CSA's cloud security assessment schemes: STAR
Certification, STAR Attestation and C-STAR Assessment. In naming Ribose
as Security Innovation of the Year, we are recognizing its dedication to
providing the highest level of security protection for users and its
commitment to benefitting the entire cloud security industry through its
work with the CSA.`"

"`Ribose serves as a leading example for CSPs in Asia, setting best
practices in user security and privacy,`" said Aloysius Cheang, Managing
Director APAC and Standards Secretariat of the CSA International
Standardization Council. "`Asia is fast rising as the next hub of
innovation in the technology space, and certified world-class
organizations like Ribose are leading the charge. By using CCM
extensively, and assisting in its development, Ribose has pioneered a
high bar approach to cloud security -- adopting a streamlined process
that provides robust protection for all users.`"

"`Winning this recognition is a high honor for Ribose, as we work closely
with many industry bodies like the CSA -- the authority on cloud
security. We are thrilled to win this honor, which stands as an external
testament to our deep commitment to cloud security and the effectiveness
of our approach and implementation,`" explained Ronald Tse, founder of
Ribose.

Tse continued, "`CSA is the de-facto cloud security industry body, and
their research has strongly influenced the cloud security industry as
well as the most -- if not all -- cloud security standards used around the
world today. As a corporate member of the CSA and a leader in cloud
security, we strongly support the CSA's work and have helped them to
develop and drive industry standards, thereby improving confidence for
both cloud providers and users around the globe.`"

"`As a collaboration platform, Ribose depends on the highest levels of
cloud security to protect our users' intellectual property. Knowing that
their work is protected by award-winning, internationally certified
levels of security gives our users the peace of mind to focus on their
tasks at hand,`" Tse concluded.
