---
layout: post
title: "Ribose wins Six Gold, Silver and Bronze Stevie(R) Awards at 2018 International Business Awards(R)"
date: 2018-08-22 11:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose wins Six Gold, Silver and Bronze Stevie(R) Awards at 2018 International Business Awards(R)
---
= Ribose wins Six Gold, Silver and Bronze Stevie(R) Awards at 2018 International Business Awards(R)

*Recognized for Wide-Ranging Asymmetric Security Solutions and Metanorma Publishing Technology*

{blank}[22 August 2018 -- Hong Kong]

http://www.ribose.com[Ribose] has won four Gold Stevie Awards for
"`Best New Semantic Technology Platform, Tools and Applications`",
"`Best New International Data Protection Solution`",
"`Best New Collaboration/Social Networking Solution`" and "`Best New
Scholarly Publishing Information Solution`" categories, as well as
a Silver Stevie for "`Most Innovative Tech Company of the Year - Up
to 100 Employees`" and a Bronze Stevie for "`Technical Innovation
of the Year - At Organizations With Up to 100 Employees`" at The 15th
Annual International Business Awards.

// [quote]
// Ribose wins Six Stevie Awards at 2018 International Business Awards
// for cutting-edge asymmetric security and technical publishing innovations

The International Business Awards are the world's premier business
awards program, where all individuals and organizations worldwide
are eligible to submit nominations. The 2018 IBAs received more than
3,900 entries from 74 nations and territories, from organizations
of all sizes and in virtually every industry.

Ribose provides asymmetric security solutions and technologies that
empower productivity in security-sensitive environments.

Its focus on cybersecurity has been recognized for a number of achievements,
including its one-of-a-kind geolocation services for organizations
with data sovereignty concerns, as well as extended "`Zero-Knowledge
Collaboration`" technology featuring enhanced elliptic-curve cryptography.

Other Ribose innovations include the "`Engyon`" secure document scheme
that allows data elements to be individually encrypted and digitally-signed
while supporting hierarchical security levels. The result is a standalone,
"`blockchain in a file`" secure document that can be transmitted through
traditional channels like email.

Ribose also won recognition for conceiving and developing "`Metanorma`"
-- a standard for standards documents -- for use by international standardization
bodies such as CalConnect and ISO to achieve an end-to-end, author-to-print
workflow.

Ribose founder Ronald Tse commented, "`Ribose is delighted to receive
such high recognition in the 15th Annual International Business Awards,
winning four Gold Stevie Awards for 'Best New Product or Service of
the Year' -- as well as a Silver Stevie Award for 'Most Innovative
Tech Company of the Year' and a Bronze Stevie Award for 'Technical
Innovation of the Year'. Winning awards in these highly competitive
categories stands as solid testament to our commitment to asymmetric
security solutions and standard advancement.`"

He continued, "`I'd like to congratulate all 2018 IBA winners and
nominees for sharing their success stories from around the world.
It's always been a source of pride for our team at Ribose to be recognized
amongst some of the leading names in international business; we are
both humbled and flattered by this year's results.`"

Stevie Award winners were determined by the average scores of more
than 270 executives worldwide who participated on 12 juries.

Judges commended Ribose for creating a "`scalable, socio-centric,
highly productive and trusted product with top notch security certified
by highly qualified and recognized organizations.`" They also noted
Ribose's "`innovation on multiple fronts with Engyon secure document
technology, data sovereignty and extended cloud security.`"

Judges praised Engyon's use of blockchain-like technology to create
secure, sharable documents -- with one commenting, "`Using blockchain
to secure collaboration is brilliant!`" and another saying "`The idea
of a standalone, but secure, document that can be transmitted through
traditional channels such as email is simply outstanding.`"

This year's IBA judges also lauded Ribose's development of Metanorma
as a "`revolutionary concept`", noting that, "`Setting standards for
standardization is a very important requirement. This is a great initiative.`"
Another judge remarked, "`To anyone who has to administrate such standards,
this [Metanorma] will seem like a godsend.`"

"`This year's Stevie Award winners are the most distinguished group
of winners we've had yet,`" said Michael Gallagher, president and
founder of the Stevie Awards. "`Ribose should be especially proud
of their achievement, as we raised the minimum scoring requirements
for the 2018 IBAs in light of an increasingly impressive pool of global
nominations. Taking home six Stevie(R) Awards this year is solid proof
that Ribose stands at the forefront of cyber security and international
standards.`"

Details about The International Business Awards and lists of award
winners are available at www.StevieAwards.com/IBA.

