---
layout: post
title: "Ribose Achieves World's First NIST Cybersecurity Framework Certification by BSI"
date: 2018-08-08 11:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose Achieves World's First NIST Cybersecurity Framework Certification by BSI
---
= Ribose Achieves World's First NIST Cybersecurity Framework Certification by BSI

*Verified compliance to NIST Cybersecurity Framework at Tier 4 (Adaptive)*

{blank}[08 August 2018 -- Hong Kong]

http://www.ribose.com[Ribose] has become the world's first organization
to certify to the NIST Cybersecurity Framework (Tier 4) by BSI.

// [quote]
// Ribose world's first certification to NIST Cybersecurity Framework

The National Institute of Standards and Technology's (NIST) Cybersecurity
Framework (CSF) was mandated by U.S. Executive Order (EO) 13636, and
was designed to protect critical infrastructure and vital industries
from cyberattacks. It also allows organizations to select a "`Tier`"
based on organizational practices -- from Tier 1 (Partial) to Tier
4 (Adaptive) -- indicating a progressive approach from informal and
reactive, to agile and risk-driven.

BSI was part of the team of experts that worked with NIST to develop
the CSF, and is the first certification body to offer certification
to the CSF. The program validates processes and evidence corresponding
to the chosen tier level, and is integrated with ISO/IEC 27001, which
comprehensively validates information security and risk management
practices.

John DiMaria, Global Product Champion for Information Security and
Business Continuity for BSI, said, "`BSI has created the world's first
certification on the NIST Cybersecurity Framework. The unique tiered
concept combines solid information security principles with application
flexibility, which will be valued by organizations worldwide. We congratulate
Ribose on being the first organization to receive our NIST CSF certification
at Tier 4, and commend its long-standing commitment to international
harmonization of cybersecurity providing the highest levels of data
protection.`"

Enoch Lee, General Manager of Hong Kong for BSI, added, "`BSI has
long been recognized as a pioneer in information security management.
The new NIST Cybersecurity Framework certification program is a key
component of our efforts to maintain this leadership position.`"

According to Ronald Tse, founder of Ribose, "`Achieving NIST CSF certification
at Tier 4 reaffirms our unwavering commitment to protecting our customers'
data based on verifiable cybersecurity. Our approach builds upon a
solid security foundation that includes the selective Kitemark for
Secure Digital Transactions certification, as well as cloud security
and privacy certification through ISO/IEC 27017 and ISO/IEC 27018.`"


---
== About Ribose

Ribose is the award-winning developer of asymmetric security™ technologies
trusted by industries with heightened cybersecurity needs. Having
pioneered the comprehensive approach to verifiable cybersecurity,
Ribose is a Deloitte Technology FAST 20 and
https://www.redherring.com/[Red Herring Top 100 Global] company, and
received the CSA APAC Enterprise Award and several
https://stevieawards.com/iba/[Stevie(R) Awards]
for cybersecurity innovations.

Ribose is the only cloud service provider (CSP)
https://cloudsecurityalliance.org/star/levels/[triple-assured by the
Cloud Security Alliance],
the first CSP to receive
https://www.bsigroup.com/en-GB/our-services/product-certification/kitemark/Kitemark-schemes-for-service-providers/kitemark-certification-for-secure-digital-banking/[BSI's Kitemark for Secure Digital Transactions],
and the first to achieve certification to the highest security tiers in
https://www.nist.gov/cyberframework[NIST CSF] and
https://www.imda.gov.sg/[MTCS]. It is also certified to
https://www.iso.org/iso-14001-environmental-management.html[ISO 14001],
https://www.isoiec20000certification.com/[ISO/IEC 20000],
https://www.iso.org/standard/50038.html[ISO 22301],
https://www.iso.org/isoiec-27001-information-security.html[ISO/IEC 27001],
https://www.iso.org/standard/43757.html[ISO/IEC 27017],
https://www.iso.org/standard/61498.html[ISO/IEC 27018] and
https://www.iso.org/iso-45001-occupational-health-and-safety.html[ISO 45001].

Learn more at: https://www.ribose.com/[ribose.com].


== About BSI

BSI (British Standards Institution) equips businesses with the necessary
solutions to turn standards of best practice into habits of excellence.
As the world's first National Standards Body and a founding member
of the
https://www.iso.org/home.html[International Organization for Standardization (ISO)],
BSI is responsible for originating many of the world's most commonly
used management systems standards.

Learn more at: https://www.bsigroup.com/[bsigroup.com].

---

Originally published at link:https://www.businesswire.com/news/home/20180808005018/en/[BusinessWire].
