---
layout: post
title: "Ribose becomes first organization in Asia to achieve ISO 45001 certification"
date: 2018-08-09 14:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose becomes first organization in Asia to achieve ISO 45001 certification
---
= Ribose becomes first organization in Asia to achieve ISO 45001 certification

*Certified to newest international standard for health and safety management*

{blank}[August 09, 2018 - Hong Kong & London]

Secure cloud provider http://www.ribose.com[Ribose] has become the first
organization in Asia and one of the first organizations in the world to achieve
https://www.iso.org/standard/63787.html[ISO 45001:2018] certification by
https://www.bsigroup.com[BSI].

// [quote]
// Ribose is first in Asia to achieve ISO 45001 certification, the international
// standard for health and safety management, by BSI

ISO 45001:2018 is the newly released international occupational health and
safety management system standard. It is the successor to
https://www.bsigroup.com/en-GB/ohsas-18001-occupational-health-and-safety/Certification-for-BS-OHSAS-18001/[OHSAS 18001],
published 19 years ago.

Ribose's certification was awarded by BSI (British Standards Institution), one
of the first wave of certification bodies to be awarded global accreditation by
the https://anab.ansi.org[ANSI-ASQ National Accreditation Board (ANAB)] for
ISO 45001:2018. BSI initially issued a "confirmation of compliance" letter
confirming Ribose's compliance with ISO 45001 on 30 March 2018.

Previously, Ribose operated an OHSAS 18001 compliant management system, which
has now been upgraded to comply with ISO 45001.

ISO 45001 differs from OHSAS 18001 in adopting ISO's High-Level Structure (HLS)
management system framework, described in Annex SL. Annex SL, which is also used
by other management systems including ISO 9001 and ISO/IEC 27001, aligns
management systems processes and therefore simplifies integration. ISO 45001
also covers a wider scope than OHSAS 18001, with stakeholders including all
internal or external parties who are directly or indirectly affected by the
organization's health and safety management issues.

According to Enoch Lee, General Manager of Hong Kong for BSI, "BSI has always
been a proponent of health and safety management, having established the
original BS OHSAS 18001 standard. Wellness and safety considerations apply to
all industries, including office-based working environments. As the first
organization in Asia to achieve ISO 45001 certification, Ribose is clearly
demonstrating its commitment to maintaining the highest international standards
of health and safety."

Ronald Tse, Founder of Ribose, commented, "At Ribose, our staff are the core of
our company, and their wellbeing is our top priority. Achieving ISO 45001
certification stands as testament that our health and safety practices meet
international best practices, and helps to ensure the wellbeing of our staff,
partners and customers."
