---
layout: post
title: "Ribose Wins Two Gold and One Silver Stevie® Awards at 2019 International Business Awards(R)"
date: 2019-09-23 11:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose Wins Two Gold and One Silver Stevie® Awards at 2019 International Business Awards(R)
---
= Ribose Wins Two Gold and One Silver Stevie® Awards at 2019 International Business Awards(R)

*Recognized for Security Solutions, Metanorma Publishing Technology and Innovation in Standards*

{blank}[September 23, 2019 - Hong Kong]

http://www.ribose.com[Ribose]
has won two Gold Stevie Awards for "International Data Protection Solution" and
"Semantic Technology Platform, Tools and Applications", as well as a Silver
Stevie Award for "Most Innovative Tech Company of the Year - Up to 100
Employees" at the
https://stevieawards.com/iba[16th Annual International Business Awards].

"Ribose should be especially proud of their achievements in this year's
International Business Awards, which stand as testament to their leadership in
cybersecurity and their equally impressive innovations in international
standards." Tweet this The International Business Awards are the world's premier
business awards program, where all individuals and organizations worldwide are
eligible to submit nominations. The 2019 IBAs received more than 4,000 entries
from 74 nations, from organizations of all sizes and in virtually every
industry.

Ribose provides asymmetric security solutions and technologies that empower
productivity in security-sensitive environments. In line with its focus on
cybersecurity, Ribose is the world's only Cloud Service Provider (CSP)
triple-assured by CSA and security-tested by UK CESG. Certified to NIST CFS Tier
4, MTCS Level 3 and ISO/IEC 27017, Ribose's platform has also received the BSI
Kitemark for Secure Digital Transactions. Its one-of-a-kind data geolocation
services (certified to ISO/IEC 27018) cater to organizations with data
sovereignty concerns, while also catering to data privacy concerns through
end-to-end encrypted collaboration technology featuring elliptic-curve
cryptography.

Ribose was also recognized for its work in advancing innovation in international
standards. In 2018, Ribose was named the official Registration Authority of the
ISO Geodetic Registry, which allows coordinates to be translated between
different GNSS systems. This year, it followed up by launching
"https://www.geolexica.org[Geolexica]", the official multi-lingual terminology
database for ISO/TC 211, which provides geographic information terminology in 14
languages.

Judges lauded Ribose for its contributions to one of the world's most important
standards, ISO 8601-1 and ISO 8601-2 -- the International Standard for the
representation of date and time -- used by every computing device in existence
today. They also noted its leadership in creating standards for physical and
postal addresses (ISO 19160-6), transcription system codes (ISO 24229), concepts
of date and time (ISO 34000), as well as calendar codes (ISO 34300).

Ribose also won praise for conceiving and developing "Metanorma" -- a
standardization framework for standards documents -- for use by international
standardization bodies to achieve an end-to-end, author-to-print workflow.
Enabling SMART standards (Standards that are Machine-Accessible, Readable and
Transferrable), Metanorma has gained rapid adoption across the international
standardization community, including CalConnect, Open Geospatial Consortium, ITU
and the Cloud Security Alliance, as well as authors in IETF, ISO and IEC.

Ribose founder Ronald Tse commented, "Ribose is both honored and humbled to
receive such high recognition at the 16th Annual International Business Awards.
Winning two Gold Stevie Awards for 'International Data Protection Solution' and
'Semantic Technology Platform, Tools and Applications' -- as well as a Silver
Stevie Award for 'Most Innovative Tech Company of the Year' -- stands as strong
testament to our cutting-edge work in security and standards."

He continued, "On behalf of the team at Ribose, I'd like to congratulate all the
2019 IBA winners and nominees for continually striving to reach new levels of
excellence. This year's competition was definitely the toughest we've seen so
far, and we are proud to have achieved these results against such a
distinguished field of business and technology leaders."

Stevie Award winners were determined by the average scores of more than 250
executives worldwide who participated on 12 juries.

Commenting on Ribose's Gold award-winning 'Semantic Technology Platform, Tools
and Applications' submission, judges noted, "When it comes to business
objective, Metanorma truly shows the purpose of its strategy," and, "The product
creates immense value for organizational use cases where standards need to be
collaborated upon and also tracked." Another remarked, "This is a really
powerful solution to a significant problem across industries. Great to see
ongoing innovation here."

Judges' comments on Ribose's 'International Data Protection Solution' entry,
another Gold award-winning submission, called it "One of the best data
protection solutions," pointing out that "features like single data element
encryption and digital signatures are impressive."

Ribose's Silver award-winning 'Most Innovative Tech Company of the Year' entry
also drew praise from the judging panel, who commended the company for its
"great technology, and you can imagine how widely it can be spread and how much
time it can save." Another judge lauded Ribose as "absolutely the best way to
secure service using a cloud platform."

"The competition at this year's Stevie Awards winners was the most dynamic we've
seen to date," said Maggie Gallagher, President of the Stevie Awards. "Ribose
should be especially proud of their achievements in this year's International
Business Awards, which stand as testament to their leadership in cybersecurity
and their equally impressive innovations in international standards."

Details about The International Business Awards and lists of award winners are
available at https://www.StevieAwards.com/IBA[www.StevieAwards.com/IBA].

