---
layout: post
title: "Ribose Completes First Transition Assessment to ISO/IEC 27001:2022 Conformance with BSI Pacific Limited"
date: 2022-12-02 00:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose Completes First Transition Assessment to ISO/IEC 27001:2022 Conformance with BSI Pacific Limited
---
= Ribose Completes First Transition Assessment to ISO/IEC 27001:2022 Conformance with BSI Pacific Limited

{blank}[2 December 2022 -- London, UK]

http://www.ribose.com[Ribose] has completed the first verified transition
assessment with https://www.bsigroup.com/en-HK/[BSI Pacific Limited] towards
https://www.iso.org/contents/news/2022/10/new-iso-iec-27001.html[ISO/IEC 27001:2022],
the third edition of the international standard for information security
management systems.

https://www.iso.org/standard/82875.html[ISO/IEC 27001:2022] is the latest
iteration of the information security management system standard that aligns
with the 93 comprehensive information security controls of
https://www.iso.org/standard/75652.html[ISO/IEC 27002:2022] organized into
organizational, people, physical and technical aspects, resulting in improved
performance in privacy protection, data leakage prevention and risk management.

Ribose completed its ISO/IEC 27001:2022 transition assessment with the issuance
of a letter of conformity by BSI on November 30, 2022. Ribose's certifications
to the previous editions,
https://www.iso.org/standard/54534.html[ISO/IEC 27001:2013] and
https://www.iso.org/standard/42103.html[ISO/IEC 27001:2005], were also awarded
by BSI, a leading conformity assessment body and the originator of the ISO/IEC
27001 standard.

"Our users are innovative leaders in their industries. With organizations today
increasingly faced with cybersecurity challenges that risks innovation, ISO/IEC
27001 helps protect our users with a holistic cyber resilience framework." noted
Ronald Tse, founder of Ribose. "By upgrading our processes early to the latest
edition of ISO/IEC 27001, our users can rest assured their data is
well-protected under our continual commitment to information security."

Michael Lam, Managing Director, Assurance Division,
https://www.bsigroup.com[BSI] APAC Region, remarked,
"Today's world increasingly operates on digital trust, which requires a laser
sharp focus on managing cybersecurity risks. As the original developer of the
ISO/IEC 27001 standard, BSI is proud to support Ribose's commitment to
world-class security in its verified transition to the latest edition of ISO/IEC
27001."
