---
layout: post
title: "Ribose Achieves World's First STAR Certification with CSA Cloud Controls Matrix v4"
date: 2022-02-08 00:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose Achieves World's First STAR Certification with CSA Cloud Controls Matrix v4
---
= Ribose Achieves World's First STAR Certification with CSA Cloud Controls Matrix v4

{blank}[8 February 2022 - London, UK; Seattle, WA]

http://www.ribose.com[Ribose]
has become the world's first cloud service provider (CSP) to achieve
https://cloudsecurityalliance.org[Cloud Security Alliance (CSA)] https://cloudsecurityalliance.org/star/[STAR Certification] using the newly released
https://cloudsecurityalliance.org/research/cloud-controls-matrix/[CSA Cloud Controls Matrix v4].

STAR Certification is the internationally recognized cloud security certification program from CSA that specifies comprehensive and stringent cloud security requirements on CSPs. The CSA Cloud Controls Matrix (CCM) is the de-facto standard for cloud security assurance and compliance, widely used in assessing cloud security performance of cloud implementations. CCM 4.0.1, the latest version of the matrix, is composed of 197 control objectives structured in 17 domains and details leading-edge cloud security practices, covering all key aspects of cloud technology.

The STAR Certification upgrade assessment was performed by BSI, a leading cloud assessment certification body, and original launch partner of the CSA STAR Certification program. Ribose's certification was granted on December 15, 2021.

"Our users are leading innovators in their industries. By achieving compliance to the latest and most comprehensive cloud security standard to date, users rest assured relying on Ribose for their success," noted Ronald Tse, founder of Ribose. "As the first organization worldwide to achieve STAR certification to CCM 3 and now CCM 4, our commitment in protecting users' information and privacy to the greatest extent is continually demonstrated."

"The CSA CCM, now in its fourth version, is recognised by many governments and industries to encompass leading edge best practices and guidance against the cyberthreats of today. We applaud Ribose's commitment to cloud security and its continual quest in providing a safe and secure environment for its users," explained Jim Reavis, CEO of CSA.

Mr. Michael Lam, Managing Director Assurance, APAC, BSI, remarked, "The landscape of cloud security shifts continuously as is the world we are living in today. In order to provide its users a secure and private way to work, Ribose has demonstrated its world-class commitment to achieving leading best practices in cloud security."

---

== About Ribose

Ribose creates asymmetric security™ and standardization technologies trusted by
industries with heightened cybersecurity needs. Having pioneered the
comprehensive approach to verifiable cybersecurity, Ribose is a Deloitte
Technology FAST 20 and http://www.redherring.com/[Red Herring Top 100 Global]
company, and received the CSA APAC Enterprise Award and several
http://www.stevieawards.com/iba/[Stevie® Awards] for its innovations.

Ribose is the first cloud service provider (CSP) to achieve certification to the
CSA CCM 4.0 and to achieve the highest security tiers in
https://www.nist.gov/cyberframework[NIST CSF] and
https://www.imda.gov.sg/regulations-and-licensing-listing/ict-standards-and-quality-of-service/IT-Standards-and-Frameworks/Compliance-and-Certification[MTCS].
It is also certified to
https://www.iso.org/iso-9001-quality-management.html[ISO 9001],
https://www.iso.org/iso-14001-environmental-management.html[ISO 14001],
https://apmg-international.com/product/iso-iec-20000[ISO/IEC 20000],
https://www.iso.org/standard/75106.html[ISO 22301],
https://www.iso.org/isoiec-27001-information-security.html[ISO/IEC 27001],
https://www.iso.org/standard/43757.html[ISO/IEC 27017],
https://www.iso.org/standard/76559.html[ISO/IEC 27018],
https://www.iso.org/standard/71670.html[ISO/IEC 27701] and
https://www.iso.org/iso-45001-occupational-health-and-safety.html[ISO 45001].

Learn more at: https://www.ribose.com/[ribose.com].

== About Cloud Security Alliance

The Cloud Security Alliance (CSA) is the world's leading organization dedicated
to defining and raising awareness of best practices to help ensure a secure
cloud computing environment. CSA harnesses the subject matter expertise of
industry practitioners, associations, governments, and its corporate and
individual members to offer cloud security-specific research, education,
training, certification, events, and products. CSA's activities, knowledge, and
extensive network benefit the entire community impacted by cloud — from
providers and customers to governments, entrepreneurs, and the assurance
industry — and provide a forum through which different parties can work together
to create and maintain a trusted cloud ecosystem. For further information, visit
us at http://www.cloudsecurityalliance.org/[www.cloudsecurityalliance.org], and
follow us on Twitter http://twitter.com/cloudsa[@cloudsa].

== About BSI

BSI (British Standards Institution) equips businesses with the necessary
solutions to turn standards of best practice into habits of excellence. As the
world's first National Standards Body and a founding member of the
https://www.iso.org/[International Organization for Standardization (ISO)], BSI
is responsible for originating many of the world's most commonly used management
systems standards.

Learn more at: https://www.bsigroup.com/[bsigroup.com].

---

Originally published at link:https://www.businesswire.com/news/home/20220220005001/en/Ribose-Achieves-World's-First-STAR-Certification-With-CSA-Cloud-Controls-Matrix-v4[BusinessWire].
