---
tags:
- bsi
- collaboration
- certification
- press release
- bs202000
- certification
permalink: blog/2022/ribose-achieves-continued-verified-compliance-to-bs-202000:2022-through-annual-assessment-program-with-bsi-pacific-limited
---
= Ribose Achieves Continued Verified Compliance to BS 202000:2022 Through Annual Assessment Program with BSI Pacific Limited
author:
  name: Ronald Tse
date: 2022-12-13 00:00:00

{blank}[13 December 2022 -- London, UK]

http://www.ribose.com[Ribose] has achieved verified compliance towards
https://www.bsigroup.com/en-GB/standards/bs-2020002020-standardization-management-system--specification/[BS
202000:2020],
the British standard for standardization management systems, through an annual
assessment program with
https://www.bsigroup.com/en-HK/[BSI Pacific Limited].

Prepared by the BSI technical committee DEF/1 Defence standardization,
https://www.bsigroup.com/en-GB/standards/bs-2020002020-standardization-management-system--specification/[BS 202000:2020]
is the world's first standard for a standardization management system, providing
a systematic and effective approach to govern usage of standards, which is
crucial to vendor and supplier confidence. BS 202000:2020 adopts a
Plan-Do-Check-Act (PDCA) cycle approach to manage the selection, adoption,
application, and deployment of standards, covering aspects such as policies,
leadership, planning, support, and operations.

Since BS 202000:2020 does not have an accredited certification program, Ribose
has implemented an annual assessment program through annual third-party
pre-assessment audits. Ribose completed its initial two-stage audit against BS
202000:2020 on 28 June 2021 with the issuance of a letter of conformity by BSI,
and completed its subsequent verification audit on 14 June 2022, also performed
by BSI.

"Standards are crucial to international trade and interoperability. Inundated by
an increasing number of international, national and industry standards,
organizations are forced to rethink their approach on the adoption and
implementation of standards," said Ronald Tse, founder of Ribose. "BS
202000:2020 is a key standard that provides an innovative and systematic
approach towards standardization that will aid organizations of any size."

Michael Lam, Managing Director, Assurance Division,
https://www.bsigroup.com[BSI] APAC Region, remarked, "BS 202000:2020 provides
best practices distilled from experiences accumulated in the defence industry,
which can greatly help guide and assist today's organizations in their adoption
of standards. BSI is delighted to support Ribose's commitment in implementing an
annual assessment program for this important British standard."

---

== About Ribose

Ribose creates asymmetric security™ and standardization technologies trusted by
industries with heightened cybersecurity needs. Having pioneered the
comprehensive approach to verifiable cybersecurity, Ribose is a Deloitte
Technology FAST 20 and http://www.redherring.com/[Red Herring Top 100 Global]
company, and received the CSA APAC Enterprise Award and several
http://www.stevieawards.com/iba/[Stevie® Awards] for its innovations.

Ribose is the first cloud service provider (CSP) to achieve certification to the
CSA CCM 4.0 and to achieve the highest security tiers in
https://www.nist.gov/cyberframework[NIST CSF] and
https://www.imda.gov.sg/regulations-and-licensing-listing/ict-standards-and-quality-of-service/IT-Standards-and-Frameworks/Compliance-and-Certification[MTCS].
It is also certified to
https://www.iso.org/iso-9001-quality-management.html[ISO 9001],
https://www.iso.org/iso-14001-environmental-management.html[ISO 14001],
https://apmg-international.com/product/iso-iec-20000[ISO/IEC 20000],
https://www.iso.org/standard/75106.html[ISO 22301],
https://www.iso.org/isoiec-27001-information-security.html[ISO/IEC 27001],
https://www.iso.org/standard/43757.html[ISO/IEC 27017],
https://www.iso.org/standard/76559.html[ISO/IEC 27018],
https://www.iso.org/standard/71670.html[ISO/IEC 27701] and
https://www.iso.org/iso-45001-occupational-health-and-safety.html[ISO 45001].

Learn more at: https://www.ribose.com/[ribose.com].

== About BSI

Since 1901, BSI is the business improvement and standards company that enables
organizations to turn standards of best practice into habits of excellence,
'inspiring trust for a more resilient world'. For over a century BSI has driven
best practice in organizations around the world. Working with over 86,000
clients across 195 countries, it is a truly global business with skills and
experience across all sectors including automotive, aerospace, built
environment, food and retail and healthcare. Through its expertise in Standards
and Knowledge, Assurance Services, Regulatory Services and Consulting Services,
BSI helps clients to improve their performance, grow sustainably, manage risk
and ultimately become more resilient.

Learn more at: https://www.bsigroup.com/[bsigroup.com].

---

Originally published at link:https://www.businesswire.com/news/home/20221213006081/en/Ribose-Achieves-Continued-Verified-Compliance-to-BS-2020002022-Through-Annual-Assessment-Program-with-BSI-Pacific-Limited[BusinessWire].
