---
layout: post
title: "Ribose Achieves World's First STAR Certification with CSA Cloud Controls Matrix v4"
date: 2022-02-08 00:00:00
categories: ribose
featured: true
author:
  name: Ronald Tse
  email: tse@ribose.com
excerpt: >-
  Ribose Achieves World's First STAR Certification with CSA Cloud Controls Matrix v4
---
= Ribose Achieves World's First STAR Certification with CSA Cloud Controls Matrix v4

{blank}[8 February 2022 - London, UK; Seattle, WA]

http://www.ribose.com[Ribose]
has become the world's first cloud service provider (CSP) to achieve
https://cloudsecurityalliance.org[Cloud Security Alliance (CSA)] https://cloudsecurityalliance.org/star/[STAR Certification] using the newly released
https://cloudsecurityalliance.org/research/cloud-controls-matrix/[CSA Cloud Controls Matrix v4].

STAR Certification is the internationally recognized cloud security certification program from CSA that specifies comprehensive and stringent cloud security requirements on CSPs. The CSA Cloud Controls Matrix (CCM) is the de-facto standard for cloud security assurance and compliance, widely used in assessing cloud security performance of cloud implementations. CCM 4.0.1, the latest version of the matrix, is composed of 197 control objectives structured in 17 domains and details leading-edge cloud security practices, covering all key aspects of cloud technology.

The STAR Certification upgrade assessment was performed by BSI, a leading cloud assessment certification body, and original launch partner of the CSA STAR Certification program. Ribose's certification was granted on December 15, 2021.

"Our users are leading innovators in their industries. By achieving compliance to the latest and most comprehensive cloud security standard to date, users rest assured relying on Ribose for their success," noted Ronald Tse, founder of Ribose. "As the first organization worldwide to achieve STAR certification to CCM 3 and now CCM 4, our commitment in protecting users' information and privacy to the greatest extent is continually demonstrated."

"The CSA CCM, now in its fourth version, is recognised by many governments and industries to encompass leading edge best practices and guidance against the cyberthreats of today. We applaud Ribose's commitment to cloud security and its continual quest in providing a safe and secure environment for its users," explained Jim Reavis, CEO of CSA.

Mr. Michael Lam, Managing Director Assurance, APAC, BSI, remarked, "The landscape of cloud security shifts continuously as is the world we are living in today. In order to provide its users a secure and private way to work, Ribose has demonstrated its world-class commitment to achieving leading best practices in cloud security."
