#!/bin/bash

S3_BUCKET=$(aws s3api list-buckets --query "Buckets[?contains(Name, '${SITE_HOSTNAME}')] | [0].Name" | jq -r '.')

echo "[bucket] is '${S3_BUCKET}'"

aws s3 sync _site/ s3://${S3_BUCKET} --size-only --delete --region ${SITE_REGION}
