---
title: Conditions d'utilisation
description: Conditions d'utilisation de Ribose
revision_date: 2023-11-16
revision_date_template: "Dernière révision : {{ revision_date | date: '%d %B %Y' }}"
layout: page
hero_include: index-page-hero.html
---
:page-liquid:

CAUTION: Cette page est une traduction de la version anglaise, fournie à titre indicatif uniquement. En cas de divergence entre la version française et la version anglaise, la +++<a href="https://open.ribose.com/tos/">version anglaise</a>+++ prévaut.

== Conditions

. Ribose est l'unique propriétaire des produits Ribose,
logiciels, services et sites web (« Services ») de Ribose Inc. (une
société des îles Vierges britanniques) (« Ribose », « nous » ou « nos »).

. Ce qui suit sont les conditions générales d'utilisation des Services (« Conditions
Générales »).

. Des avis juridiques supplémentaires et/ou des conditions peuvent s'appliquer à certains
Services (« Conditions Supplémentaires »).

. Les Conditions Générales et les Conditions Supplémentaires constituent conjointement un accord
juridiquement contraignant entre vous et Ribose (« Conditions »). Les Conditions
Supplémentaires prévalent en cas de conflit entre les Conditions Supplémentaires et les Conditions
Générales pour le Service particulier auquel les Conditions Supplémentaires s'appliquent.

== Acceptation

. Votre utilisation des Services constitue votre accord d'être lié par les Conditions.
Clique pour accepter ou accepter les Conditions signifie également votre acceptation des
Conditions.

. Il est conseillé de vérifier périodiquement les Conditions Générales pour les mises à jour, car votre
utilisation continue des Services signifie votre acceptation de tout élément modifié.
Les Conditions Générales sont disponibles à link:/tos/[Conditions d'Utilisation].

== Fourniture des Services

. Les filiales et entités juridiques affiliées de Ribose
(« Filiales et Affiliés ») peuvent vous fournir les Services au nom de
Ribose. Vous reconnaissez et acceptez que les Filiales et Affiliés
seront habilités à vous fournir les Services.

. Ribose s'engage à fournir la meilleure expérience aux utilisateurs.
Vous reconnaissez et acceptez que la forme et la nature des Services peuvent
changer de temps à autre sans préavis.

. Ribose peut temporairement ou définitivement cesser de fournir les Services
en tout ou en partie à sa seule discrétion de Ribose sans
préavis. Vous pouvez cesser d'utiliser les Services à tout moment sans avoir besoin d'
informer spécifiquement Ribose.

. Vous reconnaissez et acceptez que si Ribose désactive l'accès à votre
compte, vous pouvez être empêché d'accéder aux Services, à votre compte
détails ou à tout contenu associé à votre compte.

. Vous reconnaissez et acceptez que bien que Ribose ne soit pas actuellement
limites sur les transactions ou la capacité des Services, ces limites peuvent
être définies ou modifiées par Ribose à tout moment, à la seule
discrétion de Ribose sans préavis.

. Les données que vous fournissez à Ribose peuvent être classées selon
le type et l'origine. Vous déclarez et garantissez que vous n'utiliserez pas les Services à
des fins interdits par les lois ou réglementations applicables aux
données relatives à votre utilisation des Services, et vous acceptez que votre utilisation
des Services et de tout Contenu se fait à vos propres risques.

== Propriété Intellectuelle

. Vous reconnaisgez et acceptez que Ribose détient tous les droits légaux, titre
et intérêt dans les Services, y compris tous les droits de propriété intellectuelle
qui existent dans les Services. Ces droits appartiennent à Ribose
dans le monde entier où ces droits existent, quel que soit le statut d'enregistrement
de ces droits.

. Les Services peuvent contenir des informations désignées confidentielles par
Ribose. Vous acceptez de ne pas divulguer ces informations
sans le consentement écrit préalable de Ribose.

. Les Services et tout leur contenu (articles, textes, photographies, images,
illustrations, graphiques, matériel vidéo, matériel audio et logiciel —
collectivement, la « propriété intellectuelle ») sont protégés par des
brevets, droits d'auteur, marques et autres lois de divers pays et
conventions internationales. La propriété intellectuelle est détenue ou
contrôlée par Ribose. Les Services sont protégés par des brevets et inventions
(« Brevets et Inventions »). De plus, les Services eux-mêmes
sont protégés par le droit d'auteur en tant qu'œuvre collective et/ou compilation.

. Aucune partie des Services ne peut être reproduite, dupliquée, copiée, vendue, ou
autrement exploitée à des fins commerciales qui ne sont pas expressément autorisées
par Ribose.

. Sauf ce qui est expressément établi dans les Conditions, vous ne pouvez pas copier, télécharger,
afficher, distribuer, publier, saisir dans une base de données, exécuter, modifier,
créer des œuvres dérivées, transmettre, publier, décompiler, effectuer
de l'ingénierie inverse, désassembler ou de toute autre manière exploiter
notre propriété intellectuelle ou les Services eux-mêmes, ou
toute partie de ceux-ci.

. Vous acceptez de ne pas supprimer, masquer ou modifier les avis de droits
de propriété (y compris les avis de droits d'auteur et de marque) qui
peuvent être joints ou contenus dans les Services.

. Le nom Ribose et les sceaux, logos et marques de la marque Ribose
sont des marques déposées/marques de design de Ribose, ou
autrement des marques non déposées qui véhiculent la bonne volonté
de Ribose. Tous droits réservés. Rien dans les Conditions ne vous donne
le droit d'utiliser aucun des noms commerciaux, marques, marques de service,
logos, noms de domaine et autres caractéristiques distinctives de la marque Ribose.

. Si vous avez été explicitement autorisé par Ribose par un accord
écrit séparé à utiliser ces caractéristiques de marque, vous acceptez que votre
utilisation de ces caractéristiques sera conforme à cet accord, aux Conditions et
aux directives de caractéristiques de marque de Ribose. Les directives de caractéristiques
de marque de Ribose peuvent être demandées en envoyant un e-mail à
{{ site.emails.support }}.

.. contester directement ou indirectement la validité, l'applicabilité ou la portée
de la couverture des Brevets et Inventions ou tout brevet ou demande de brevet
découlant ou découlant des Brevets et Inventions dans toute juridiction, et,
sans limiter la généralité de ce qui précède, accepte de ne pas interférer avec
les procédures d'examen ou de commencer ou de participer à toute procédure
d'opposition ou action judiciaire de nullité, qu'elle soit complète ou partielle,
concernant les Brevets et Inventions ; ou

.. déposer, ou faire déposer, toute demande de brevet basée sur ou découlant
des Brevets et Inventions, y compris, sans s'y limiter, toute demande de brevet
d'amélioration ou brevets basés sur ou liés aux Brevets et
Inventions ou toute demande de brevet ou brevet qui contourne les Brevets et
Inventions. Toute invention basée sur ou découlant des Brevets et
Inventions sera détenue uniquement par Ribose et vous acceptez de
céder toute cette invention à Ribose.

== Informations et Sécurité du Compte

. Vous pouvez être amené à fournir des informations vous concernant (« Informations
Personnelles ») pour accéder à certains Services ou pour
continuer à utiliser les Services. Ces informations peuvent être demandées dans le cadre
du processus d'inscription aux Services ou par votre utilisation continue des Services. Vous
acceptez que les Informations Personnelles que vous fournissez à Ribose seront toujours
exactes, correctes et à jour.

. Vous acceptez et comprenez que vous êtes seul responsable du contrôle d'accès à
votre compte, y compris la confidentialité des identifiants d'accès à votre
compte pour accéder aux Services. Par conséquent, vous acceptez d'être seul
responsable envers Ribose pour toutes les activités qui se produisent sous votre
compte.

. Si vous avez connaissance de toute utilisation non autorisée de votre compte ou de vos
identifiants d'accès, vous acceptez d'en informer immédiatement Ribose à
{{ site.emails.support }}.

. Vous acceptez l'utilisation de vos données conformément à la politique
de confidentialité de Ribose. La politique de confidentialité de Ribose est disponible à
link:/privacy/[Avis de Confidentialité].

== Utilisation Approprie

. Vous ne pouvez pas utiliser les Services à des fins illégales ou interdites par les
Conditions, ou causer des dommages sur ou via les Services. Vous vous engagez à ce qu'aucune de
vos actions sur ou via les Services ne violera aucune loi, réglementation, pratique ou directive
applicable locale, étatique, nationale ou internationale.

. Vous acceptez d'accéder aux Services uniquement via les interfaces fournies par
Ribose, sauf si vous avez été spécifiquement autorisé à le faire dans le cadre d'un
accord séparé avec Ribose. Vous acceptez de ne pas accéder ou
tenter d'accéder aux Services en utilisant des moyens automatisés, y compris via des
scripts et des crawlers.

. Vous acceptez de ne pas vous engager ou tenter de vous engager dans toute activité qui
interfère avec ou perturbe les Services ou toute partie de ce support,
constitue ou facilite les Services.

. Vous acceptez de défendre, indemniser et dégager Ribose, ses dirigeants,
directeurs, employés, agents, concédants de licence, partenaires commerciaux et fournisseurs
de toute réclamation, action ou demande réelle ou menacée, responsabilité et
règlement, y compris, sans s'y limiter, les frais juridiques et comptables raisonnables,
résultant de, ou allégué résulter de, votre utilisation des Services d'une manière qui
viole ou est alléguée violer les Conditions ou toute loi applicable.

== Contenu

. Les informations accessibles dans le cadre de ou via votre utilisation des Services peuvent
provenir d'un tiers autre que Ribose (« Contenu »).
Ce Contenu est de la seule responsabilité de la partie dont ce contenu
provient. Ribose ne fait aucune déclaration, recommandation
ou garantie de quelque nature que ce soit sur ce Contenu et n'accepte aucune responsabilité ou
obligation concernant toute partie de ce Contenu.

. Vous comprenez que certains Contenus présentés dans ou via les Services,
y compris les publicités et contenus sponsorisés, peuvent être une propriété intellectuelle
détenue par des tiers qui fournissent ce Contenu à Ribose. Vous
acceptez de ne pas modifier, louer, prêter, vendre, distribuer ou créer des œuvres dérivées
basées sur ce Contenu en tout ou en partie, sauf si vous avez été autorisé
à le faire par les propriétaires de ce Contenu.

. Ribose se réserve le droit de filtrer, examiner, modifier,
refuser ou supprimer tout Contenu des Services.

== Votre Contenu

. Ribose n'obtient aucun droit, titre ou intérêt de vous (ou de vos
concédants de licence) en vertu des Conditions ou sur tout Contenu que vous
soumettez, publiez ou affichez sur ou via les Services autre que la licence limitée
stated below. Vous acceptez que vous êtes seul responsable de la protection et de l'application de vos
droits et Ribose n'a aucune obligation de le faire en votre nom.

. Vous acceptez que vous êtes seul responsable (et que Ribose
n'a aucune responsabilité envers vous ou envers tout tiers) de tout Contenu que
vous créez, transmettez ou affichez via ou dans les Services, et donc seul
responsable de toute conséquence de ces actions, y compris tout dommage ou perte
envers Ribose.

. Vous acceptez de ne pas utiliser toute marque, marque de service, nom commercial, logo
de toute société ou organisation d'une manière susceptible ou destinée à causer
une confusion sur le propriétaire ou l'utilisateur autorisé de ces marques, noms ou logos.

. Pour le contenu soumis, publié ou affiché sur ou via les Services (« Votre
Contenu »), vous accordez à Ribose une licence perpétuelle, irrévocable, mondiale,
libre de redevances et non exclusive de reproduire, adapter, modifier, traduire,
publier, exécuter publiquement, afficher publiquement et distribuer Votre Contenu, pour
le seul but de permettre à Ribose d'afficher, de distribuer,
de fournir et de promouvoir les Services (« Licence de Contenu »).

. Ribose peut offrir des services syndiqués via ou en conjonction avec
d'autres parties. Vous autorisez Ribose à rendre Votre Contenu
disponible à d'autres parties avec lesquelles Ribose a des relations pour
la fourniture de services syndiqués, et à utiliser ce Contenu en lien avec
la fourniture de ces services via la Licence de Contenu.

. Vous confirmez et garantissez à Ribose que vous avez tous les droits,
pouvoir et autorité nécessaires pour accorder la Licence de Contenu. De plus, vous
confirmez et garantissez que Ribose ne violera aucun droit
d'un tiers, et n'encourra aucune responsabilité ou dommage de quelque nature que ce soit
en raison de votre soumission de Votre Contenu à Ribose ou de la fourniture des
Services à vous.

== Contenu Publicitaire

. Vous acceptez que Ribose peut placer des publicités sur les Services. Certains
annonces ou promotions peuvent être ciblées vers certaines informations stockées sur
ou associées aux Services. La forme, la nature et la mise en œuvre de la publicité
par Ribose sur les Services peuvent changer sans préavis.

== Contenu Externe

. Les Services peuvent fournir des liens vers des ressources non exploitées par
Ribose (« Ressources Externes »). Vous reconnaissez et acceptez que
Ribose n'est pas responsable des Ressources Externes, et donc
n'est pas responsable des pertes ou dommages que vous pouvez subir en raison de
l'accès aux Ressources Externes, ou en raison de la confiance placée dans les
Ressources Externes.

. Ribose se réserve le droit de supprimer ou de dissocier toute
Ressource Externe sans préavis et sans encourir aucune responsabilité de sa part.

. Vous reconnaisgez et acceptez que les citations ou commentaires du
personnel de Ribose sur les Ressources Externes ne reflètent pas l'opinion de
Ribose.

== Logiciel Ribose

. Ribose vous attribue une licence personnelle, mondiale, libre de redevances,
non cessible et non exclusive pour utiliser le logiciel qui vous est fourni par
Ribose dans le cadre des Services ou pour faciliter la fourniture des
Services à vous (« Logiciel »). Cette licence est dans le seul but de
vous permettre d'utiliser les Services conformément aux Conditions.

. Vous ne pouvez pas copier, télécharger, afficher, distribuer, publier, saisir dans
une base de données, exécuter, modifier, créer des œuvres dérivées, transmettre, publier, décompiler,
effectuer de l'ingénierie inverse, désassembler, tenter d'extraire le code source ou de toute autre manière
exploiter le Logiciel ou toute partie de celui-ci, sauf si requis par la loi ou explicitement
autorisé par Ribose par écrit.

. Le Logiciel peut nécessiter des mises à jour de Ribose de temps à autre.
Vous acceptez de recevoir ces mises à jour et d'autoriser Ribose à vous
les fournir afin de faciliter la fourniture des Services à vous.

== Transactions

. Certaines zones des Services vous permettent de postuler votre candidature à un ou plusieurs des
programmes Ribose. Les conditions de ces programmes et les conditions
régissant votre candidature et participation à ces programmes sont énoncées dans le ou les
Accords de Licence pour ce(s) programme(s). La réception d'une confirmation de commande
électronique ou autre ne signifie pas notre acceptation de votre candidature, ni ne constitue
une acceptation dans le programme. Ribose se réserve le droit, après réception de votre commande,
d'accepter ou de refuser votre candidature comme prévu dans l'Accord de Licence
régissant le(s) programme(s) particulier(s) auquel(s) vous postulez.

== Résiliation

. Les Conditions continueront à s'appliquer jusqu'à leur résiliation comme indiqué ci-dessous.

. Vous pouvez résilier votre accord juridique avec Ribose, en :

.. notifiant Ribose par un avis écrit envoyé à
l'adresse de Ribose décrite au début des Conditions ; et

.. fermant ou supprimant vos comptes pour tous les Services, si cette option
vous est disponible.

. Ribose peut résilier son accord juridique avec vous si :

.. vous avez violé toute disposition des Conditions, ou déterminé par
Ribose que vous êtes incapable de vous conformer aux Conditions ; ou

.. Ribose est tenu de le faire par la loi ; ou

.. Ribose n'est plus en mesure de vous fournir les Services

. En cas de résiliation des Conditions, tous les droits, obligations et responsabilités
légaux dont vous et Ribose avez bénéficié, été soumis (ou qui se sont accumulés au fil du temps
alors que les Conditions étaient en vigueur) ou qui sont exprimés comme continuant indéfiniment,
ne seront pas affectés par cette cessation, et les dispositions des sections « Déclaration de Garantie, Limitation de Responsabilité et Dégagement » et « Autres » continueront à s'appliquer à ces
droits, obligations et responsabilités indéfiniment.

== Déclaration de Garantie, Limitation de Responsabilité et Dégagement

. Ribose ne garantit pas l'exactitude des informations trouvées sur les
Services. Votre confiance dans les informations trouvées sur les Services se fait à vos propres risques.

. LES SERVICES, ET TOUT LEUR CONTENU, VOUS SONT FOURNIS « EN L'ÉTAT ». RIBOSE NE FAIT
AUCUNE GARANTIE NI REPRÉSENTATION, EXPRESSE OU IMPLICITE, Y COMPRIS, MAIS SANS S'Y LIMITER,
LES GARANTIES IMPLICITES DE QUALITÉ MARCHANDE, D'ADÉQUATION À UN USAGE PARTICULIER,
DE TITRE, DE NON-VIOLATION DES DROITS DE TIERS, D'EXACTITUDE DES DONNÉES,
OU DE JOUISSANCE TRANQUIILLE.

. EN AUCUN CAS RIBOSE OU TOUTE AUTRE PERSONNE IMPLIQUÉE DANS LA CRÉATION
DES SERVICES ET DE LEUR CONTENU NE SERA RESPONSABLE DE TOUT DOMMAGE OU PRÉJUDICE,
Y COMPRIS TOUT DOMMAGE DIRECT, INDIRECT, ACCESSOIRE, SPÉCIAL, CONSÉCUTIF, PUNITIF
OU AUTRE DOMMAGE RÉSULTANT DE TOUTE CIRCONSTANCE IMPLIQUANT LES SERVICES OU LEUR CONTENU
(Y COMPRIS MAIS SANS S'Y LIMITER LES DOMMAGES OU PRÉJUDICES CAUSÉS PAR ERREUR, OMISSION,
INTERRUPTION, DÉFAUT, DÉFAILLANCE DE PERFORMANCE, TRANSMISSION MAL DIRIGÉE OU REDIRIGÉE,
ÉCHEC DE CONNEXION INTERNET, UTILISATION NON AUTORISÉE DES SERVICES,
PERTE DE DONNÉES, RETARD DANS L'OPÉRATION OU LA TRANSMISSION, FAILLE DE SÉCURITÉ,
DÉFAILLANCE DE LIGNE, CONDUITE DIFFAMATOIRE, OFFENSANTE OU ILLICITE DE TOUT UTILISATEUR DES SERVICES,
OU VIRUS INFORMATIQUE, VERS, CHEVAL DE TROIE OU AUTRE COMPOSANT NUISIBLE), MÊME SI VOUS
AVEZ INFORMÉ RIBOSE À L'AVANCE DE LA POSSIBILITÉ DE TEL DOMMAGE.

. RIBOSE NE GARANTIT NI NE FAIT AUCUNE REPRÉSENTATION CONCERNANT LES MATÉRIAUX SUR
LES SERVICES EN TERMES D'ACTUALITÉ, D'EXACTITUDE, DE PRÉCISION, DE FIABILITÉ,
OU AUTREMENT. BIEN QUE NOUS FAISONS DES EFFORTS RAISONNABLES POUR FOURNIR DES INFORMATIONS
EXACTES ET ACTUELLES SUR RIBOSE SUR LES SERVICES, VOUS NE DEVEZ PAS PRÉSUMMER QUE
LES INFORMATIONS FOURNIES SONT TOUJOURS À JOUR OU QUE LES SERVICES CONTIENNENT TOUTES LES
INFORMATIONS PERTINENTES DISPONIBLES SUR NOTRE SOCIÉTÉ. NOUS NE PRENONS AUCUN ENGAGEMENT
DE VÉRIFIER OU DE MAINTENIR L'ACTUALITÉ DE CES INFORMATIONS.

. La loi applicable peut ne pas permettre l'exclusion de certaines garanties ou la
limitation ou l'exclusion de la responsabilité pour les dommages accessoires ou consécutifs.
Par conséquent, certaines des limitations ou exclusions ci-dessus peuvent ne pas s'appliquer à vous.
Cependant, en aucun cas, la responsabilité agrégée de Ribose envers vous ou
tout tiers pour les dommages, pertes et causes d'action ne dépassera pas le montant
payé par vous, le cas échéant, pour accéder aux Services ou 100 $US, le moindre des deux.
Vous acceptez d'engager toute action dans un délai d'un an à compter de la date de
survenance de la cause d'action, et que les actions engagées après cette date seront prescrites.

. Dans l'éventualité où vous avez un différend avec Ribose, vous dégagez
Ribose (et nos dirigeants, directeurs, agents et employés) des réclamations,
demandes et dommages (réels et consécutifs) de toute nature, connus et inconnus,
suspectés et non suspectés, divulgués et non divulgués, découlant de ou liés de quelque manière que ce
soit à ces différends.

== Autres

. Ribose se réserve le droit de rechercher tous les recours disponibles en droit et en équité
pour les violations des Conditions, y compris la suspension ou le blocage de
votre accès aux Services.

. Rien dans les Conditions ne constitue ou ne doit être considéré comme constituant un partenariat
entre les parties et aucune partie n'a l'autorité ou le pouvoir de
lier l'autre ou de créer une responsabilité envers l'autre de quelque manière que ce soit ou à
toute fin.

. Vous ne devez pas céder, transférer, transmettre, concéder sous-licence,
sous-traiter, déléguer ou autrement disposer, en tout ou en partie,
aucun de vos droits ou obligations en vertu des Conditions
sans obtenir l'avis écrit préalable de Ribose.

. Aucun retard ou échec de Ribose à appliquer l'une des
Conditions ne constitue une renonciation de l'un de nos droits en vertu des
Conditions. Ni la réception de tout fonds par Ribose ni la confiance de toute personne
dans nos actions ne doit être considérée comme constituant une renonciation de toute partie des
Conditions. Seule une renonciation spécifique,
écrite, signée par un représentant autorisé de Ribose
aura un effet juridique.

. Si une clause ou disposition
établie dans les Conditions est déterminée comme illégale, invalide ou inapplicable
en vertu du droit présent ou futur, la clause ou disposition est réputée supprimée
sans affecter l'applicabilité de toutes les clauses ou dispositions restantes.

== Loi Applicable et Juridiction

. L'utilisateur accepte que les
Conditions et tout différend découlant de ou lié aux Conditions et/ou à l'Avis
de Confidentialité ou aux Services sera régis par et interprétés conformément
aux lois de la RAS de Hong Kong sans égard aux conflits de
lois, et le lieu exclusif de tout différend relatif à cet Accord sera
les tribunaux de la RAS de Hong Kong, à condition que Ribose
sera toujours autorisé à engager toute action ou procédure contre l'utilisateur dans tout
autre tribunal compétent et Ribose sera toujours autorisé à
choisir les lois de toute autre juridiction compétente.

. Cette déclaration de Conditions d'Utilisation en langue anglaise est l'accord officiel de
Ribose avec les utilisateurs des Services. En cas d'incohérence entre cette
déclaration de Conditions d'Utilisation en langue anglaise et sa traduction dans une autre
langue, ce document en langue anglaise prévaut.

. Spécifiquement exclue de l'application à cet Accord la loi connue sous le nom de
Convention des Nations Unies sur les Contrats de Vente Internationale de Marchandises.

== Modifications des Conditions

. Ribose se réserve le droit, à sa seule discrétion, de modifier, altérer ou autrement
changer les Conditions à tout moment. Nous fournirons un avis de ce changement sur la
page des Conditions Générales.

. Votre utilisation continue des Services constitue votre acceptation et votre accord
pour être lié par ces changements sans limitation, qualification ou modification. Si à tout moment vous
déterminez que vous n'acceptez pas ces changements, veuillez vous référer à la section
« Résiliation » pour résilier la relation.

== Pour Plus d'Informations

. Si vous avez des questions concernant nos Conditions d'Utilisation, veuillez envoyer un
e-mail à {{ site.emails.support }}.
