name: build

on:
  push:
    branches:
      - '!main'
      - '!staging'
  pull_request:

jobs:
  build:
    name: Build hub
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hub
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: hub/package-lock.json
      - run: npm ci
      - run: npm run build
