name: links

on:
  push:
    branches:
      - main
      - staging
  pull_request:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  link_checker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hub
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: hub/package-lock.json
      - run: npm ci
      - run: npm run build

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Run lychee
        uses: lycheeverse/lychee-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: >-
            --verbose --no-progress --cache --max-cache-age 1d
            --base "$PWD/hub/dist"
            --exclude 'iso\.org'
            --exclude 'iec\.ch'
            --exclude 'mitre\.org'
            --exclude 'webtrust\.org'
            --exclude 'anab\.ansi\.org'
            --exclude 'nytfriedmanforum\.com'
            --exclude 'singaporestandardseshop\.sg'
            --exclude 'github\.com'
            --exclude 'stevieawards\.com/iba/ribose-inc-hong-kong'
            --exclude 'anab\.org'
            --exclude 'spc\.net\.cn'
            --exclude 'metanorma\.org/posts'
            --exclude 'relaton\.org/posts'
            --exclude 'gdei\.gov\.cn'
            --exclude 'kotoshu\.org'
            --exclude 'electropedia\.org'
            --exclude 'gitlab\.com/my-account'
            --exclude 'standards\.calconnect\.org/calconnect/cc-10001'
            --exclude 'relaton\.org/blog/2022-12-28'
            --exclude 'relaton\.org/asciibib'
            --exclude 'unece\.org'
            --exclude 'ras\.ru'
            --exclude 'pdfa\.org'
            --exclude 'sparxsystems\.com'
            --exclude 'ansi\.org'
            --exclude 'diataxis\.fr'
            --exclude 'braintraffic\.com'
            --exclude 'technical-writing-training-and-certification\.com'
            --exclude 'primmel/private-models'
            --exclude 'primmel/smartcab'
            --exclude 'stevieawards\.com/iba/ribose-inc-hong-kong-new-product'
            --exclude 'newswire\.ca/en/story/1035'
            --exclude 'sportsoho\.com'
            --exclude 'sustainablebrands\.com/news_and_views/leadership'
            --exclude 'govstore\.service\.gov\.uk'
            --exclude 'prnewswire\.se'
            'hub/dist/**/*.html'
          fail: true
